### ISSUE TITLE
Join grocy's Transifex

### ISSUE THREAD

**Issue by yarons** [patzly/grocy-android#101]
grocy is being translated using Transifex, is there any chance we'll try to contact grocy's maintainer and ask him to add this project to the Transifex project?

https://www.transifex.com/grocy/grocy/

I'd love to help both sides if needed.

**Comment by MrJohnZoidberg** [comment]
Hi, we have created another organization for our project, you can help translate it in your language there:
[https://www.transifex.com/grocy-android/grocy-android](https://www.transifex.com/grocy-android/grocy-android)

**Comment by MrJohnZoidberg** [comment]
Did I solve your question?

**Comment by yarons** [comment]
Pretty much, thank you and sorry I didn't see it in the README, thanks!

**Comment by MrJohnZoidberg** [comment]
I just saw that you requested `Hebrew` and `Hebrew (Israel)`, please let me check what language abbreviation we need for our app.

**Comment by yarons** [comment]
Hebrew is better if possible :) There's a mapping problem on certain Android versions, usually it `he` but sometimes the ISO code is `iw` for some reason.

**Comment by MrJohnZoidberg** [comment]
Thanks for the link. So I approve `Hebrew` and not `Hebrew (Israel)`, right?
If someone has a problem with that, we can add `Hebrew (Israel)` and copy your translated `strings.xml` into it.

**Comment by MrJohnZoidberg** [comment]
Is Hebrew written from right to left? Because there can be some tiny string issues for RTL languages in our app. You can open a new issue if you found something which doesn't seem to be right.

Thanks for your contribution! :)

**Comment by yarons** [comment]
`Hebrew` it is 🙂 

Hebrew is indeed RTL, in order to bypass these problems we can create some overrides using `layout-rtl`, there's a special guide for that:
https://material.io/design/usability/bidirectionality.html

**Comment by MrJohnZoidberg** [comment]
Thank you for the link, I've just forced RTL layout on my phone and spotted a few mirroring issues in our app – I will correct these soon.
