### ISSUE TITLE
Fix plurals

### ISSUE THREAD

**Issue by yarons** [patzly/grocy-android#112]
Instead of using different cases in code you can simply use plurals for these strings:
1 day
%1$d days

As they appear in the following function:
https://github.com/patzly/grocy-android/blob/master/app/src/main/java/xyz/zedler/patrick/grocy/util/DateUtil.java#L117

Better use the plural option as explained here:
https://developer.android.com/guide/topics/resources/string-resource#Plurals

**Comment by MrJohnZoidberg** [comment]
Thanks for the link, I've already read that at the point where we were working on these code parts. But we were lazy and we thought that this project would only be translated in one or two languages. :)

I will improve this soon.

**Comment by yarons** [comment]
Feel free to tap your own shoulder regarding the localization and public relations matter :)

**Comment by MrJohnZoidberg** [comment]
Do you want a new version with your translation as fast as possible or can you wait a few days?

Because currently I'm not working on the master branch and hence there would be no changes in the new version except a new language – and that's not interesting for users of all oher languages IMHO.
Or what do you think?

**Comment by yarons** [comment]
> Do you want a new version with your translation as fast as possible or can you wait a few days?

I'm patient, take as much time as you need 🙂.

**Comment by MrJohnZoidberg** [comment]
Wow, I have just seen that you are a very passionate translator and that you've contributed to many projects that I love!
Keep up the great work!

**Comment by yarons** [comment]
Thank you so much! I'll keep doing my best 🙂
