### ISSUE TITLE
Shopping scanning loses progress when screen is rotated

### ISSUE THREAD

**Issue by dueringa** [patzly/grocy-android#116]
Hi,

as stated in the title, when I'm in scanning mode to shop, and I accidentally tilt my phone so the screen rotates, everything I entered so far is lost, which is especially frustrating when creating new products.

**Comment by MrJohnZoidberg** [comment]
Hi,

yes, that's a bug – I'm really sorry for this and thanks for reporting it!
I will try to fix it right now.

**Comment by dueringa** [comment]
Thanks a lot :) (also, sorry for the "frustrating" part, that was unnecessary)
