### ISSUE TITLE
In shopping/scanner mode, set amount

### ISSUE THREAD

**Issue by dueringa** [patzly/grocy-android#117]
Vague suggestion:

When using the scanner mode for shopping there seems to be no way to set the amount (unless I'm not finding it).

I guess the user is expected to scan the barcode again to add another item to the inventory? From what I've gathered, I'm not the only one having problems with camera barcode scanning. It would be convenient to have a way to set the amount without scanning again. I'm not sure how to handle this exactly. Maybe add an "Add another" button to the toast notification that appears? (From what I've gathered the scan view is from an external library, so I guess adding the button to the view/screen itself is not that easy).

**Comment by MrJohnZoidberg** [comment]
Thanks for your suggestion, I will look into it.
Adding buttons to the layout is easy, because it's an overlay over the library's layout.

What problems with the barcode scanner do you experience? Maybe these can disappear when using ML Kit barcode recognition (I'm currently working on it, there are some great [advantages](https://github.com/patzly/grocy-android/blob/master/FAQ.md#user-content-faq6)).

**Comment by dueringa** [comment]
I mainly have problems problems with my camera not focusing correctly and thus the barcode is not recognized at all. It seems there are also problems when the barcode is printed on reflecting plastic packaging which reflect the light. (Having barcode scanner support as mentioned in #72 may also help circumventing these problems)

**Comment by loziniak** [comment]
It would also be useful when adding stock with units like `grams`, when you have to add for example 200 grams :-) There could be an input with +/- buttons showing on first scan, where you can enter value, or just scan another item, and input increases itself automatically.

**Comment by MrJohnZoidberg** [comment]
In the current alpha preview version there is no "batch mode" anymore, instead the forms on the purchase/consume pages behave like the web interface. I hope you like it, the code for the old "batch mode" was IMHO too buggy and not that good.
