### ISSUE TITLE
I don't get how barcode scan works...

### ISSUE THREAD

**Issue by canDry** [patzly/grocy-android#12]
I scan the barcode of something I use and want to register... it doesn't let me "link".

**Comment by patzly** [comment]
A documentation would be helpful, is already planned...

Is your product already created and purchased? Remember that you have to create and purchase a product before you can consume it.
For linking it has also to be created.

Can you please give us a more detailed description of what you're trying to do and the steps you've done already?

**Comment by patzly** [comment]
Help for scanning and other actions is planned (#9).
