### ISSUE TITLE
Filter by product group like in web interface

### ISSUE THREAD

**Issue by szimszon** [patzly/grocy-android#120]
Hi,
I wonder if you could help me.
I have product groups like:
* Vegetables
* Vegetables / Fruits

In the web page if I filter for "Vegetables" I get the list of products in groups like "Vegetables" and "Vegetables / Fruits".

I'm wondering if it could be implemented also in the app?

With this feature I could query for all vegetables (also in "sub" groups)...

**Comment by patzly** [comment]
In the bottom app bar, tap ob the three dots and select Filter > Product group

I think that's what you're searching for...

**Comment by patzly** [comment]
Oh now I understand...
That's right, it works with the web interface, but it's complicated to implement. Right now we have not much time, so we have other priorities for this app.
I think for now the easiest solution for your problem are two different groups, but I'll leave that issue open.
