### ISSUE TITLE
Adding products to stock via e-check

### ISSUE THREAD

**Issue by ivanboytsov** [patzly/grocy-android#121]
In Russia we get electronic checks in json format along with paper. It would be nice to have ability to load this json into the app with automatically set product names, prices, quantities and shops.
Example:
{"user":"","retailPlaceAddress":"","userInn":"9705118142","requestNumber":97,"shiftNumber":375,"operator":"Сист. администратор","operationType":1,"totalSum":211715,"cashTotalSum":0,"ecashTotalSum":211715,"kktRegId":"0002986821006307","fiscalDriveNumber":"9285000100096468","fiscalDocumentNumber":133769,"fiscalSign":3389670843,"items":[{"name":"Молоко Parmalat ультрапастеризованное 1,8% 1 л бзмж","price":7819,"sum":15638,"quantity":2.0},{"name":"Пельмени Мираторг домашние","price":23500,"sum":47000,"quantity":2.0},{"name":"Макаронные изделия Шебекинские рожок полубублик №202","price":5299,"sum":5299,"quantity":1.0},{"name":"Салат Aro дальневосточный из морской капусты","price":2649,"sum":2649,"quantity":1.0},{"name":"Губки для посуды Fine Life 5 штук","price":1900,"sum":1900,"quantity":1.0},{"name":"Творог Простоквашино 2% бзмж","price":7690,"sum":15380,"quantity":2.0},{"name":"Азу из говядины Эколь халяль охлажденное ~600 г","price":29264,"sum":29264,"quantity":1.0},{"name":"Зефир Шармэль Яблоко","price":11500,"sum":11500,"quantity":1.0},{"name":"Огурцы корнишоны 300 г","price":12990,"sum":12990,"quantity":1.0},{"name":"Макаронные изделия Шебекинские перья №343","price":5299,"sum":5299,"quantity":1.0},{"name":"Шоколад Алёнка много молока","price":4490,"sum":8980,"quantity":2.0},{"name":"Картофель молодой сетка","price":5725,"sum":5725,"quantity":1.0},{"name":"Лампа светодиодная Старт Экономь 10W E27 груша холодный белый","price":9900,"sum":9900,"quantity":1.0},{"name":"Кефир Домик в Деревне 3,2% 1 л бзмж","price":8191,"sum":8191,"quantity":1.0},{"name":"Филе цыпленка-бройлера Троекурово охлажденное 900 г","price":22200,"sum":22200,"quantity":1.0},{"name":"Доставка H10364314210","price":9800,"sum":9800,"quantity":1.0}],"nds18":7014,"nds10":15422,"dateTime":1585284480,"taxationType":1,"localDateTime":"2020-03-27T07:48"}

**Comment by ivanboytsov** [comment]
I did it myself with tasker and rest api, but it is not so convenient. And I lost ability to set expiry dates later. Within the app it can be implemented in better way.

**Comment by MrJohnZoidberg** [comment]
Mmh, that would be a local feature which should only appear if you are in Russia... Maybe I will implement it when I have enough time, but there are higher priorities currently.

**Comment by MrJohnZoidberg** [comment]
Sorry, I've decided to mark this issue as "won't fix" because it has a too low priority for us and would only be interesting for a few users. Maybe you (or others) can code this yourself and create a merge request (but that's hard because our code is not that great to read).
