### ISSUE TITLE
Shopping List: Auto-select shopping list when adding via app icon shortcut

### ISSUE THREAD

**Issue by jo-me** [patzly/grocy-android#122]
Feature suggestion: see below

**Comment by MrJohnZoidberg** [comment]
Hello, can you provide a description? Else we don't know what you mean.

**Comment by jo-me** [comment]
When long pressing the app icon I can add an item to a shopping list.
In this screen there is no shopping list preselected, so every time you have to select one.

In my case I have only one, so this is tedious.
In general, it might make sense to have a default shopping list that is preselected. 

This would save 2 clicks for every addition via Icon shortcut

**Comment by MrJohnZoidberg** [comment]
Oh yes, that's a bug. The last selected shopping list should be preselected.

**Comment by jo-me** [comment]
Ah ok, 
It is currently only preselected when going to that screen from the shopping list screen.
From the app icon shortcut nothing is selected.

**Comment by MrJohnZoidberg** [comment]
Thanks for reporting that, we will fix it when we have time.
