### ISSUE TITLE
Consume: Error occured

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#124]
Consume by Scan
Ask location and ask stock entry leads to "error occured"
Having only one of them activated works proper.

**Comment by MrJohnZoidberg** [comment]
Thanks for reporting that! I will look into it as soon as I have time.

**Comment by MrJohnZoidberg** [comment]
I think I've fixed the issue now (in upcoming v1.9.0), but if it's still there then please reopen it.
