### ISSUE TITLE
login via duckdns.org

### ISSUE THREAD

**Issue by KrautJasp** [patzly/grocy-android#128]
I have problems logging in with duckdns.org 
Is this even possible? and if so, how?

**Comment by MrJohnZoidberg** [comment]
Sorry, we can't help you with that because we don't know this service and we never tested it – so you have to find out for yourself or maybe you can find something on the internet.

**Comment by KrautJasp** [comment]
Sorry, I was a bit hasty. I have now found a solution and can use the application now. But anyway, thanks for the answer!
grocy-android is a really great project!

**Comment by MrJohnZoidberg** [comment]
Thanks for your kind words!

**Comment by Skinderholm** [comment]
> Sorry, I was a bit hasty. I have now found a solution and can use the application now. But anyway, thanks for the answer!
> grocy-android is a really great project!

How did you solve it?

**Comment by KrautJasp** [comment]
Hey,
I have used this [video](https://www.youtube.com/watch?v=98EXFyDwe3E) to configure DuckDNS.
But additionally I added the following with the file editor in the configuration file:
(as it is explained [here](https://www.home-assistant.io/integrations/panel_iframe/#configuration-variables))

![qwhtm](https://user-images.githubusercontent.com/72578230/96994215-acfdf180-152c-11eb-9b4c-9af9fa650753.png)
(I used port 22)
But I don't know if this was really necessary, in any case it worked ¯\_( ͡' ͜ʖ ͡')_/¯

Of course I followed the instructions from the [FAQ](https://github.com/patzly/grocy-android/blob/master/FAQ.md#user-content-faq4) accordingly.
And finally I entered the server address as shown in the picture and the API Key in the APP and it worked.
