### ISSUE TITLE
Error: TransactionTooLargeException

### ISSUE THREAD

**Issue by donk7413** [patzly/grocy-android#129]
Hello since this morning, I have this error and I can't access to the shopping list or the stock :

`10-09 06:48:41.385  7941  7941 E AndroidRuntime: FATAL EXCEPTION: main
10-09 06:48:41.385  7941  7941 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 7941
10-09 06:48:41.385  7941  7941 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1610536 bytes
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8347)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 1610536 bytes
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:532)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4561)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
10-09 06:48:41.385  7941  7941 E AndroidRuntime: 	... 7 

> more`

**Comment by donk7413** [comment]
[stock.txt](https://github.com/patzly/grocy-android/files/5352844/stock.txt)
This is the json of my stock list, please let me know if you need more informations

**Comment by donk7413** [comment]
After more investigations, it's look like that some quantity units that I have define make the error. I deleted them and everything get back to normal. I don't know if it was UQ conversions or the units self . I will do more test to see. Keep you in touch

**Comment by MrJohnZoidberg** [comment]
Hi, we already know this error. It occurs if a list of some objects which is transferred from one screen to another is too large, so maybe you have many products in your database. Our app needs to be optimized to handle these large lists (instead of transferring a list of all products, we could transfer only the necessary stuff like product names).

I don't understand, why the error was fixed after you deleted some quantity units, but maybe it's connected with the issue I described above.

**Comment by MrJohnZoidberg** [comment]
I just saw that your stock list is indeed very huge :-)

I will try to work on this as soon as I have enough time.

**Comment by donk7413** [comment]
It's fixed with the timeout fixe in #177. I have more than 99+ UQ conversion and over 3000+ products and 200+ stock items and no crash actually.

**Comment by MrJohnZoidberg** [comment]
Wow, that's cool!
