### ISSUE TITLE
Scanning to Purchase should respect the factor for quantity unit purchase and quantity unit stock

### ISSUE THREAD

**Issue by bfayers** [patzly/grocy-android#13]
For example, I have a product setup with the Quantity Unit Purchase set to Pack and the Quantity Unit Stock set to Pieces with a factor of 4, however when I scan the barcode in the app to purchase it only adds 1 to stock instead of 4.

The consume behavior is as expected, only consuming one at a time (however, perhaps a custom field set to how much default consume should be per product would be useful for products like flour where scanning every time for every gram used would be inconvenient.)

**Comment by patzly** [comment]
Right now we have to learn for our Abitur, so please be patient.

Thanks for the detailed description, we will work on that.
In the current version only one unit is used, ignoring the factor and other units (complicated to implement). See the master product edit screen: only stock unit can be edited now, but we will implement other fields in the next versions.

For flour I would recommend you to set the unit to pack, one pack is opened, then consumed and you open the next one. I think this is much easier to manage than grams, especially if one pack is always e.g. 1000g.
