### ISSUE TITLE
SOCKS proxy support

### ISSUE THREAD

**Issue by jpds** [patzly/grocy-android#130]
I'd like to try hosting grocy on a Tor hidden service (as it really doesn't need to be on the public Internet) and for that to work; the Android app needs to support setting a SOCKS proxy which can be pointed at Orbot's SOCKS port.

Also removes the requirement of having a TLS certificate as the connection is end-to-end encrypted anyway.

**Comment by MrJohnZoidberg** [comment]
Hi, could you provide a test instance on a hidden service for me so that I'm able to write working code (my email: mrjohnzoidberg@mailbox.org)?
Because I don't know how to setup such a hidden service and I don't want to spend time on this.

**Comment by MrJohnZoidberg** [comment]
I've just found this great [website](https://business.blogthinkbig.com/api-rest-requests-tor-hidden-services-android-apk/). Do you agree that you need Orbot on your phone to connect with the Tor network? Just want to ask so that I know I'm right with that.

**Comment by jpds** [comment]
It's actually really simple to set up a hidden service, for example in Debian:

```
$ sudo apt install -y tor
```

Uncomment the lines in `/etc/tor/torrc`:

```
HiddenServiceDir /var/lib/tor/hidden_service/
HiddenServicePort 80 127.0.0.1:80
```

Restart tor:

```
$ sudo systemctl restart tor
```

...and done, you'll have a hostname in `/var/lib/tor/hidden_service/hostname` that will forward HTTP requests to it to the local HTTP server (which may need configuring to recognize the new `.onion` domain).

> Do you agree that you need Orbot on your phone to connect with the Tor network?

Indeed.

**Comment by MrJohnZoidberg** [comment]
Thanks, I now have a hidden service running.
Should I only check if the URL entered in the app has ".onion" in it and then in this case I request a connection with Orbot (like the [website](https://business.blogthinkbig.com/api-rest-requests-tor-hidden-services-android-apk/) said):

```java
if (!OrbotHelper.get(this).init()) {
        OrbotHelper.get(this).installOrbot(this);
}
```

Right? Or do I have to make an option to set a proxy like you said?

**Comment by jpds** [comment]
Someone might want to use Tor on their phone to access a server that's still available on the normal Internet, but I guess that'd be rare.

Looking at other apps, there are some such as F-Droid and [RedReader](https://github.com/QuantumBadger/RedReader) expose a "Use Tor" option which interfaces with Orbot. Others such as OsmAnd+ allow access to proxy settings (such as when you want to use a VPN provider's SOCKS proxy).

**Comment by MrJohnZoidberg** [comment]
Ok, so for v1.9.0 I will implement it like the website example and with ".onion" recognition and in v2.0.0 I will implement a proxy option and a Tor option like in F-Droid (not until v2.0.0 because there was a settings page overhaul and I don't want to mess up current settings in master branch; in v2.0.0 on login page there will be a link to settings page for making such configs).

**Comment by MrJohnZoidberg** [comment]
Now I'm finished with the intial ".onion" support, you can build an APK by yourself or wait until v1.9.0 is released. :)

**Comment by MrJohnZoidberg** [comment]
Quick update here: socks and onion support will come later in v2.0 because priority is now on more important things.

**Comment by MrJohnZoidberg** [comment]
There is now Tor and HTTP proxy support like in F-Droid. -> available in next beta version
