### ISSUE TITLE
Geschäft für Artikel 

### ISSUE THREAD

**Issue by ThomasKujawa** [patzly/grocy-android#147]
Im Browser konnte ich das anlegen.

In der App geht das nicht? Bin ganz neu bei grocy.

**Comment by patzly** [comment]
Bitte schreiben Sie hier nur auf Englisch, damit es jeder lesen kann.
Unsere App ist nicht zusammenhängend mit dem Grocy-Projekt, sie ist nur eine native Oberfläche für Android. Was mit der Browser-Applikation funktioniert, muss in keinster Weise mit unserer App funktionieren, da die Server-Grundlage von einem ganz anderen Entwickler entwickelt wird.
Die Geschäfte können Sie in den Stammdaten verwalten, diese können Sie in unserer App sehr wohl aufrufen (linkes Menü in der unteren Leiste).

**Comment by MrJohnZoidberg** [comment]
Hallo, ist Ihre Frage beantwortet?

**Comment by MrJohnZoidberg** [comment]
Das war von meinem Bruder nicht so streng gemeint. – Sie können definitiv hier auch weiter auf Deutsch schreiben, wenn Sie kein Englisch können. :-)

Grüßle
