### ISSUE TITLE
Add Recipes feature

### ISSUE THREAD

**Issue by KrautJasp** [patzly/grocy-android#148]
It would be really nice to be able to access it via the app.

**Comment by simonsan** [comment]
Yes, that would be awesome. I use recipes even to model basic things like the combination of things I use to make a washing machine. So that would be really cool to do that from the phone/tablet as well.

**Comment by MrJohnZoidberg** [comment]
We know that but it will require again a lot of work (like the initial features), so please be patient – we currently haven't much time because we both have a job now. :-)

**Comment by RaitaroH** [comment]
Just to add to this conversation, 
I think it would be really great if the recipe page would deal with embedded images and iframes to videos (eg. watching an youtube video of the recipe without having to leave the app).

**Comment by Dilski** [comment]
@MrJohnZoidberg would you like help implementing these features?

**Comment by MrJohnZoidberg** [comment]
@Dilski Yes, if my motivation is high enough one day I will work on it. Today I also received a mail from another developer who would like to do some work for it. :-)
