### ISSUE TITLE
Manage Chores & Reminder

### ISSUE THREAD

**Issue by simonsan** [patzly/grocy-android#149]
It would be absolutely beautiful to have an overview (and probably reminder) for our chores. I could for example imagine to use a tablet in the future for this and mount it on a wall that shows which tasks are still to do for the day that we could swipe through.

**Comment by MrJohnZoidberg** [comment]
Hey guys, quick update here: the chores page (where chores are displayed and can be tracked) is almost finished and will come with the next update. :-)
