### ISSUE TITLE
Error while loading the start page / stock overview

### ISSUE THREAD

**Issue by KrautJasp** [patzly/grocy-android#150]
Since yesterday I have a pretty big problem. I have started to fill my database with the products and I am already at over 200.
The problem, which appeared now is, that the start page, that means the stock, does not show me any products anymore... all that appears is an error message with the button: "Wiederholen" (I use the German version). What I don't understand is that I can use everything else, i.e. add and consume products and display the product groups and so on... so everything is synchronized with the server, only the app doesn't show me the stock and so I can't create shopping lists because of products below minimum stock...

Sometimes it also happens that the stock is displayed but the loading icon does not disappear. Or it is displayed that the stock is empty and the loading icon does not disappear. 

I thought it might be because there are too many products (over 200) but somehow I can't imagine that. Do you have an idea?

**Comment by patzly** [comment]
That sounds like multiple bugs...
We already know that we have to fix this too-many-products-bug, but we don't have much time right now :/
In case you need to consume or manage something you can always use the website of your server instance, too. We will look into this as soon as possible.

**Comment by donk7413** [comment]
It's probably the same issue like #151.

The timeout is too short and the stock can't load. 
I have more than 3000+ products, 200+stock items and 100+UQ conversions and since  #177 no issues.

You should test the 1.9 and tell us if the bug have been fixed.

**Comment by MrJohnZoidberg** [comment]
Yes, please try it with v1.9.0 as soon as it is released. Thanks!
