### ISSUE TITLE
TLS 1.3 support for Android <= 9

### ISSUE THREAD

**Issue by lruppert** [patzly/grocy-android#163]
Attempting to login to my server with a letsencrypt certificate fails with a message telling me that the certificate couldn't be validated and that I should get a letsencrypt certificate. The server is a brand new VM with a newly issued letsencrypt key and an nginx configuration only allowing strong ciphers and TLS 1.3. ssllabs.com has no issues with the certificate chain, nor do any browsers I've tried. Expanding support on the server to include TLS v1.2 causes the certificate to be accepted.

Steps to reproduce:

1. Configure a server to only support TLSv1.3
2. Attempt to connect and get lectured by the app because the new fangled thing makes it angry and scared
3. (debugging and self-doubt)
4. Configure the server to also support TLSv1.2
5. App happily connects

I skimmed the source code quickly to see if I could figure out how it's trying to validate the certificate but ran out of time. Maybe the connection library is pre-TLSv1.3?

**Comment by MrJohnZoidberg** [comment]
Hi, what Android version do you have?

**Comment by MrJohnZoidberg** [comment]
I've found [this](https://github.com/nextcloud/android/issues/3932) in the Nextcloud Android repository. So Android delivers the certificate stuff and if the Android version is too old and not supported anymore, certificate libs become outdated.
Nextcloud Android solved this issue with Conscrypt, maybe we can do this too. But this has not a high priority for me, I will look into this when I have enough time.

**Comment by lruppert** [comment]
Oh good catch! It turns out I'm only running 9. :( That explains the issue, and probably the reason I didn't think of it was my android browser probably packs its own libraries, hiding android 9's shame from me. On the bright side maybe this ticket will help others who are equally unlikely to have made the association between an error message about certificate validation and a protocol mismatch.

**Comment by Uatschitchun** [comment]
Thankfully I found this already open issue ;)
My wife's phone (sadly Android 7) isn't connecting anymore since I updated my deployment to reverse proxy with Traefik v2 and adapted the TLS options. 
Testing my server against https://www.ssllabs.com/ssltest/index.html it indicates to be using TLS 1.2 & 1.3
```
Protocols
TLS 1.3	Yes
TLS 1.2	Yes
```
It even indicates that Android 7 should be supported:
`Android 7.0	RSA 4096 (SHA256)  	TLS 1.2 > h2  	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   ECDH secp384r1  FS`
I checked the nextcloud app against my server instance and it's working nicely.
The server's log tells, the TLS handshake is failing and trying to fall back to TLS v1 which isn't (and won't be) enabled:
```
"http: TLS handshake error from IP: tls: no cipher suite supported by both client and server"
"http: TLS handshake error from IP tls: client offered only unsupported versions: [302 301]"
"http: TLS handshake error from IP: tls: client offered only unsupported versions: [301]"
```

What to do?

**Comment by MrJohnZoidberg** [comment]
The next alpha version (v2.0.0-alpha07) will include Conscrypt, which solves this issue here. :tada:

@Uatschitchun I hope this works then for your wife's phone too. You can give feedback here after the new version is released. :)

**Comment by Uatschitchun** [comment]
Wow nice, cool 😎
I'll test as soon as alpha 7 is out and report back!

**Comment by Uatschitchun** [comment]
So, as v7a is out, I re-checked my wife's phone and still get an **SSLHandshakeException** when trying to connect ;(
My server's access.log still shows:
```
time="2021-05-15T09:44:43+02:00" level=debug msg="http: TLS handshake error from 192.168.5.32:37541: tls: no cipher suite supported by both client and server"
time="2021-05-15T09:44:43+02:00" level=debug msg="http: TLS handshake error from 192.168.5.32:37542: tls: client offered only unsupported versions: [302 301]"
time="2021-05-15T09:44:43+02:00" level=debug msg="http: TLS handshake error from 192.168.5.32:37543: tls: client offered only unsupported versions: [301]"
```
The nextcloud app, also using conscrypt, is working nicely!

**Comment by MrJohnZoidberg** [comment]
Sorry, I didn't test my implementation of Conscrypt when I wrote it... I just saw that there was a mistake in my code which didn't apply the new security provider and on another location I had to tell Volley to allow TLS1.3 somehow (I don't understand why).

But now I've tested it with my server (only TLS1.3 protocol in nginx) and all Android versions from 5.0 to 9.0 are working with it. So I hope this isn't an issue anymore yet.

**Comment by Uatschitchun** [comment]
Nice! Again, I'll test and report back

**Comment by Uatschitchun** [comment]
Huge thx! beta is working ;)

**Comment by MrJohnZoidberg** [comment]
Great!
