### ISSUE TITLE
Select topmost input field by default

### ISSUE THREAD

**Issue by cslux** [patzly/grocy-android#175]
Thank you guys very much for this app, great work. I have question and an enhancement request.

1. [Question] Is it possible to set the default view to the shoppinglist?
    Basically, when I open the app I always click on the lower left button and select to shopping list.

2. [Enhancement] It would save us a view clicks if the first input field get selected by default and the keyboard gets opened.

Thanks!

**Comment by MrJohnZoidberg** [comment]
Hi, thanks for this enhancement request! I have split it up into two issues and I will work on it as soon as I have enough time. Maybe it will come with v2.0.0 . :-)

**Comment by MrJohnZoidberg** [comment]
I think with the next version there are all topmost fields selected by default. If you still find something which would be helpful if autoselected you can reopen this issue or create a new one.
