### ISSUE TITLE
Implement new barcode system

### ISSUE THREAD

**Issue by MrJohnZoidberg** [patzly/grocy-android#182]

**Comment by radim-ek** [comment]
I don't know what precisely means "new barcode system", but it can be a better UI for scanning QR codes? Now is optimized for wide and low (RECTANGLE) EANs, so I need to move away from QR if I scan this SQUARE.

**Comment by MrJohnZoidberg** [comment]
Oh sorry, I didn't receive a notification for your comment...
With new barcode system I mean the internal changes in grocy server 3.0.0 . Barcodes are now separate objects and not saved in product details anymore, only linked.
I will open a new issue for QR code layout.
