### ISSUE TITLE
Translation issue with plural forms

### ISSUE THREAD

**Issue by Porrumentzio** [patzly/grocy-android#183]
In some languages, for example Basque, the grammatical number of units is marked by the number itself but the unit gets unaltered:

**One** _bottle_ of wine = _botila_ **bat** ardo
**Three** _bottlles_ of wine = **hiru** _botila_ ardo

So, basically the unit gets unaltered. Consequently, there should **not** be an option for plural name of unit.

Is it possible to modify this some way?
Maybe getting off the plural name option from certain locales?

__
For now, I'll enter a message saying that the plural option is not necessary in Basque, into the button itself.

**Comment by MrJohnZoidberg** [comment]
Mmh, I hope I understand you right: You mean the master quantity unit form in our app and in that you would like to have an option to disable the plural field in your language. Is writing the same words like in singular into the plural field not an option?

**Comment by Porrumentzio** [comment]
Yes, I mean disabling the plural field in certain languages. No, the plural is marked with a final -k on words, but when there are numbers, they are which mark the grammatical number.

In our language there are three grammatical numbers: singular, plural and undefined.
When there's some word that marks the grammatical number ("some", "various", numbers...), the main word remains undefined.

So, when using numbers (words that do mark the grammatical number by themselves), the main word will always remain undefined: it's illogical to mark the grammatical number more than once.

So yes, summing up, the plural option is not needed in some languages (due to the kind of phrase it will be)

**Comment by MrJohnZoidberg** [comment]
Ok thanks, now I get it.
I will make an option for that in the app settings. Hopefully it will come with v2.0.0 of our app. :-)

**Comment by MrJohnZoidberg** [comment]
Tracked in #348.

**Comment by MrJohnZoidberg** [comment]
I just saw that the server displays the plural field in every language, so you just have to let it empty and then no plural is used.
I hope this issue is done now, don't hesitate to write here if something is not clear.
