### ISSUE TITLE
Ferature Request: Offline mode with sync for shopping list

### ISSUE THREAD

**Issue by LeoSum8** [patzly/grocy-android#19]
Mobile coverage in most supermarkets I know is terrible. Therefore the app is currently unusable for shopping under these circumstances. It would be great if a cached version of the shopping list could be kept in the app to be synced at a later time.

Thank you for this app! I found it on F-Droid and discovered grocy through it. This whole ecosystem looks very promising and you guys seem to be developing at a rapid pace.

After setting up grocy for the best part of the day I was a little disappointed when I took the app shopping today. Luckily I had a hand-written backup of my list :)

**Comment by MrJohnZoidberg** [comment]
Hey, offline support in the shopping list is on our roadmap! But you have to be patient, this needs more work than other features, because for this we need to implement a database.

**Comment by MrJohnZoidberg** [comment]
Surprise! Last night I've implemented this feature in our app. :tada: 
An update will be published in a few days.

Stay tuned!

**Comment by LeoSum8** [comment]
whoa, you really tried my patience there! ;)

**Comment by MrJohnZoidberg** [comment]
Version 1.4.0 of our app is out now, we hope you like it :)
Whenever the shopping list is loaded via the Internet, the offline data is updated (database overwritten) as well.
Sorry for the long wait, we had to change a lot of stuff under the hood.
You can open new issues if you have questions or ideas for enhancement regarding the offline mode.
