### ISSUE TITLE
Feature Request: Option to use default font

### ISSUE THREAD

**Issue by IronPiston** [patzly/grocy-android#194]
I'd like the option to switch from the default font to one like Roboto or Google Sans that I use across my phone. I realize the default font is monospaced, but I don't think it would impact the formatting negatively.

**Comment by MrJohnZoidberg** [comment]
It's harder than I thought because we've hardcoded the monospaced Roboto in a lot of places...

**Comment by MrJohnZoidberg** [comment]
In the current alpha preview version we've changed the main font to Roboto and only have titles in Roboto Mono. I hope this is ok for you – it is very difficult to implement proper support for any font or dynamic font changing...
