### ISSUE TITLE
Confirm adding the same item twice

### ISSUE THREAD

**Issue by basxto** [patzly/grocy-android#195]
Confirm if the user really wants to add (/consume/open) the same item twice … or just did not move the camera away fast enough.
Especially for add it does not make much sense to scan it twice since you can specify the amount.

**Comment by MrJohnZoidberg** [comment]
Do you mean in purchase batch mode? There you cannot specify an amount...

**Comment by basxto** [comment]
I misunderstood the UI, the number on it’s top showed how many new products must be added to the db, not how many products will be bought.

**Comment by MrJohnZoidberg** [comment]
Oh, sorry that we don't provide any docs for that... :-)

**Comment by MrJohnZoidberg** [comment]
In the current alpha preview version, there is no "batch mode" anymore (IMHO it was too buggy and bad code), instead the forms on purchase/consume page behave like the web interface. I hope you like it.
