### ISSUE TITLE
Product view loses data on rotation

### ISSUE THREAD

**Issue by Gigadoc2** [patzly/grocy-android#214]
**App version:** 1.9.0

When you trigger a screen rotation while in the "Product" screen (tested by adding a new product), any data entered so far is gone: [screencap.mp4](https://cables.five-ey.es/aeqC2zv8PnLbQJ0bRSLL/screencap.mp4)

On rotating back (not seen in the screencapture), the app crashes. I have a logcat of the crash, there are no error logs produced on the first rotation: [logcat](https://cables.five-ey.es/aeqC2zv8PnLbQJ0bRSLL/logcat.txt)

If I should provide any more info, please let me know :)

**Comment by MrJohnZoidberg** [comment]
The crash after second rotation is fixed now for`v1.9.1`, but not the data disappearance.
I will fix the latter one in `v2.0.0` because in that version there are internal code changes which make it much easier to maintain data on device rotation. :-)
