### ISSUE TITLE
Is it possible to use an IP address instead of an URL

### ISSUE THREAD

**Issue by Porrumentzio** [patzly/grocy-android#216]
Sometimes, setting up a ARM minicomputer with a static IP on intranet is possible and it's not as difficult as to have a static IP and domain.
Therefore, is it possible to enter the IP addres and port instead of the URL, when setting up the Android app?

**Comment by MrJohnZoidberg** [comment]
Yes, of course this is possible. Have you tried it already?

**Comment by Porrumentzio** [comment]
No, I wanted to know that to organize my plan to set up a Grocy instance :) Thanks
