### ISSUE TITLE
Option to set default scan mode

### ISSUE THREAD

**Issue by matthiakl** [patzly/grocy-android#217]
The scan mode currently always start in use mode. It would be nice to have one of the following:
* have an option to set the default mode 
* store the last used mode and use it, when reopening the scanner

**Comment by MrJohnZoidberg** [comment]
The scan mode in our next release v2.0.0 will be completely different. It will behave just like on the web interface and can be enabled in the Purchase/Consume forms. I hope you are not sad about this...
The old scan mode code was really ugly and hard to develop. Now the Purchase/Consume forms will also support external barcode scanners. :-)
