### ISSUE TITLE
Replace 'Server URL' string with 'Server address'

### ISSUE THREAD

**Issue by Porrumentzio** [patzly/grocy-android#218]
Having known with #216 that it's possible to enter server address with IP address and not only with URL, I think it's more clear to change the mentioned string that way.

**Comment by MrJohnZoidberg** [comment]
The Wikipedia article for [URL](https://en.wikipedia.org/wiki/URL) says:
> A Uniform Resource Locator (URL), **colloquially termed a web address**, is a reference to a web resource [...]

So I think "URL" is the word which is technically better.With "URL" we also wanted to emphasise that the entered text need `http://` or `https://` in the beginning.

Did my answer changed your mind or do you still want to have the change? :-)

**Comment by radim-ek** [comment]
I agree with @MrJohnZoidberg 👍 
URL can be literally everything with knowing this definition  "service://user:pass@**host**:port/pathToResource"  where **host** can be specified by IP or FQDN

**Comment by Porrumentzio** [comment]
It's well, thanks!
