### ISSUE TITLE
Purchase/Consume- If item name ending with space "theITEM ", you can't use it.

### ISSUE THREAD

**Issue by radim-ek** [patzly/grocy-android#219]
If you chose an item in the list "Purchase/consume" and the item has space "theITEM " at the end of the name, you get "Create new product..." with the name "theITEM"?

**Comment by MrJohnZoidberg** [comment]
Ah, that's because we trim the input (remove trailing spaces) before we check it...

**Comment by MrJohnZoidberg** [comment]
I can reproduce that issue with products which have a space in the beginning, like ` sugar`. But what did you mean with 
> the item has space "theITEM " at the end of the name

I don't understand this part. Can you give an example product name?

**Comment by radim-ek** [comment]
` Cibule `  Or  `Vejce `  ... every string where last char is space. In ASCII ( \x20 ). It's not standard to have space at the end string. But I have a few of them there. And can be everywhere in other instances. I can repair these strings in my instance  by remove space at the end, but still is a bug. If you have a name with space at the end of the string, you need to respect this.
