### ISSUE TITLE
Extended product editing

### ISSUE THREAD

**Issue by Sanaki** [patzly/grocy-android#220]
When adding new products, a few fields are missing, such as default store. Presumably these are hidden behind the "Show Extended Form" button at the bottom, but pressing it has no effect.

Version: 1.9.0, F-Droid
Grocy version: 2.7.1

**Comment by gismo2006** [comment]
Hello,

same here. I didn't know but I think maybe, it wouldn't work because we only use a hhtp Connection. (missing certifikat).

greets gismo

**Comment by Sanaki** [comment]
Hmm... getting a cert installed on the NAS I'm running it on could be a pain, but maybe I'll give that a spin.

**Comment by MrJohnZoidberg** [comment]
Hello guys, the extended product form is not implemented yet. But we added the button for it a long time ago and didn't remove it, sorry.
In `v2.0.0` there will be a new product edit form with subcategories, so that it's more clearly than the web interface form.
