### ISSUE TITLE
Option to "Purchase all done items"

### ISSUE THREAD

**Issue by AllesMeins** [patzly/grocy-android#221]
I would realy like to see a "purchase all done items"-option - so basically the same as the "purchase all items" but only with the items that I've marked as done. I don't scan my products so my workflow is "go shopping and mark all items in shopping-mode". At home do a "purchase all items" to add them to my stock. Unfortunately the app also offers me the items I didn't bought, so if I'm to quick a accidentally remove items from my list that I still need to buy.

**Comment by MrJohnZoidberg** [comment]
That's a good suggestion and it's easy to implement it until `v1.9.1`. Thanks!

**Comment by AllesMeins** [comment]
Happy to hear that... While you're on it - maybe an option to "Clear done items" would be usefull too? So one could clean the shopping list without removing items not yet bought.

**Comment by MrJohnZoidberg** [comment]
Sorry I'm currently working hard for `2.0.0` in my free time (which is not really much) and I don't want to make big changes to `v1.9` anymore (only bug fixes and other required changes)... So I hope that you are not angry if I change the milestone of this issue to `v2.0.0`.  :-)

**Comment by MrJohnZoidberg** [comment]
> maybe an option to "Clear done items" would be usefull too?

This option is already available: click "Clear shopping list" and you will be asked if you want to clear all or only done items. :-)
