### ISSUE TITLE
Option to select default start screen

### ISSUE THREAD

**Issue by AllesMeins** [patzly/grocy-android#222]
Just a minor improvement. It would be great to be able to select the screen with which the app should start. I do most of my stock-management from my PC and use the app mainly while out shopping. So it would be great if I could make the app start with the shopping-list instead the stock-screen.

**Comment by MrJohnZoidberg** [comment]
I've already created an issue for that: #176 
Launcher Shortcuts are already implemented, so you can use them to start different screens from your launcher. Shopping List is one of the possible shortcuts.

An option to select any start screen is not so easy to implement I think...
