### ISSUE TITLE
Impossible to delete product from "Bulk purchase scan" and blocking all other purchase

### ISSUE THREAD

**Issue by radim-ek** [patzly/grocy-android#225]
When I buy a product in Bulk scan. I can't delete it from queue. That's not problem, because if you leave bulk scan product vanished. But other products in queue can't be transferred to Grocy instance. Invalid "New product" blocking queue and there is no possibility to delete it or skip over.
![Screenshot_20201107-183502_Grocy](https://user-images.githubusercontent.com/6909034/98449827-84364880-2137-11eb-8c60-08e0f654a3ed.jpg)

**Comment by MrJohnZoidberg** [comment]
Hi, maybe I didn't understand well what you mean... Did you click the Floating Action Button in the bottom right corner? After this, `Hermelin` and `Eidam blok` would be purchased and gone from the list.

I don't understand what you mean with "invalid" and "blocking queue", could you explain this a bit better please?

**Comment by MrJohnZoidberg** [comment]
The red cross means that the product isn't created on the server in this moment. The green tick means that the product exists on the server and the purchases can be executed with the Floating Action Button.

After you've pressed this button, all stored transactions of products with a green tick are executed. Stored transactions of products which have a red cross are skipped.

**Comment by radim-ek** [comment]
> After this, `Hermelin` and `Eidam blok` would be purchased and gone from the list.

But this not happend :( Floating Action Button in the bottom right corner click work (initiate action) ONLY when the product on top queue is green.And when top product is red (not on server), this button not work and not invoke action.

**Comment by MrJohnZoidberg** [comment]
Ah ok, now I understand what you mean. :-) I will try to reproduce it. Thanks!

**Comment by radim-ek** [comment]
I try to reproduce it oe more time and one bug is there:
1) Scan some not knowing product
2) Some of them get full info to get green tick in product.
3) One of them but dont fill with all data.
4) ... you cant do Purchase with FAB with others after red product.
There is screenshots (FAB number change from 3 to 1, but on server is not made a 3. product. Only first one.)
![1 - Scan 3 new product](https://user-images.githubusercontent.com/6909034/98451809-97521400-2149-11eb-93e4-fefcbad9345d.jpg)
![2 - 2 of them fill with info to get Green](https://user-images.githubusercontent.com/6909034/98451810-98834100-2149-11eb-94f8-c8c70481da4a.jpg)
![3 - FAB action  and first one only created on instance](https://user-images.githubusercontent.com/6909034/98451812-98834100-2149-11eb-8359-8c89899f1599.jpg)

**Comment by MrJohnZoidberg** [comment]
I've found the code lines where this bug occurs and I will fix it until `v1.9.1` release.
