### ISSUE TITLE
Different behavior than in server: Location filter in stock view

### ISSUE THREAD

**Issue by MrJohnZoidberg** [patzly/grocy-android#248]
The filter filters with the default location, but not with the real location. I think I have to open an issue in the server repo because I don't know how to get the information in the stock request (or a single other request).

**Comment by patzly** [comment]
From an user email:
> Grocy website displays the filtering as I intended - i.e. the actual inventory at the respective location. In the Android app, it is currently not possible to determine WHERE the goods are actually located - if they are not at the standard location. Even more difficult, of course, when 2 pieces are in the basement and 3 are in the holiday home: The app reports 5 pieces at the standard location, my fridge (stupid example)

**Comment by samnewman86** [comment]
Sorry didn't see this issue as it was quite old.
I noticed that even in the server filtering by the location shows the grand total, not the total in that location. Do you guys experience this too?

**Comment by MrJohnZoidberg** [comment]
@samnewman86 Yes, I can reproduce this behavior on the server. Maybe it's intended? (But I don't know) If you think this is a bug, you can create an issue in the grocy repo.
