### ISSUE TITLE
Using hass ingress for application login

### ISSUE THREAD

**Issue by lukas947** [patzly/grocy-android#249]
Hi,

I do not feel comfortable with exposing grocy on a custom port using hass.io add-on. Would it be possible to login to the app via ingress address instead please? 

Tested Server URLs:
`http://ip.add.re.ss:port - Works as described`

```
http://ip.add.re.ss:hassPort/api/hassio_ingress/longrandomstring - goes to help about exposing the port
https://longgeneratedrandomstring.ui.nabu.casa/api/hassio_ingress/differentlongrandomstring/ - goes to help about exposing the port
```

It seems like the help page is hard coded, if certain criteria is not met. If I can reach the grocy API via ingress, why not the app?

Thanks!

**Comment by MrJohnZoidberg** [comment]
Hello,

> It seems like the help page is hard coded, if certain criteria is not met.

Yes, this is intended behavior. I've written in the code to open the help if there is `hassio_ingree` in the URL.

> If I can reach the grocy API via ingress, why not the app?

Why? Because in my tests a few months ago I couldn't reach the grocy API via the Home Assistant ingress page. I think the website behind the ingress URL just is the Home Assistant page which shows the grocy application in an embedded frame. So in my view this is intended by the Home Assistant developers because in this way the ingress apps are protected from the public throught Home Assistant authentication.

My thoughts are confirmed with this [blogpost](https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/):
> Ingress allows Hass.io add-ons to seamlessly integrate their user interface with Home Assistant. Home Assistant will take care of the authentication and the secure connection [...]

So the only way to get access from outside Home Assistant is to open the ingress grocy addon like described in the help section in our FAQ.

> Would it be possible to login to the app via ingress address instead please?

I'm sorry, this is not possible (or at least I don't know a way to achive it). I think there is no need to feel uncomfortable with exposing your grocy app if you set a strong password and maybe change the username (so that admin is no valid username, because bad guys often try this username).

Did I answer all your questions?

**Comment by lukas947** [comment]
Yes, you did. Thank you 👍 

I understand your standpoint, but still believe ingress can be used for API as well as internal add-on communication. Let's close the issue for the time being. Maybe in the future this will be possible. 

Thanks again!

**Comment by MrJohnZoidberg** [comment]
> I understand your standpoint, but still believe ingress can be used for API as well as internal add-on communication

If you still believe in that, can you give me any links or docs from Home Assistant which prove what you believe? :-)
You should understand the technical fact that ingress add-ons cannot be accessed from outside without proper port opening. That's because the Home Assistant authentication system is like a wall around Home Assistant *and* the ingress add-ons, which is intended by the HA developers.

If you still believe that it is possible to access grocy API from outside using ingress link, even with the fact above, then I cannot help you anymore. :-)

**Comment by lukas947** [comment]
HI @MrJohnZoidberg,

this is my last post, if you still say no, I will respect that as your choice. :)

I successfully polled the API via ingress (locally or via Nabu Casa) under these conditions:
* there must be a valid token for HA in the request
* there must be a valid cookie for ingress_session
* there must be a valid cookie for grocy_session
* there must be a valid add-on proxy address

Simulated in Postman, cookies and token were intercepted from the browser after logging in to both HA and Grocy. Then the API endpoint is on the end of the address, like it would normally be.
![image](https://user-images.githubusercontent.com/13629192/100714231-c446bf00-33b5-11eb-8c9d-e409ac959acb.png)

It's hard to say how to properly obtain the grocy add-on proxy address, because I have not found any good documentation of ingress, apart from the (fairly old) blog post you mentioned.

Now, I understand that adding alternative authentication flow for HA to the app might present certain architectural challenges. I'm not an Android dev, or any for that sense, so I cannot help you with implementation of this issue.

**Comment by MrJohnZoidberg** [comment]
Hi @lukas947,

I thought about this topic again, because there was a new issue with it – and now I think we should implement this authentication option in our app, because it is really easy to install Home Assistant OS on a Raspberry Pi for example, compared to setting up a whole server with Linux. And the Nabu Casa cloud feature makes it even more great for households without a static IP (as far as I understand). So to allow people who use such a setup to use our app, I will try to implement the auth behavior.

What I learned yet:

- The app needs the grocy add-on proxy id (like you already wrote). This can be found in the URL when navigating to the REST-API page of grocy.
- The app needs a Home Assistant auth token. The easiest way to get this, is to create a long-term token on the profile page which is valid for 10 years.
- The app has to request a ingress session key on start:
```
curl 'http://123.123.123.123:8123/api/hassio/ingress/session' -H 'authorization: Bearer <long-term token>' --data-raw ''
```
- Every minute, the app needs to validate the ingress session key (I think only when the app is in foreground):
```
curl 'http://123.123.123.123:8123/api/hassio/ingress/validate_session' -H 'authorization: Bearer <long-term token>' --data-raw '{"session":"<current ingress session key>"}'
```
- The requests look like that:
```
curl 'http://123.123.123.123:8123/api/hassio_ingress/<proxyId>/api/system/info' -H 'GROCY-API-KEY: <grocy api key>' -H 'Cookie: ingress_session=<current ingress session key>'
```

I don't know when this feature will be fully implemented, because I have to experiment how the app can load the session key on start without displaying a page already. And I need to extend the login workflow for that.

**Comment by RubenKelevra** [comment]
@MrJohnZoidberg hey thanks for giving this a shot!
In my case there's no way to get an open port from my ISP - they only got IPv4 and carrier grade NAT.

Using Home Assistant Cloud is the much easier option, since you can share the URL while not giving away any other URL to an Add-On.

Additionally the installation is maintained and updated automatically even when running on your own Raspberry Pi at home and you can get a valid HTTPS certificate for 5 Euros without having any proxy who stores it - its stored on the Raspberry Pi at home and the traffic is pipes to it encrypted.

It's the easiest solution to install Grocy IMHO if you have Home Assistant anyway.

**Comment by MrJohnZoidberg** [comment]
I've implemented the login flow for Home Assistant :tada:
I hope you like it, it will come with the next alpha version.

**Comment by lukas947** [comment]
Thank you for giving it a chance! It's much appreciated hopefully not just by me, but also all the other security nerds :)

**Comment by KTibow** [comment]
I'm getting 405 errors. What's causing that?

**Comment by KTibow** [comment]
Oops, was using my local instance, now getting 503s.

**Comment by MrJohnZoidberg** [comment]
@KTibow Are you using Nabu Casa?

**Comment by MrJohnZoidberg** [comment]
@RubenKelevra Did you test the current alpha already with Nabu Casa? I don't have the subscription yet.

**Comment by RubenKelevra** [comment]
> @RubenKelevra Did you test the current alpha already with Nabu Casa? I don't have the subscription yet.

Just found the alpha from 3 days ago... can you please just upload it under releases? Would make it easier to keep track of that! :)

Here's the result:

![Screenshot_20210220-141228.jpg](https://user-images.githubusercontent.com/614929/108596518-d9fccc80-7385-11eb-9711-637f6f260838.jpg)

**Comment by MrJohnZoidberg** [comment]
@RubenKelevra Thanks, did you log in with the form which contains four fields or with the form which contains only two fields? Because you may forgot to click on the card which says "Click here if you use the grocy Home Assistant add-on".

**Comment by schildgenb** [comment]
I can say I have tried this with the nabu casa url and it does not work. Mine just timeouts when trying to connect. It does work on the local url and the Hass ingress.

**Comment by KTibow** [comment]
I'm using my HA instance at `https://xxx.duckdns.org:443`.

**Comment by RubenKelevra** [comment]
> @RubenKelevra Thanks, did you log in with the form which contains four fields or with the form which contains only two fields? Because you may forgot to click on the card which says "Click here if you use the grocy Home Assistant add-on".
> 
> Besides that, does the login work with your local url of the Home Assistant server (not the Nabu Casa one)?
> 
> And yes, we can think about publishing the alpha versions via releases – but the problem is that we don't know how F-Droid behaves if we tag sth as alpha release.

Oh damn, yeah gonna try it again then :)

**Comment by MrJohnZoidberg** [comment]
@KTibow
> Nevermind, I figured out how to get the identifier. Maybe you should make that auto-gettable?

Just scan the QR code of an API key on your grocy server interface... :-)
If you tap on "Enter data manually" below the QR code scanner,  the API key field and the ingress proxy identifier field won't be filled automatically AND you have to click on the card on the top.

**Comment by KTibow** [comment]
Wait, really? I’ll have to try that using Ingress.

**Comment by MrJohnZoidberg** [comment]
To the people who use Nabu Casa here:

A fix for the login comes with the next alpha version, currently you need to add `:443` to the Home Assistant server url.

**Comment by RubenKelevra** [comment]
@MrJohnZoidberg 

> Just scan the QR code of an API key on your grocy server interface... :-)

> A fix for the login comes with the next alpha version, currently you need to add `:443` to the Home Assistant server url.
> Besides that, the login with Nabu Casa is working fine for me.

Hey!

I just got time to test it again. So with the 2.0.0-alpha3:

I've scanned the API key, which filled in the "ingress proxy identifier" as well as the "Valid API key" automatically.

I then entered my `https://1234567.ui.nabu.casa:443` "Server URL" and created a "Long-lived access token" in my Home Assistant user settings.

But it still won't work for me:

![Screenshot_20210223-131449](https://user-images.githubusercontent.com/614929/108842676-ea0cea00-75d9-11eb-9896-d9b77a187ad8.jpg)

**Comment by RubenKelevra** [comment]
The same is happening for `2.0.0-alpha4`, but for it I don't need the port 443 at the end of the URL.

When I paste the full URL to the Grocy instance, which looks like `https://1234567.ui.nabu.casa/hassio/ingress/23242_grocy` into the "Server URL" I just get this error:

`Not a valid grocy instance`

**Comment by RubenKelevra** [comment]
Do we need the full URL to the grocy instance in the first field, or just the Domain-Name?

The Ingress proxy identifier is a long base36(?) string, is this correct? I expected that this would look like "23242_grocy" or something like that.

**Comment by MrJohnZoidberg** [comment]
Mmh I don't know why your nabu casa connection doesn't work but mine does work...

> Do we need the full URL to the grocy instance in the first field, or just the Domain-Name?

Like the section header ("Home Assistant") indicates: You need only the Home Assistant server URL or Nabu Casa URL.

> The Ingress proxy identifier is a long base36(?) string, is this correct? I expected that this would look like "23242_grocy" or something like that.

The first one is correct, the QR code contains the ingress URL to the grocy instance and Grocy Android reads the identifier from the URL. So all should work, but I don't know why yours isn't working...

The "API key not working" message is displayed if there was an AuthFailureError. So there can also be a problem with Home Assistant authentication (with the long-lived token). But I'm not sure what it can be.

When using Home Assistant there should be a different message which says that the API isn't working or sth other (maybe the long-lived token).For now I've added the exact (internal) message to the error screen (shown if there was an AuthFailureError). You can see the change in the next alpha version.

**Comment by MrJohnZoidberg** [comment]
Does anyone else here use Nabu Casa? @lukas947 ? I would like to know if my implementation works generally or not. (Like I wrote, for me it does work)

**Comment by schildgenb** [comment]
After putting 443 after the url it has been working for me and have not had
any issues.

Thanks,

Brad Schildgen

**Comment by polm99** [comment]
> Does anyone else here use Nabu Casa? @lukas947 ? I would like to know if my implementation works generally or not. (Like I wrote, for me it does work)

Alpha4 - Can't get it working, "API key not working", with Nabu Casa or direct domain name entry, with adding port number and w/o, with manual data entry or using QR code. Tryed with mobile network, home wifi, with Adblock disabled.

**Comment by RubenKelevra** [comment]
@MrJohnZoidberg is just the token enough to login or it using the Grocy username or something like that? 🤔

**Comment by RubenKelevra** [comment]
I cleared the App-Data and tried again today. It's now working for me.

Maybe the update to the alpha3 and then alpha4 from the stable version caused this? 🤔

I mean I never used the App, but I tried several times to login before. So maybe something is set on the first try and never overwritten?

**Comment by polm99** [comment]
I've fresh installed alpha05 - message is "API key not working" and "b.a.b.a" in field below.

**Comment by timasplin** [comment]
I have just installed the alpha5 - and when trying to connect over local network to my grocy instances running in hassio it will not connect.

I created a long lived access token and used the QR scan to fill in connection details

But the app just gives me:
`
API key not working
b.a.b.a
`

Looking in my supervisor logs I get the following warning when I try to connect using the grocy app:
`WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None`

When visiting URL in the browser this is working - but this has access to the ingress session cookie which I can see is being sent when inspecting the network traffic.  

After clearing the app cache and exposing a port for grocy I was able to connect over the local network

**Comment by MrJohnZoidberg** [comment]
Thanks for all your reports, we don't have enough time to work on the app... In april my exams are over and then I can work on it again.

**Comment by pbanj** [comment]
> 
> 
> I've fresh installed alpha05 - message is "API key not working" and "b.a.b.a" in field below.

i got this issue also. i decided to click the get key button and i think i know why it isnt working for people. that button opened the browser and pointed it towards https://url:8123 which isnt a great idea to hard code as some like myself may have it set up not to need the port at the end/have changed the default port. so if that button is doing that i have a feeling the app itself is doing it too.

**Comment by MrJohnZoidberg** [comment]
@pbanj Yes, that's discussed in #413. But if you enter a URL together with a port (e.g. `http://192.168.1.234:50`) this port `50` and not `8123` will be taken in the current version. So it is not hardcoded, but I thought that it would be good if the default port of Home Assistant is chosen automatically if you don't enter a port at all (for people without much knowledge about ports). But that's discussed in the linked issue.

I think that the error "API key not working" also appears for some people even if they append the port to the URL, so that's still an unsolved problem. Maybe the ingress login implementation has a bug in our app.

**Comment by barrelltitor** [comment]
It seems I get the same issue as others above with the b.a.b.a error,  I'm using a nabucasa URL, but tried with local http://ip:port as well and the same thing. Can I provide any sort of logs or things like that to assist with fixing this?

**Comment by MrJohnZoidberg** [comment]
Hey guys, I would like to work on this issue but it seems that the grocy Add-on for Home Assistant isn't maintained right now: There are [unfixed bugs](https://github.com/hassio-addons/addon-grocy/issues) for weeks now and I cannot work with a broken system (these bugs also occur on my Raspberry Pi). I'm totally sorry for that. I think frenck (the maintainer) doesn't use grocy anymore, so it is unlikely that the Add-on will ever loose its experimental status.

And the Home Assistant Add-on ecosystem doesn't allow access to anything of the interior life of an Add-on, so I think there is no simple workaround which we can apply without the maintainer. The user can't even install a specific version of an Add-on or downgrade it – these all are reasons why I don't like it to work with Home Assistant Add-ons or an implementation in our app.

So I think it would be the best if we wait for a bug fix and in the meantime the finalized Grocy Android v2.0.0 can be released – with the current implementation of the Ingress login.

I hope you can agree with that.

**Comment by pbanj** [comment]
> And the Home Assistant Add-on ecosystem doesn't allow access to anything of the interior life of an Add-on, so I think there is no simple workaround which we can apply without the maintainer. The user can't even install a specific version of an Add-on or downgrade it – these all are reasons why I don't like it to work with Home Assistant Add-ons or an implementation in our app.

you can load a custom repository for addons, so someone could fork it and fix it, or fork it and use it to install an older version. 
![image](https://user-images.githubusercontent.com/17306233/133002940-0fb5b909-397a-412c-8d88-690985633cb9.png)


also poking around with docker will allow to get to where the addon is installed and then you can make changes. using something like portainer aids in this. 
this is an export of the image for the grocy add on 
![image](https://user-images.githubusercontent.com/17306233/133002967-f29c73f5-456e-4c05-90eb-60b7ea305f95.png)

**Comment by Xelinor** [comment]
So, it looks like Frenck finally updated Grocy and seems to be back at it. If willing (and time allowing), I have Nabu Casa and would be happy to help debug for problems with it.

As it stands at the moment, I have the version of Grocy installed from the Android app store, and I'm getting a 401 Unauthorized error in the app's log.

Log message is as follows;
01-02 19:14:55.343 29653 31566 E Volley  : [3936] BasicNetwork.performRequest: Unexpected response code 401 for https://[nabu-casa-uniqueifier].ui.nabu.casa/api/hassio_ingress/[ingress-uniqifier]/api/system/info

So, I went ahead and put the same URL in my chrome browser and it works without problem. I get the following response:

`{"grocy_version":{"Version":"3.1.3","ReleaseDate":"2021-11-14"},"php_version":"8.0.14","sqlite_version":"3.36.0","os":"Linux 5.10.83 #1 SMP PREEMPT Fri Dec 3 17:18:05 UTC 2021 aarch64","client":"Mozilla\/5.0 (Linux; Android 12; Pixel 6 Pro) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/96.0.4664.104 Mobile Safari\/537.36"}`

Is there an alpha/beta version I should be trying this with instead?

**Comment by MrJohnZoidberg** [comment]
The new version 2.1.1 of our app has improved connection handling for Home Assistant and a scanner for the long-lived token from Home Assistant. The connection error page has some new descriptions and hints for wrong (not working) token or API key.

My tests have shown that the grocy API QR code doesn't contain the server URL anymore (with the new add-on version), so you may have to fill it out manually even if you scanned QR codes. If you use Nabucasa (Home Assistant Cloud) you unfortunately need to type the server URL (which you use for accessing your server) including your long Nabucasa uuid like `https://<nabucasa-uuid>.ui.nabu.casa`. Maybe you can use your clipboard and paste the URL into the field, this could prevent typos.

Please react to this comment with a 👍 if your app is working with Home Assistant or if it doesn't work, react with a 👎 and please create a new issue in this repository together with the error description shown in the app.
Thanks!

**Comment by MrJohnZoidberg** [comment]
@Xelinor @pbanj @barrelltitor @polm99 @timasplin

Any reactions please? :)

**Comment by Xelinor** [comment]
> @Xelinor @pbanj @barrelltitor @polm99 @timasplin
> 
> Any reactions please? :)

Unfortunately I hit a breaking point with Grocy in my home assistant instance. I had to shut it down and haven't decided if I'm going to spin it back up, so I'm not sure if I'll be able to test that.

**Comment by pbanj** [comment]
> @Xelinor @pbanj @barrelltitor @polm99 @timasplin
> 
> Any reactions please? :)

i stopped using the addon and went to stand alone because of this issue, so i cant test it. sorry

**Comment by bakercj** [comment]
New user of the Grocy HA addon and attempting to use the app. Experiencing "API key not working" and "com.androud.volley.AuthFailureError". I have attempted scanning the QR code, utilizing the internal IP, and using the custom domain that points to my HA instance. 

@MrJohnZoidberg If you have any tips or troubleshooting to perform, I am happy to assist.

**Comment by MrJohnZoidberg** [comment]
@bakercj

Please look here for more details: #509

The current version of our app doesn't support the addon version 0.17.0, sorry.
Please wait for a few days until we release the next version.
