### ISSUE TITLE
Autoscan date

### ISSUE THREAD

**Issue by duylong** [patzly/grocy-android#25]
Hi,

I don't know if it's easy to automatically scan a date from a photo capture. In any case I add this idea because when we do a lot of shopping, it takes a long time to put all the dates.

Best regards,

**Comment by MrJohnZoidberg** [comment]
Hi,
We also know this problem :)
There are possible solutions from grocy side (maybe you don't want them):
- Enter the average best before days of the product in the product edit form

**Comment by MrJohnZoidberg** [comment]
Sorry, I've sent my comment too early :)

**Comment by duylong** [comment]
I often have prepared meals, meat or something else in the refrigerator that have a fixed date, it can take a long time to enter all the dates.
What I currently do, I scan and then put them in the fridge. Then in the evening, I come with the computer and I put the dates of the latest products directly from Grocy.

Hard to find a simple solution, but I understand the difficulty of the feature, it was just an idea;)

**Comment by patzly** [comment]
I tried it with the app from Play Store – It doesn't make mutch fun, the text recognition takes long and you have to manually tap on scan each time.
Thanks for the idea, but I think that the saved time isn't worth mentioning because it often needs more than one scan until it's correct.

**Comment by patzly** [comment]
I've made some Google searches: the only really good developed android-specific library is the Google Vision API which is included in Play Services...
All other solutions probably aren't good enough and not really developed for Android, like Tesseract for example. So there aren't many useful OCR libs out there for open-source apps, I think we should focus on the main functionalities of Grocy.
