### ISSUE TITLE
latest version breaks local access?

### ISSUE THREAD

**Issue by loph917** [patzly/grocy-android#252]
installing the 1.10 release from google play breaks access to a locally hosted instance of grocy. installed 1.9.0 from the apk here on github and all works well.

my installation of grocy is hosted on a bare metal ubuntu 20.04 with apache, no https. i am using a virtual host with internal DNS setup for a non-public zone. not accessing grocy from outside the local LAN here at home.

using the 1.10.0 version of the android app, i get to the logon page, enter my URL and API key and after hitting the login button it displays an error that it can't reach the server. from firefox on the same device, same URL and same API key, i can access the grocy installation with no issue.

apache logs display no access hits for the device IP when using the android app (1.10.0). back on 1.9.0, access logs roll as expected.

**Comment by MrJohnZoidberg** [comment]
Thanks for reporting that, I will test it in a few hours.

**Comment by MrJohnZoidberg** [comment]
Is it working again with `v1.10.1`?

**Comment by loph917** [comment]
yes it is. thank you for the quick fix.
