### ISSUE TITLE
Add Server address somewhere in infos

### ISSUE THREAD

**Issue by precchia** [patzly/grocy-android#253]
Maybe I missed something, but I haven't found anywhere the address of the server I'm connected to. Unless I 'log off' that is. I have a couple of servers (mostly for testing) and It would be useful to be able to know which one I'm supposed to be connected to, to determine which server 
to troubleshoot.

**Comment by MrJohnZoidberg** [comment]
In the upcoming `v2.0.0` there will be a new settings page where you can see that. It's already done but on another branch (proper_navigation), where I'm working on the whole new version.

I will closes this issue, so that I can see only issues which I have to work on.
