### ISSUE TITLE
Make due date and price optional in shopping basket

### ISSUE THREAD

**Issue by precchia** [patzly/grocy-android#254]
It seems grocy (the main app) has options to make due date and price optional in the shopping list.
Entering a due date for every product is extremely heavy in my opinion, so I disabled it on the server.
But it seems the client does not take these options into account, and insists on asking the due date.

**Comment by MrJohnZoidberg** [comment]
Sorry, I don't understand where you are seeing this on the `shopping list` page – maybe you mean the `purchase` page or the `batch purchase` page?
Because these details (due date and price) are only asked on purchase transactions.

**Comment by precchia** [comment]
Sorry if I wasn't clear.
I have the interface in French (takes the default language of Android?) so I can't tell you exactly which page it is...

But, If I:
- open the 'Shopping List' (Liste des courses) list
- Tap on an item (it will open a dialog on hte bottom-half of the screen)
- Tap on the 'Cart' Icon
It will open a full screen window allowing me to enter: Due Date, Quantity, Price, if the price is the total price, The shop I bought this in
I'm referring to the Due Date and Price fields there.

By the way, I assume this is the correct way to set a product as 'purchased'. Is it?

**Comment by MrJohnZoidberg** [comment]
Ah, thanks now I understand. I will look into it soon. :-)

> By the way, I assume this is the correct way to set a product as 'purchased'. Is it?

Yes, you can purchase items from shopping list like this, but apart from that you can also purchase products from stock overview and with the "purchase" page.

**Comment by MrJohnZoidberg** [comment]
The price field is optional already (I've checked this in the code, there is no error if it's empty).
And the due date field is automatically prefilled if you set a default due date in this product. So if you set the default due date to -1 (never expire), it will be prefilled with -1 on the purchase page and thus you don't need to fill it out. That's the same behavior like on the grocy server interface.

Do you agree with me?
