### ISSUE TITLE
Not a valid Grocy instance

### ISSUE THREAD

**Issue by knnnrd** [patzly/grocy-android#255]
I'm able to access the Grocy web interface through an Nginx reverse proxy. When I fill in the server url in the Grocy app and click "Create key", it correctly redirects me to the web interface. But then after filling in the key it says "Not a valid grocy instance". I can't find any log files on my device so I'm not really sure how to debug this further. 

Mind you that I am using the linuxserver.io docker image for running Grocy.

**Comment by MrJohnZoidberg** [comment]
The server makes an API request after you pressed "Login" to get the grocy server version:
`http(s)://your.grocy.server/api/system/info?GROCY-API-KEY=YourApiKey`

The error you mentioned ("Not a valid grocy instance") occurs
- if the response doesn't contain the string `grocy_version`
- or if the resonse status code is 404.

I think there is a problem with your reverse proxy. You can simply get the response with the `curl` commandline application:
`curl 'http(s)://your.grocy.server/api/system/info?GROCY-API-KEY=YourApiKey'`

For example for the demo server, the request command and its response is the following:
`curl 'https://en.demo.grocy.info/api/system/info?GROCY-API-KEY='`
`{"grocy_version":{"Version":"2.7.1","ReleaseDate":"2020-04-17"},"php_version":"7.4.12","sqlite_version":"3.27.2"}`

Can you try this with your server and api key and post the response here?

**Comment by knnnrd** [comment]
Ok I know where it's going wrong. My Grocy instance is protected by Authelia. So the response to the request is a 302 redirect to the authelia login page (https://www.authelia.com/).

curl: 
```
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

curl -L 'http://...': 
```
<!doctype html><html lang="en"><head><meta property="csp-nonce" content="cNAD0UL5tGG0gFEZfroc0w3fz7XK7NjU"/><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Authelia login portal for your apps"/><link rel="manifest" href="/authelia/manifest.json"/><link rel="icon" href="/authelia/favicon.ico"/><title>Login - Authelia</title><link href="/authelia/static/css/2.89e66999.chunk.css" rel="stylesheet"><link href="/authelia/static/css/main.7bb9a71f.chunk.css" rel="stylesheet"></head><body data-basepath="/authelia" data-rememberme="true" data-resetpassword="true"><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script src="/authelia/static/js/runtime-main.cc5273ce.js"></script><script src="/authelia/static/js/2.ed5c733c.chunk.js"></script><script src="/authelia/static/js/main.ce7f9aff.chunk.js"></script></body></html>
```

Any idea on how to fix this? Thanks!

**Comment by knnnrd** [comment]
I guess the solution is to not protect the /api path with authelia since it's protected with the API key generated by Grocy.

**Comment by MrJohnZoidberg** [comment]
Yes, I think that's the only solution.

**Comment by vctls** [comment]
Sorry for digging up this old issue, but I'm having the same issue and simply not protecting the `/api` route doesn't seem to be enough with an SSO configuration.  
I'm using `ReverseProxyAuthMiddleware`, and if I don't put the `/api` route behind my SSO (in my case, Authelia), then the requests don't get the `Remote-User` header and Grocy returns 500 errors.
I can put an arbitrary value for the header in the reverse-proxy configuration, but I'm not sure what consequences it will have.
I tried adding `proxy_set_header Remote-User anonymous;`, for example. Now both the web and mobile app work, but I see the user `anonymous` actually got created.
