### ISSUE TITLE
Problems when adding new item with Purchase barcode scanner?

### ISSUE THREAD

**Issue by ImjuzCY** [patzly/grocy-android#258]
I'm not sure if it's a bug or I'm using it wrong, but when I scan a barcode with the Purchase barcode scanner, if the item is new, I have to enter the purchase unit, stock unit and factor. After that, I upload  the newly created item, and the purchase entry will always only be 1 stock unit. 

For example, I bought a pack of pork belly with two pork bellies in a pack. I open the Purchase barcode scanner, scan the barcode, and I'm prompted to enter the name of the product. Afterwards, I have to go into the create new item page from the scanner (with the button on top of the screen), and enter the details about the product, including Quantity Unit Purchase, Quantity Unit Stock, and Factor purchase to stock. I entered Pack, Piece, and 2 in the respective fields, and press upload. After this, the quantity of stock I have recorded will be 1 piece although it should be 2 pieces because I bought 1 pack with 2 pieces.

**Comment by MrJohnZoidberg** [comment]
You're right, that's a bug – thanks for reporting it!
We hardcoded `1` as amount on that page in the purchase transaction details and I forgot to add the factor as multiplier.

I will fix it right now, but I don't know when we will release the next version. That's not a hotfix IMHO so we wait for more fixes or improvements until the next release.

**Comment by radim-ek** [comment]
Oh, yes! I forget report this bug :) 
Is as you wrote: "After create new product with Purchase barcode scanner, you got everytime only one stock not converted [QU buy -> QU stock]
