### ISSUE TITLE
Instead of purchase unit, stock unit is used

### ISSUE THREAD

**Issue by loziniak** [patzly/grocy-android#259]
When I enter **scanning** mode from main (stock) screen, then select **purchase**, and then add **new** product, Then it is added to the stock with **stock units**, instead of purchase units.

**Comment by radim-ek** [comment]
Duplicate of 258#

**Comment by MrJohnZoidberg** [comment]
Thanks @radim-ek, yes this will be fixed in the next version `v1.10.2`.
