### ISSUE TITLE
Refreshing the shopping list UI every 10 seconds results in skipping back to the top.

### ISSUE THREAD

**Issue by TheDevFreak** [patzly/grocy-android#26]
This makes the app very difficult to use in a store when you are looking down your list and it just skips back to the top.

**Comment by patzly** [comment]
Oups, we'll try to fix this.
Until a fix is available please set the auto-sync interval in settings to `0`, so you have to manually refresh if someone has marked an item as done on another device (or you don't have to sync at all if you're the only one who accesses the list in store).
