### ISSUE TITLE
Enable some settings by default when creating a new product

### ISSUE THREAD

**Issue by loziniak** [patzly/grocy-android#261]
Settings I mean:

* "Accumulate sub products min. stock amount"
* "Allow partial units in stock"

Is there a good reason, why it's not allowed by default? I have to go to web interface for a lot of new products. And it would not be a problem for me, if these settings were set on every product in my stock.

**Comment by MrJohnZoidberg** [comment]
In `v2.0.0` there will be all options in product create/edit mode which are on the server.

**Comment by loziniak** [comment]
Does it mean additional clicking, or some options will be checked by default?

**Comment by MrJohnZoidberg** [comment]
I think in `v2.0.0` you have to click like on the server, but in a later version we will implement a page where you can set all default values for new products (if this is technically possible, I didn't think about that yet).
