### ISSUE TITLE
No factor applied when scanning new product

### ISSUE THREAD

**Issue by todu85** [patzly/grocy-android#264]
When scanning a new product for shopping and the product is not defined yet, you get a popup to fill in the missing fields. When you now change the units: e.g. 1 package (shop) is 1000g (inventory), just 1g is added to inventory. I guess that the unit conversion is missing, because the fields are saved correctly.

**Comment by radim-ek** [comment]
Duplicate of #258

**Comment by MrJohnZoidberg** [comment]
Thanks for reporting! But like Radim wrote, this is a duplicate of an already fixed issue. We will release the new version with this fix in a few days.

**Comment by MrJohnZoidberg** [comment]
Sorry, we won't release another version before `v2.0.0`... I hope this is ok. The upcoming version will contain the fix.
