### ISSUE TITLE
Switch between multiple grocy instances

### ISSUE THREAD

**Issue by patzly** [patzly/grocy-android#272]
Request from an email:
> Is it possible to add support for multiple Grocy instances? I use several systems, primarily test and production, and would be very happy if this could be implemented in the future.

**Comment by dominiczedler** [comment]
Meanwhile we offer an automated nightly build with a different app icon, additionally a debug version which you can build by yourself and finally the production version from F-Droid or Google Play (or GitHub releases). These are three versions which you can install and use independently from each other. We hope this is sufficient for you.
