### ISSUE TITLE
Allow username:password in server URL

### ISSUE THREAD

**Issue by 0xD0M1M0** [patzly/grocy-android#273]
I want to keep grocy behind an Apache Server Password Authentication. This would require somehow a handover of the username and password in the URL, so I used a "https://user:password@url.de/public" style URL.

The logfile of the app throws me:
01-06 22:29:56.271  9691 15191 E Volley  : [43023] b.f: Unexpected response code 401 for https://user:password@url.de/public/api/system/info?GROCY-API-KEY=XYZ

A curl of the same string throws me:
{"grocy_version":{"Version":"3.0.1","ReleaseDate":"2021-01-05"},"php_version":"7.4.3","sqlite_version":"3.31.1"}

If I switch off authentication but keep the full URL incl. user and password, the app works as good it can work with 3.0.1 (thank you for updating and working hard on your version 2.x.x).

Aside that 3.0.1 is not supported right now, do you have any idea how to authenticate or can you add this feature in the url handling?

**Comment by MrJohnZoidberg** [comment]
Mmh, I don't have an idea why volley cannot access the server like this (the error is from volley, which the app uses for requests).
But I found a solution [here](https://stackoverrun.com/de/q/10475275) and [here](https://medium.com/@valericaplesu/android-why-does-volley-retry-on-401-and-403-53974c042d32) which I will implement in a later version. So maybe it will take some time for that, sorry. :-)

**Comment by 0xD0M1M0** [comment]
Thx. At least there is a possible solution out there. I don't know the code to well. I only found a connection in the "DownloadHelper.java". It seems that this solution [here](https://stackoverflow.com/a/26301863) with adding:

`params.put(
            "Authorization",
            String.format("Basic %s", Base64.encodeToString(
                    String.format("%s:%s", "username", "password").getBytes(), Base64.DEFAULT)));`

did the trick.

**Comment by MrJohnZoidberg** [comment]
Does your solution (with the Authorization header) only work if you then use the URL without `user:password@` or can you have the part in the URL together with the Auth header?

I'm asking because as a solution I would simply read the username & password from the URL (if they are given) and put them in the Auth header like you did. Then it wouldn't be necessary to add two optional fields to the form.

**Comment by 0xD0M1M0** [comment]
Frankly, I am not sure how my server handles it. Via the browser I use the address with https://user:password@domain.net and it works. So I guess if you read out as proposed the two fields and transfer them in the header it would be fine.

**Comment by MrJohnZoidberg** [comment]
I've implemented it now, can you please test it as soon as our next alpha version is released? Thanks!
If something still doesn't work, you can open a new issue or write it here.

**Comment by 0xD0M1M0** [comment]
The login works without problems. Thank you very much!

The logfile has some url exceptions. I don't know if they are there because of the username.password in the url.

--------- beginning of main
02-17 19:45:49.304 12320 12320 E SensorManager: unregisterListenerImpl callingApp: xyz.zedler.patrick.grocy,callingPid:12320,callingUid:10428
02-17 19:46:22.818 12320 14004 E Volley  : [11665] j.a: Unhandled exception java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:22.818 12320 14004 E Volley  : java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:22.818 12320 14004 E Volley  : 	at b.a.b.w.b.f(SourceFile:30)
02-17 19:46:22.818 12320 14004 E Volley  : 	at b.a.b.j.a(SourceFile:8)
02-17 19:46:22.818 12320 14004 E Volley  : 	at b.a.b.j.run(SourceFile:2)
02-17 19:46:22.818 12320 14004 E Volley  : Caused by: java.net.MalformedURLException: no protocol: null/api/hassio/ingress/session
02-17 19:46:22.818 12320 14004 E Volley  : 	at java.net.URL.<init>(URL.java:601)
02-17 19:46:22.818 12320 14004 E Volley  : 	at java.net.URL.<init>(URL.java:498)
02-17 19:46:22.818 12320 14004 E Volley  : 	at java.net.URL.<init>(URL.java:447)
02-17 19:46:22.818 12320 14004 E Volley  : 	at b.a.b.w.g.a(SourceFile:8)
02-17 19:46:22.818 12320 14004 E Volley  : 	at b.a.b.w.b.f(SourceFile:4)
02-17 19:46:22.818 12320 14004 E Volley  : 	... 2 more
02-17 19:46:22.850 12320 12320 E g4      : validateHassIngressSession: error: b.a.b.u: java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:23.397 12320 14008 E Volley  : [11669] j.a: Unhandled exception java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:23.397 12320 14008 E Volley  : java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:23.397 12320 14008 E Volley  : 	at b.a.b.w.b.f(SourceFile:30)
02-17 19:46:23.397 12320 14008 E Volley  : 	at b.a.b.j.a(SourceFile:8)
02-17 19:46:23.397 12320 14008 E Volley  : 	at b.a.b.j.run(SourceFile:2)
02-17 19:46:23.397 12320 14008 E Volley  : Caused by: java.net.MalformedURLException: no protocol: null/api/hassio/ingress/session
02-17 19:46:23.397 12320 14008 E Volley  : 	at java.net.URL.<init>(URL.java:601)
02-17 19:46:23.397 12320 14008 E Volley  : 	at java.net.URL.<init>(URL.java:498)
02-17 19:46:23.397 12320 14008 E Volley  : 	at java.net.URL.<init>(URL.java:447)
02-17 19:46:23.397 12320 14008 E Volley  : 	at b.a.b.w.g.a(SourceFile:8)
02-17 19:46:23.397 12320 14008 E Volley  : 	at b.a.b.w.b.f(SourceFile:4)
02-17 19:46:23.397 12320 14008 E Volley  : 	... 2 more
02-17 19:46:23.397 12320 14007 E Volley  : [11668] j.a: Unhandled exception java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:23.397 12320 14007 E Volley  : java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:23.397 12320 14007 E Volley  : 	at b.a.b.w.b.f(SourceFile:30)
02-17 19:46:23.397 12320 14007 E Volley  : 	at b.a.b.j.a(SourceFile:8)
02-17 19:46:23.397 12320 14007 E Volley  : 	at b.a.b.j.run(SourceFile:2)
02-17 19:46:23.397 12320 14007 E Volley  : Caused by: java.net.MalformedURLException: no protocol: null/api/hassio/ingress/session
02-17 19:46:23.397 12320 14007 E Volley  : 	at java.net.URL.<init>(URL.java:601)
02-17 19:46:23.397 12320 14007 E Volley  : 	at java.net.URL.<init>(URL.java:498)
02-17 19:46:23.397 12320 14007 E Volley  : 	at java.net.URL.<init>(URL.java:447)
02-17 19:46:23.397 12320 14007 E Volley  : 	at b.a.b.w.g.a(SourceFile:8)
02-17 19:46:23.397 12320 14007 E Volley  : 	at b.a.b.w.b.f(SourceFile:4)
02-17 19:46:23.397 12320 14007 E Volley  : 	... 2 more
02-17 19:46:23.398 12320 14006 E Volley  : [11667] j.a: Unhandled exception java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:23.398 12320 14006 E Volley  : java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:23.398 12320 14006 E Volley  : 	at b.a.b.w.b.f(SourceFile:30)
02-17 19:46:23.398 12320 14006 E Volley  : 	at b.a.b.j.a(SourceFile:8)
02-17 19:46:23.398 12320 14006 E Volley  : 	at b.a.b.j.run(SourceFile:2)
02-17 19:46:23.398 12320 14006 E Volley  : Caused by: java.net.MalformedURLException: no protocol: null/api/hassio/ingress/session
02-17 19:46:23.398 12320 14006 E Volley  : 	at java.net.URL.<init>(URL.java:601)
02-17 19:46:23.398 12320 14006 E Volley  : 	at java.net.URL.<init>(URL.java:498)
02-17 19:46:23.398 12320 14006 E Volley  : 	at java.net.URL.<init>(URL.java:447)
02-17 19:46:23.398 12320 14006 E Volley  : 	at b.a.b.w.g.a(SourceFile:8)
02-17 19:46:23.398 12320 14006 E Volley  : 	at b.a.b.w.b.f(SourceFile:4)
02-17 19:46:23.398 12320 14006 E Volley  : 	... 2 more
02-17 19:46:23.405 12320 12320 E g4      : validateHassIngressSession: error: b.a.b.u: java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:46:23.405 12320 12320 E g4      : validateHassIngressSession: error: b.a.b.u: java.lang.RuntimeException: Bad URL null/api/hassio/ingress/session
02-17 19:50:10.859 12323 12323 E r.patrick.groc: Unknown bits set in runtime_flags: 0x20000
02-17 19:50:10.861 12323 12323 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
02-17 19:50:25.895 13691 13691 E r.patrick.groc: Unknown bits set in runtime_flags: 0x20000
02-17 19:50:25.898 13691 13691 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent

**Comment by MrJohnZoidberg** [comment]
Thanks! They shouldn't occur in the next alpha anymore.
