### ISSUE TITLE
Test report

### ISSUE THREAD

**Issue by aniamisiewicz** [patzly/grocy-android#275]
Hi! 
As a part of a university course called "Software Testing" (Jagiellonian University in Poland) we performed some blackbox testing on your app. 
During this process we discovered some bugs that we would like to report. 
This process took place 3 months ago so we are aware of the fact that some of them may be out of date. In spite of this, we attach the report.
[Full_Grocy_Test_Report (1).pdf](https://github.com/patzly/grocy-android/files/5824302/Full_Grocy_Test_Report.1.pdf)

We hope that would help you somehow!

Our team: github.com/aniamisiewicz, github.com/juliacichosz, github.com/klaudiagoska
We love the app btw :)

**Comment by MrJohnZoidberg** [comment]
Thanks a lot for this test report! We appreciate your feedback and will try to fix all these bugs.
