### ISSUE TITLE
Suggestion: Reduce margin around items

### ISSUE THREAD

**Issue by k3a** [patzly/grocy-android#294]
First, thanks for the awesome app and all the work you did!

Next, in my opinion there is too much space wasted between items. 
It can be a bit annoying especially for the Shopping list as it requires me to scroll the list to see more than 6 items.

I can see 5 items in the main screen and 6 items in the shopping list which seem quite low to me.

It is not a big deal and you can keep it as is if you think it's ok and close the issue right away.
I decided to suggest it and maybe get opinions from other users...

**Comment by MrJohnZoidberg** [comment]
Thanks for your feedback!
We want our app to comply with the Material Design Guidelines, but maybe we can add an option in settings which decreases space between rows. But we will look into this later, because currently the new versions of our app have higher priority, sorry.

**Comment by MrJohnZoidberg** [comment]
I've implemented an option yesterday to use smaller items on the shopping mode page. I think all other pages should not have other sizes for entries, that would be too much work. If you want to see more content on all pages, please use the option in your phone settings to change the display/content size.
