### ISSUE TITLE
[v2.0.0] Update warning [fixed] + language settings [implemented]

### ISSUE THREAD

**Issue by InToSSH** [patzly/grocy-android#322]
Hi guys,
first of all, thank you very much for your hard work on the new v2.0.0

I installed the app and every time I open it I get the "Update warning" saying that I use Grocy Android 1.10.1, but I use the new v2.0.0

Another thing, I helped translating the app to Czech language, but I can't find an option in the app's settings to change the language. I assume it is using english based on the language of the phone (which has to be in english - because of Google Assistant), so I would really like to have the option in app to change language. I wanted to check all the translated strings and fix the ones that don't make sense.

Thank you

![Screenshot_20210208-210742_Grocy](https://user-images.githubusercontent.com/6452373/107275617-4c021700-6a52-11eb-8bf4-6fd602dff37e.jpg)

**Comment by MrJohnZoidberg** [comment]
Thanks for your feedback! The first thing will be fixed in the next alpha (I think we can post that tomorrow in the Testing issue, because this update warning is annoying for you).
For the second one we have to investigate a bit more, I don't know how this can work, but it should work because other apps also have this option.

**Comment by InToSSH** [comment]
Thank you, now that I logged in to my server and used the app for a bit (added and consumed a product), the warning stopped showing so no need to rush :)

The language setting is actually more crucial for me, because I would like to use the app on the tablet in the kitchen, which is in english (as I said earlier, Google Assistant doesn't work that well in czech language), but my girlfriend uses Grocy in czech.

**Comment by patzly** [comment]
I've implemented the language setting in another app already to force German and it works very well, so this is no problem.
A language selection bottomsheet with all available languages would be required and a setting to display it, maybe in Appearance or Behavior category.

**Comment by InToSSH** [comment]
Awesome. My first thought when I was looking for the setting was to go to Appearance. I think Behavior is more for the logical setting. But it's up to you :). And the language list I would either stick to all english names (I think everybody knows their language name in English and it's easiest) or each language name translated to its respective language (English, Deutsche, Čeština) , but I would not recommend translating all names to each language (when an english speaking person accidentally switches to czech, they will have hard time knowing English is Angličtina in Czech language, etc)

**Comment by patzly** [comment]
The language names are now displayed in the system language (no matter which language is selected in the app).
I think that's the best way because everyone can understand his own system language.

**Comment by InToSSH** [comment]
Amazing, thank you very much :)
