### ISSUE TITLE
[v2.0.0] Better help text for scan mode

### ISSUE THREAD

**Issue by matthiakl** [patzly/grocy-android#332]
After activating the "Start in Scan-Mode" settings, I expected the scanner to open with the corresponding page, but I still have to tip on the icon to start it. Also the help text on the scan pages is misleading: It says to long press the title bar to start the scanner, which for me only toggles the keyboard.

OS: LineageOS 14.1 / Android 7.1.2

+1 for the performance/loading time improvement :+1:

**Comment by MrJohnZoidberg** [comment]
Hi, scan mode means the same in our app as on the web interface. So activate the scan mode only activates the "quick filling" of the product form – so the missing fields are asked automatically after entering a product.
If you want to scan a barcode with your camera AND want the "quick filling" enabled, you must click on the barcode after activating the scan mode.

The long press on the title bar only toggles the "quick filling"...
Maybe "scan mode" are the wrong words for that mode? But if we would rename it, it wouldn't be equal with the web interface anymore. And I don't know how it should be named better. What do you think and did you unterstand the difference now?

**Comment by matthiakl** [comment]
Ah, ok. Thanks for the explanation. I never used the web-interface for scanning, so I looked it up there now. I'm fine with the behavior in the App, you should only add something to the help text, as the one in the web interface is clearer about the auto-filling.

**Comment by MrJohnZoidberg** [comment]
Ok, thanks – we will think about a better help text or an improvement of the old one.

**Comment by mbw2001** [comment]
Having the option to go directly to scan mode would be awesome as well.

**Comment by MrJohnZoidberg** [comment]
Yes, I thought about that, too. For that you can use the Floating action button on the start page. Short press on it means consume page and long press means purchase page – it opens also the barcode scanner if you don't have external device support enabled.

**Comment by MrJohnZoidberg** [comment]
I changed the "Scan mode" to "Quick mode" and improved help texts (they may be outdated in your language though) and behaviour. I hope this is better and easier to understand now.
The last state of the barcode scanner visibility is also stored (and restored with the next visit on the page) but I still have to find a way to keep the scanner open after a scan so the state can be stored properly.
