### ISSUE TITLE
[v2.0.0] [fixed] adding new product with "&" in it truncates product name

### ISSUE THREAD

**Issue by meldra** [patzly/grocy-android#333]
I submitted a product via the purchase screen called "lenny&larry cookie". I ended up with a product called "lenny".

Backslashes seem fine as i successfully created a 'rotini/rotelle' product with the same workflow, but this submission got truncated where the & should have been.

It's a fairly common char for products, brands and even stores.

**Comment by MrJohnZoidberg** [comment]
Thanks! I can reproduce this one – but I don't know where I truncante such a char in the code...
I will debug it later this day.
