### ISSUE TITLE
[v2.0.0] "App not installed" with Alpha 1

### ISSUE THREAD

**Issue by geekywalrus** [patzly/grocy-android#345]
**Device:** Samsung Galaxy Note 8
**Android version:** 9.0 (OneUI 1.0)
**Developer mode:** Enabled
**Root:** No

**Description**
I've given my file manager (Solid Explorer) all permissions necessary to allow it to install unknown apps as well. I tap "Install" and it tries to install for a few seconds, then responds with "App not installed".

If there's a way I can provide you with logs, let me know. I know usually a logcat is helpful, but I'm not sure how to provide one without root. My charging port is broken so ADB isn't usable for me unfortunately.

**Comment by MrJohnZoidberg** [comment]
Hi, did you install the old version from F-Droid or Google Play Store? Because F-Droid has another signature and this means you have to uninstall the old application before installing the alpha.

**Comment by geekywalrus** [comment]
Darn.. That's embarrassing.. Didn't even think of that. That was the
problem. Thanks. Working great so far.

**Comment by MrJohnZoidberg** [comment]
Great, thank you! I will write this into the installation steps in the testing issue.
