### ISSUE TITLE
[v2.0.0][fixed] Crash when choosing a store for purchase.

### ISSUE THREAD

**Issue by samnewman86** [patzly/grocy-android#347]
See video:
--- beginning of system
02-10 22:15:11.366 19299 19299 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
02-10 22:15:12.254 19299 19299 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
02-10 22:15:13.202 19299 19299 E VpsExtension: Failed to get binder for service "vendor.vpsservice"
02-10 22:15:15.512 19299 19299 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-10 22:15:41.389 19299 19299 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-10 22:15:52.971 19299 19299 E AndroidRuntime: FATAL EXCEPTION: main
02-10 22:15:52.971 19299 19299 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 19299
02-10 22:15:52.971 19299 19299 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.l.k4.h0(SourceFile:3)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.f.T.g(SourceFile:4)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.g.a.c.onClick(SourceFile:1)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.k.e.onClick(SourceFile:2)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at android.view.View.performClick(View.java:7335)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7304)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at android.view.View.access$3600(View.java:815)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28155)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7711)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-10 22:15:52.971 19299 19299 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
02-10 22:15:53.185 20443 20443 E r.patrick.groc: Unknown bits set in runtime_flags: 0x20000
02-10 22:15:53.188 20443 20443 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
02-10 22:15:53.403 20443 20443 E TextView: Saved cursor position 3121/3121 out of range for text

**Comment by samnewman86** [comment]
https://www.dropbox.com/s/11kw1i1b7ojmk7s/21-02-10-22-15-39.mp4?dl=0

**Comment by MrJohnZoidberg** [comment]
Thanks. Do you have any stores in master data? I didn't test it without stores configured.

**Comment by samnewman86** [comment]
The crash was when there were no stores configured.
Maybe needs a way to handle that
