### ISSUE TITLE
[v2.0.0] Wrong QU plural form shown

### ISSUE THREAD

**Issue by InToSSH** [patzly/grocy-android#348]
Hello,
thank you for implementing the language settings.
Now that I switched to czech language, I noticed the wrong plural form of quantity unit is shown (so far discovered in stock overview and shopping list).

In czech language we use 4 different forms.

QU master data:
![chrome_2021-02-11_02-05-31](https://user-images.githubusercontent.com/6452373/107592593-b1e6ce00-6c0d-11eb-925b-907fc4fcf8e8.png)

This shows correctly in Grocy Web UI:
![2021-02-11_02-06-45](https://user-images.githubusercontent.com/6452373/107592660-d17df680-6c0d-11eb-810a-4f3529284c62.png)

And this is what is shown in the Grocy Android:
<img src="https://user-images.githubusercontent.com/6452373/107592759-0722df80-6c0e-11eb-8760-dfe2aec1a795.jpg" width="300" />

**Comment by MrJohnZoidberg** [comment]
Hi, sorry, the extended quantity unit form like in the web interface (with the multiple plural forms) is not implemented yet (and the functionality is missing, too)... I think this is a duplicate of #183, but I will let it open as reminder.

**Comment by InToSSH** [comment]
That's alright.. I wasn't sure if it was implemented before and got broken or if it's a new thing, I started using Grocy at server v3.0.0 :-) This is just for the final polish, nothing important. Thank you

**Comment by MrJohnZoidberg** [comment]
Hi, I'm currently working on this issue but I'm struggling with the server implementation (how the plural selection behaves there)...

Do you know how to fill out the field "plural forms" correctly so that the server select the plural according to the language's plural rules? There is the help text "one plural form per line" and "this language requires X forms". So my understanding is that you have to write X lines in this field. But the server doesn't choose all forms from this field if I test with all cardinal numbers which have different rules [here](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html) (I tested polish and czech for example). I saw that also the first field (name) and the second field (name plural) are chosen sometimes...

In czech there are 4 plural forms needed like the help text says in your first screenshot. But why did you only write two forms in it? I hope you can help me, because I don't want to bother the grocy server developer with that...

**Comment by MrJohnZoidberg** [comment]
Hallo @berrnd, ich habe eine Frage zu den Pluralen der Mengeneinheiten in Sprachen mit mehr als einem Plural. Auf der Server-Website wird ja, wie der Screenshot ganz oben zeigt, bei Stammdaten -> Mengeneinheiten ein weiteres Feld für Plurale angezeigt, wenn die Sprache mehr als ein Plural hat (bzw. mehr als 2 Kardinalformen).
Darüber steht z.B. bei [Polnisch](https://pl.demo.grocy.info/quantityunit/3), dass 4 Formen benötigt werden, eine pro Zeile. Also trage ich z.B. "A" "B" "C" und "D" ein und teste die Formen mit dem Testbutton und den Kardinalzahlen von [hier](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#pl).

- Bei der 1 wird die Form angezeigt, die im ersten Feld (Singularform) der Website steht. Ich würde erwarten, dass stattdessen die erste Zeile des Pluralforms-Felds genommen wird, aber das ist noch verständlich.
- Aber bei der 2 wird jetzt nicht, wie mit den Regeln erwartet, die zweite Zeile des Pluralforms-Felds genommen, sondern die erste Zeile (A)...
- Bei der 0 und der 5, bei denen ich mit den Regeln die dritte Zeile erwarten würde, wird die zweite Zeile ausgegeben (B).
- Und bei der 0.0 oder 1.5 oder 10.5, die alle laut den Regeln die vierte Pluralform brauchen, wird entweder die zweite Zeile (B) oder bei der 1.5 auch die dritte Zeile (C) ausgegeben.

Kannst Du mir erklären, warum das so ist? Ich will bei dir im Repo kein Issue dafür erstellen, weil das Feature ja anscheinend bei den Leuten funtioniert, wie oben beschrieben. Nur verstehe ich die Auswahl nicht ganz, sodass ich sie in unserer Android-App genau so nachbauen kann.

Im Issue zu diesem Feature im Server-Repo habe ich von Dir einen [Screenshot](https://github.com/grocy/grocy/issues/161#issuecomment-488780631) gefunden, aber leider bringt der mich auch nicht weiter.

Vielen Dank schon mal für Deine Hilfe :-)

**Comment by berrnd** [comment]
Ich habe ehrlich gesagt nicht wirklich Ahnung davon und mich selbst nie wirklich mit dem ganzen Thema beschäftigt, speziell nicht mit Sprachen die mehr als 2 Pluralformen haben...

grocy selbst benutzt, [GNU gettext / PO Files](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) (die Dateien in den Unterverzeichnissen vom [/localization](https://github.com/grocy/grocy/tree/master/localization) Ordner, kommen von Transifex).

Serverseitig (PHP) über [php-gettext/Gettext](https://github.com/php-gettext/Gettext) implementiert, clientseitig (JavaScript) über [gettext-translator](https://www.npmjs.com/package/gettext-translator).

Für die Mengenenheiten werden "virtuelle PO files" generiert, hier:
https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/services/LocalizationService.php#L191-L204

Sorry, ich kann von daher nicht wirklich sagen was falsch und richtig ist / ob das aktuell in grocy selbst so passt oder nicht, bisher hat zumindest dazu noch niemand gemeckert...
