### ISSUE TITLE
Missing external barcode database (OpenFoodFacts/OFF)

### ISSUE THREAD

**Issue by phatair** [patzly/grocy-android#353]
Hello,  is the external barcode database lookup not yet implemented in the new 2.0 alpha version?

I'm missing the setting for this function.
Thanks for this great app. 

Best regards

**Comment by MrJohnZoidberg** [comment]
Hi, thanks for your feedback.
Yes, this is not implemented yet because I removed the "batch mode" pages and thus also the bottom sheet with barcode lookup (unintentionally). I will work on this soon.

Best regards

**Comment by ramon-kramer** [comment]
hi, any news about this? can't for the feature 'cause i'm just starting with grocy and have to add a lot of products :)

**Comment by MrJohnZoidberg** [comment]
Hi, sorry I need time to think about and implement the workflow – it is not easy... :)
So please be patient for some days or a week (or two, if it takes much time).
