### ISSUE TITLE
Keep screen orientation during scanning

### ISSUE THREAD

**Issue by matthiakl** [patzly/grocy-android#358]
It would be nice, if the screen orientation is prevented from changing (portrait <-> landscape) while the scan window is active. Sometimes it is not possible to align the product easily and turning the phone around would help, but this usually causes the app to relayout in landscape mode and the scan window does not match, either.

**Comment by MrJohnZoidberg** [comment]
Thanks, I will add an option in settings for that, which is enabled by default (so orientation is locked by default, if camera frame is open).

**Comment by MrJohnZoidberg** [comment]
Do you think we need this option? I've implemented it now without it and I think this is ok because who wants to rotate the screen while barcode scanning? :)

**Comment by matthiakl** [comment]
I don't need an option ;) If the orientation is only fixed when the scan window is open, it should be fine. Thanks for this feature.
