### ISSUE TITLE
[v2.0.0] [fixed] Language mix

### ISSUE THREAD

**Issue by 0xD0M1M0** [patzly/grocy-android#360]
2.0.0-alpha03:
Default system language: German
Manual setting in app: English

After playing a bit with the app (can't reproduce what I did. I was somewhere from adding a new product to scan it in purchase mode). The app went into a language mix. Headers in German, texts mostly English, settings German.
I closed the app/process fully and after a restart everything was English again. I will keep playing and next time remember what I do, when it happens.

**Comment by 0xD0M1M0** [comment]
It seems to happen when I put the app in the background and pull it back to the front.
![Screenshot_20210217-213014__01](https://user-images.githubusercontent.com/76812428/108264207-8876f680-7167-11eb-98d3-074304575a13.jpg)

**Comment by MrJohnZoidberg** [comment]
Thanks, I will look into it soon.
