### ISSUE TITLE
[v2.0.0] [implemented] Keyboard hides bottomSheet buttons

### ISSUE THREAD

**Issue by 0xD0M1M0** [patzly/grocy-android#361]
2.0.0-alpha03
While editing the product master data -> edit product -> optional properties -> Description field
the keyboard covers the "clear" and "save" buttons. While being in number fields the Google keyboard displays a tick to save the number, the keyboard in the description field shows the enter sign. I have to minimize the keyboard to find the save button again.
I guess this entry mode for text is used in multiple locations. I noticed it in this submenu.

**Comment by MrJohnZoidberg** [comment]
The problem is that we need the newline button here because the field allows a whole text with multiple lines (like on the web interface). And the keyboard can only display one action button... Maybe we can move the view a bit up.
