### ISSUE TITLE
[fixed] Shopping list notes: saving empty text field doesn't remove previous note

### ISSUE THREAD

**Issue by 0xD0M1M0** [patzly/grocy-android#362]
After writing a note in the shopping list the field contains a text. When editing this field in the shopping mode and removing with the keyboard all content (or using the clear button) and clicking on "save" doesn't "save" an empty value but ignores the save command.
It is impossible to remove the note in the "shopping mode". In the shopping list itself it removes the note.

**Comment by MrJohnZoidberg** [comment]
Oh, I forgot to implement the methods on the shopping mode page – thank you for this reminder.
