### ISSUE TITLE
[v2.0.0-alpha03] [fixed] Updates to master data are pushed to the wrong server

### ISSUE THREAD

**Issue by lambda1103** [patzly/grocy-android#363]
After installing the app I first tried it on the public demo server, which didn´t show any problems in my short testing.
Then I changed the server to my personal grocy instance and tried to add a location to my master data. When pushing the addition I noticed that nothing seemed to happen on my instance. A while later I was browsing the public demo again and noticed that the added location was pushed to the public demo instead of my private server. I checked again and the app tells me that it´s connected to my server and everything else is correct. Even the location list fits my server, only when pushing new locations they are sent to the public demo.

**Comment by MrJohnZoidberg** [comment]
Thanks, I can reproduce that.
