### ISSUE TITLE
[v2.0.0] [fixed] Language not applied

### ISSUE THREAD

**Issue by joaodsantos** [patzly/grocy-android#364]
After selecting a language that language is not applied on the app, it all remains in English. I can see this happening to Portuguese, both from Portugal and from Brazil. 
I'm not sure if this is because of the language code being used, when I select either I only see pt, not the 4 letter one pt-pt, pt-br.

I had a look at open and closed bugs and couldn't find anything related to this so just thought I'd flag it.

**Comment by patzly** [comment]
Thank you for reporting, I haven't tested Portuguese before! That's weird...
I think it has to do with the language variant. The code you see is not the full code being used internally, so that's not the problem. But the way the variant is selected could be wrong, I will look into this.

**Comment by patzly** [comment]
I just found the problem, we get the selected language from preferences as one string `pt-PT` and make a `new Locale(String code)` object with it.

Portuguese is currently the only language with variants in Grocy Android, all other languages can be converted to `Locale` objects by passing the code as a single argument as language code to the constructer.
For language with variants we need `new Location (String code, String country, String variant)`, so we have to split the string from preferences.

**Comment by joaodsantos** [comment]
Just had a chance to test this on alpha4, can confirm the language changes but pt-br is being selected for both options.

Stock overview is "Visão geral de stock" in pt-pt but I see "Visão geral de estoque" for both Portuguese options which is pt-br
