### ISSUE TITLE
[v2.0 alpha 4]  open not an option on consume

### ISSUE THREAD

**Issue by gmandres** [patzly/grocy-android#369]
I can't find anywhere the option to "open" an item.
This isn't available on the consume screen or any other screen I can find.

**Comment by MrJohnZoidberg** [comment]
The "open" button is on the bottom and only appears if you've selected a product which doesn't use tare weight behavior.
Should I move this button into a line in the form which you can tick (like the "spoiled" line)? Then it would be more accessible.

**Comment by gmandres** [comment]
I would prefer it inline with those items.
I still cannot find it, even on items without tare weight measurement enabled.

**Comment by MrJohnZoidberg** [comment]
Can you provide a screenshot where you think that the open button is missing?
I thought again about the inline option and I don't think that this is a good idea. Because the option may be covered by the bottom app bar or you have to scroll down to reach it. It shouldn't be like this.

**Comment by MrJohnZoidberg** [comment]
Ping! :) Please answer us with a screenshot of the consume page and the missing open button or let us know it the issue can be closed.
