### ISSUE TITLE
Sorting of umlaut

### ISSUE THREAD

**Issue by 0xD0M1M0** [patzly/grocy-android#371]
2.0.0-alpha04:
On all pages with lists: the umlauts ä, ö, ü are either sorted before or after "Z". Based on DIN 5007 they should be treated as normal letters. Just an enhancement and probably nitpicking (found it by accident on a spelling error :) ).

A big thank you for putting so much work into this project!

**Comment by Ape** [comment]
Note that this depends on the language. DIN 5007 is not a global truth.

**Comment by MrJohnZoidberg** [comment]
In the next alpha version, lists will use rules (which are integrated in Android) of the current locale for sorting. For German this is working now with umlauts. :+1:
