### ISSUE TITLE
[v2.0.0] [fixed] Portuguese variants not being applied

### ISSUE THREAD

**Issue by joaodsantos** [patzly/grocy-android#372]
Just had a chance to test my previous issue #367 on alpha4, can confirm the language changes but pt-br is being selected for both options.

Stock overview is "Visão geral de stock" in pt-pt but I see "Visão geral de estoque" for both Portuguese options which is pt-br

(added this same comment on the other issue but it's closed so decided to open a new one)

**Comment by MrJohnZoidberg** [comment]
Thanks! It's fixed now (with the next alpha version) but you have to select your language again to see the change.
