### ISSUE TITLE
[v2.0.0] Scan Mode only works with one item

### ISSUE THREAD

**Issue by mahrulez** [patzly/grocy-android#374]
Scan mode only works with one item.
If you try to scan the next one a barcode occurs but the item is not removed from the database.
Exiting to "Home"-Screen of the app and enter consume part again the next item can be scanned.
P20 Pro
Android 10

**Comment by MrJohnZoidberg** [comment]
Please explain your complete workflow, I cannot reproduce this issue with this description.

**Comment by mahrulez** [comment]
If you want to scan more then one different item (one after the other). A red barcode appears. It works only when you leave the scan window back to the main menu and go back in to the scan window.

**Comment by MrJohnZoidberg** [comment]
Do you mean the purchase page or the consume page or both?
What do you mean with red barcode? Could you please provide a screenshot?

**Comment by MrJohnZoidberg** [comment]
Is this still an issue or has it been solved with one of the last versions?

**Comment by mahrulez** [comment]
I will try it later at the weekend with the new beta version and give you feedback.
