### ISSUE TITLE
Inconsistent estimate of stock value

### ISSUE THREAD

**Issue by daviewales** [patzly/grocy-android#376]
On the web version of grocy, it says I have 125 items in stock, with value $264.
On the grocy-android , it says I have 125 items in stock, with value $300.78.

Is this a grocy bug, or a grocy-android bug?

See screenshots below:

**Grocy**
![image](https://user-images.githubusercontent.com/2499066/110227687-2bdd4f00-7f4f-11eb-83ca-1aea4ef85185.png)

**Grocy Android**
![Screenshot_20210307-141039](https://user-images.githubusercontent.com/2499066/110227720-778ff880-7f4f-11eb-9bf4-f2133fe0560e.png)

## Info

Grocy version: 3.0.1
Grocy-Android version: 2.0.0 Alpha 5

**Comment by Ape** [comment]
It's a Grocy bug that has been already fixed for the next release.
