### ISSUE TITLE
Unable to connect to the server on a non-root location

### ISSUE THREAD

**Issue by AliZaidi1500** [patzly/grocy-android#377]
When trying to connect to the grocy server running on address 192.168.0.100, the app says `Failed to connect to https://192.168.0.100/grocy`. The grocy server instance is running under the `/grocy` subdirectory and web access works fine. I went ahead and accessed the api directly to get the server info from `https://192.168.0.100/grocy/api/system/info?GROCY-API-KEY=my_api_key` and it returns `{"grocy_version":{"Version":"2.7.1","ReleaseDate":"2020-04-17"},"php_version":"7.3.25","sqlite_version":"3.32.1"}`.

**Comment by MrJohnZoidberg** [comment]
Mmh I've just tried it with my server and a subdirectory and it's working (so it's no bug in our app I think)... Maybe it's something on your side which blocks connections for our app? Can you try it again with the latest alpha?

**Comment by fanul** [comment]
strangely enough i encounter this issue lately... would you mind provide nginx.conf and config for grocy...
