### ISSUE TITLE
Scanning issues

### ISSUE THREAD

**Issue by DrTechdom** [patzly/grocy-android#378]
When scanning out a product with the consume function the app crashes. Most of the time when it does scan and the app doesn't crash... The upc shows as scanned but the product still shows that it's required to be filled.

**Comment by DrTechdom** [comment]
--------- beginning of crash
03-20 12:35:54.890  5410  5410 E AndroidRuntime: FATAL EXCEPTION: main
03-20 12:35:54.890  5410  5410 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 5410
03-20 12:35:54.890  5410  5410 E AndroidRuntime: b.b.b.v: java.lang.NumberFormatException: empty String
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.b.b.z.z.o$D.b(SourceFile:4)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.b.b.z.z.i.a(SourceFile:1)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.b.b.z.z.j$a.b(SourceFile:9)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.b.b.z.z.n.b(SourceFile:1)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.b.b.z.z.b$a.b(SourceFile:6)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.b.b.i.b(SourceFile:9)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.a.a.a.a.g(Unknown Source:5)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.h.k.a(SourceFile:3)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.h.a.a(Unknown Source:4)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.m.e.a(SourceFile:3)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.a.b.w.k.e(SourceFile:5)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.a.b.g$b.run(SourceFile:5)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: Caused by: java.lang.NumberFormatException: empty String
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at java.lang.Double.parseDouble(Double.java:538)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.b.b.B.a.G(SourceFile:16)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	at b.b.b.z.z.o$D.b(SourceFile:3)
03-20 12:35:54.890  5410  5410 E AndroidRuntime: 	... 18 more
--------- beginning of main
03-20 12:36:32.061  8858  8858 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
03-20 12:36:32.333  8858  8880 E libc    : Access denied finding property "vendor.gralloc.disable_ahardware_buffer"

**Comment by MrJohnZoidberg** [comment]
Could you please provide more information (detailed steps you've performed to reproduce)? Do you use an external scanner or the camera scanner?
With the given information I cannot reproduce the issue.

**Comment by MrJohnZoidberg** [comment]
@DrTechdom Please tell us if this is still an issue.

**Comment by MrJohnZoidberg** [comment]
Closed due to inactivity / no answer.
