### ISSUE TITLE
[v2.0 alpha 5] Possible to set font size in shopping mode?

### ISSUE THREAD

**Issue by Uatschitchun** [patzly/grocy-android#379]
Hi, great app!!
Would it be possible to get a setting for the size of the shopping list? It would be handy to have it smaller (more items).

**Comment by patzly** [comment]
Hi, thanks for your suggestion! Do you mean the default shopping list or the separate shopping mode with the extra big font size?

**Comment by Uatschitchun** [comment]
Sorry for not being precise, I meant the shopping mode.

**Comment by patzly** [comment]
Ok that's a good idea, thanks!

**Comment by bqv** [comment]
(I miss the old font 😞)

**Comment by MrJohnZoidberg** [comment]
@bqv We're sorry to hear that, but we think the new font is better because it is not monospace and there doesn't need so much space. We hope you can understand that.
