### ISSUE TITLE
Shopping list bug

### ISSUE THREAD

**Issue by DrTechdom** [patzly/grocy-android#380]
When editing a shopping list item on mobile web, you can not save unless you fill out the notes section. This shouldnt be required.

**Comment by Uatschitchun** [comment]
Is this one deriving from https://github.com/grocy/grocy/issues/1268 ?

**Comment by DrTechdom** [comment]
No that doesn't seem to be the same thing. I was going to take a screenshot but I can not reproduce the issue.

**Comment by patzly** [comment]
When you say "mobile web", do you mean the web interface of your grocy instance in a browser or our app?

**Comment by lambda1103** [comment]
Yeah, I'm pretty sure you're right @patzly 
I can reproduce this in the website on mobile but in the app it works fine

**Comment by patzly** [comment]
Ok, then you have to go to [grocy by Bernd Bestel](https://github.com/grocy/grocy), the server application with the web interface is his project. Grocy Android is just an independent native Android app which uses his API, so we are not responsible for this ;)

**Comment by lambda1103** [comment]
Yeah, it's already fixed grocy/grocy#1289
