### ISSUE TITLE
Unerwarteter Antwort-Code: 400

### ISSUE THREAD

**Issue by LeoLTM** [patzly/grocy-android#381]
Ich habe auf meinem Hass.io Linux Server 2 IPv4 Adressen am Netzwerkadapter konfiguriert und kriege trotz eingestelltem Port keine Verbindung zu Grocy. 
Die IPv4 Adressen seien:
192.168.2.100
192.168.2.101

und wenn ich in Hass.io den Port 99 einstelle, erhalte ich bei frisch erstelltem API Token in Grocy und der Server Adresse http://192.168.2.100:99 oder anderen konfigurierten Ports die Fehlermeldung im Titel.

Ich habe es mit der Google Play Version und der neuesten GitHub Alpha getestet, LLAToken und QR Code sind korrekt eingegeben. 
DuckDNS läuft auch in Hass.io, falls das etwas zur Sache tut.

**Comment by MrJohnZoidberg** [comment]
Hi, beziehst du dich auf die [alte Anleitung](https://github.com/patzly/grocy-android/blob/master/FAQ.md#user-content-faq4) zum Verbinden mit Home Assistant?
Ich vermute schon, denn du öffnest ja einen Port. In der aktuellen Alpha-Version unserer App kannst du dich mit Home Assistant verbinden, ohne einen Port öffnen zu müssen – kannst du diesen Weg mal versuchen?
Bei Fragen dazu gerne hier nochmal melden. :)

**Comment by LeoLTM** [comment]
Oh, da habe ich wohl was übersehen! Ganz ohne Port klappt die Verbindung jetzt wunderbar. 
Danke für den Tipp und die super App! Ist sowohl vom Design als auch vom Potenzial einfach klasse. 

Freue mich auf weitere Features und Fixes, LG.

**Comment by MrJohnZoidberg** [comment]
Danke für die netten Worte!
Es kann sein, dass die neue Verbindung zu Home Assistant noch nicht ganz reibungslos läuft (da haben paar Leute Probleme berichtet). Da werde ich noch dran arbeiten.
LG
