### ISSUE TITLE
Offline transactions with sync functionality

### ISSUE THREAD

**Issue by jamesgeddes** [patzly/grocy-android#384]
It would be great to be able to do stuff while offline then have the app update the server when connection is made available again.

**Comment by MrJohnZoidberg** [comment]
Currently you can mark items on your shopping list as done while offline and these changes will be synced with your server.
But all other transactions cannot be handled offline properly, because we completely rely on the server for any transactions (we don't use a complete database with transaction calculation in the app, but the server does) and therefore won't handle them offline.

**Comment by jamesgeddes** [comment]
That's what I meant, I would like, for example, to be able to see what I have in stock while my phone is offline. I appreciate that it's a big change but it would be a valuable one.

**Comment by MrJohnZoidberg** [comment]
Ah now I understand. You can already load all lists without internet connection except stock overview (because this is still from an old app version). I'm currently working on this one so that this page also stores and loads data for offline view.👍

**Comment by jamesgeddes** [comment]
That's good, however as you say, it would be good to use a complete database with transaction calculation in the app and then advise the server of any changes. Mobile devices are not known for having reliable connections (I am an ardent Ethernet fanboy) so doing everything locally and then ensuring that the server has received the message is a much more robust way of ensuring integrity. Also a lot more complex, admittedly!

**Comment by jamesgeddes** [comment]
Additionally, VPN takes a *tonne* of battery on many mobile devices, so being able to synchronise changes when you get back from the shops would be super.

**Comment by MrJohnZoidberg** [comment]
Sorry, but honestly we won't implement this. Because even the developent of the app without such a sync functionality needs almost too much work for us and therefore we cannot spend even more time for this feature.
You don't have to use VPN if you have a grocy instance which is accessible from the internet. So maybe this would be an option for you.

**Comment by jamesgeddes** [comment]
I appreciate that it is a big project so perhaps this could be open but marked as P4 or similar? Perhaps someone else might be able to take it on? Like I say, I know it is not a priority but I really think that this would add value. No harm in having tickets open and left for others to get their teeth into. I might be interested in doing this later this year once I have some time free, for example.

**Comment by jamesgeddes** [comment]
Thanks @MrJohnZoidberg

**Comment by Saturo78** [comment]
I also would prefer a solution which stores all data local and syncs them in the background with the server.
I actually use an App which works that way, and its much more fluent and comfortable but i want to switch to grocy because i want to use the recipe features.

**Comment by patzly** [comment]
As my brother already said, this is just too hard to implement and an overkill for a companion app that just displays content from a server and uses its API, and these offline transactions would have nothing to do with an API request anymore. Google's own apps would also just display an error message that the device is offline and needs to go back online to make any transactions.

**Comment by dominiczedler** [comment]
We decided to close issues where we think that they will never be implemented. We have limited time for this project and thus we want to concentrate on the important things and enhancements which keep the app running.
