### ISSUE TITLE
Item Transfer

### ISSUE THREAD

**Issue by jamesgeddes** [patzly/grocy-android#385]
It would be great to be able to record location transfers from within the app.

**Comment by MrJohnZoidberg** [comment]
This page will come soon.👍

**Comment by jamesgeddes** [comment]
I must say that you guys are doing a sterling job with this. Well done! I, for one, am very grateful for all your efforts.

**Comment by MrJohnZoidberg** [comment]
Thanks a lot, this motivates us!
