### ISSUE TITLE
Gets timeout error when trying to connect to grocy running on hass

### ISSUE THREAD

**Issue by MobbareKurtZ** [patzly/grocy-android#387]
I'm running a Grocy instance on HomeAssistant supervised running on docker. I tried using both the alpha and stable version of the app but get "Timeout error" every time I attempt to connect to my server. The API-key is fine, I'm attempting to connect to https://******.duckdns.org and have also tried doing it with a port set in the network settings on the hassio addon. I can't seem to understand why I would get a timeout error.

**Comment by MrJohnZoidberg** [comment]
Did you try it in our current alpha version with the form for Home Assistant?
I mean this page:

<img src="https://user-images.githubusercontent.com/27244574/115925121-ef26d200-a480-11eb-9bf6-467ab8253323.png" alt="Screenshot" width="250"/>

There you can click in the card on the top and the form for Home Assistant appears:

<img src="https://user-images.githubusercontent.com/27244574/115925304-39a84e80-a481-11eb-9559-2bf295f8affd.png" alt="Screenshot" width="250"/>

With this method you don't need to open a port. (The FAQ is outdated for this new method and only mentions it in one sentence)

**Comment by MobbareKurtZ** [comment]
> Did you try it in our current alpha version with the form for Home Assistant?
> I mean this page:
> 
> <img alt="Screenshot" width="250" src="https://user-images.githubusercontent.com/27244574/115925121-ef26d200-a480-11eb-9bf6-467ab8253323.png">
> 
> There you can click in the card on the top and the form for Home Assistant appears:
> 
> <img alt="Screenshot" width="250" src="https://user-images.githubusercontent.com/27244574/115925304-39a84e80-a481-11eb-9559-2bf295f8affd.png">
> 
> With this method you don't need to open a port. (The FAQ is outdated for this new method and only mentions it in one sentence)

Yes I've tried that, still getting a Timeout error.

**Comment by MrJohnZoidberg** [comment]
Hi again, I think this is related to #413... Can you try to append :443 to your Home Assistant server URL? The current behavior is that the app assumes that the Home Assistant server is running on port 8123 and only tries this one.
The progress of a better behavior implementation is tracked in #413, please write me here if the solution above works for you.

**Comment by MrJohnZoidberg** [comment]
Closed due to inactivity / no answer.
