### ISSUE TITLE
Google assistant integration

### ISSUE THREAD

**Issue by augustodinizl** [patzly/grocy-android#389]
Good evening,

First of all, congratulations for the excelent work with the app.
Second, sorry about my poor english.
Third, is in your plans make the android app compatible with google assistant?

Again, THANKS FOR YOUR BRILLIANT work!!!!

Edit: maybe something like that: https://developers.google.com/assistant/app/intents

**Comment by MrJohnZoidberg** [comment]
Hi, thanks for your compliments!

I'm sorry, we don't have the time to implement Google Assistant right now.
But we can let this issue open for later. :)

**Comment by dominiczedler** [comment]
We decided to close issues where we think that they will never be implemented. We have limited time for this project and thus we want to concentrate on the important things and enhancements which keep the app running.
