### ISSUE TITLE
please sign the APK

### ISSUE THREAD

**Issue by IzzySoft** [patzly/grocy-android#4]
Could you please sign the APK attached to `releases/`? I currently get a signature error with `apksigner` (could be only v2 signature is missing, I'm not sure). Thanks!

**Comment by patzly** [comment]
The apk is signed only with full APK signature (v2).
Do you have Android 6 or below? I didn't know that v2 was first introduced in Android 7, so maybe this could cause an error on older versions of Android. On my device running Android 10 it works.

**Comment by patzly** [comment]
The `v1.1.0` release apk is signed with v1 and v2, hope it works!

**Comment by IzzySoft** [comment]
Yes! That solves the issue, thanks a lot!

As for your questions:

* description says Android 5 or higher. v2 was IMHO introduced with MM.
* I didn't install it – as I wrote, it was `apksigner` which complained.

So why `apksigner`? Well, I check apps from "unknown sources" against different sources. And as your Readme writes "F-Droid: soon™", I thought I'd help that a little and get it into "staging"; so in less than 22h it should [turn up here](https://apt.izzysoft.de/fdroid/index/apk/xyz.zedler.patrick.grocy) – where it can be installed (and kept up-to-date) with the F-Droid app directly from the Android device. Congrats: *Grocy* is app number 500 there and thus made the repo break a new record :smile:

Disclosure: I'm also one of the F-Droid maintainers. When you want to bring your app to f-droid.org I gladly assist. My scanners all approved – but they admittedly didn't check for "blobs" or "untrusted Maven" etc. in your repo.

I'm closing this issue as it is solved (updates will be fetched automatically within 24h whenever you create a new tag and attach an APK to it). Feel free to ping me from another issue should you need help getting the app to f-droid.org – or simply go straight to [open an RFP](https://gitlab.com/fdroid/rfp/issues), which will ping me automatically (that's where I'm "maintaining").

Thanks again!

PS: If you wish to link to your app in my repo, [here's a badge for that](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :smiley:

**Comment by MrJohnZoidberg** [comment]
@IzzySoft 
Thank you very much for your efforts to bring our app to F-Droid!
I really like the F-Droid store and have it installed on many devices – so when we have time, we will open an FRP to make the app available in the main repo.

Thanks again for your help and advice, you're doing a great job! :smiley:

**Comment by IzzySoft** [comment]
Glad you like it – and thanks for the compliments! With Grocy being the app bringing the numbers to 500, I couldn't resist [tooting it on Mastodon](https://mastodon.technology/@IzzyOnDroid/104203180713177484). Turned out as successful advertizing Grocy: got [responses saying](https://mastodon.technology/@mondstern/104205788112984430) "hey, that looks promising – need to find someone to host the server part for me" :smile:

Looking forward to your RFP then :smiley:
