### ISSUE TITLE
Consumption order works only in default location

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#402]
The consumption order open, due, fifo is applied to the default storage location. An open stock in another storage location is not consumed first.

**Comment by MrJohnZoidberg** [comment]
Is this the right place for this issue? I mean we only make API requests to the grocy server and so I'm sure that we cannot fix this issue because it's server side...

**Comment by Saturo78** [comment]
Thanks, i will  adress the issue to grocy and close this one.
