### ISSUE TITLE
Save on top

### ISSUE THREAD

**Issue by firlevapz** [patzly/grocy-android#405]
Thanks for this great app for grocy!
It would be great to have an option to have the save-button on the top, probably sticky inside the header, so i don't have to press the back-button to reveal the save-button, because it's hidden by the keyboard. 

Thanks!

**Comment by MrJohnZoidberg** [comment]
Thanks for the suggestion and your nice words, we will look how we can implement this.

**Comment by politas** [comment]
I strongly second this, or if the app window can be set to shrink as the keyboard expands, instead of being covered? I think [this](https://aubykhan.wordpress.com/2011/09/17/android-development-tips-resizing-layout-while-on-screen-keyboard-is-displayed/) is how to do that.

**Comment by politas** [comment]
If I understand it, it looks like that would need to be changed [here](https://github.com/patzly/grocy-android/blob/8e0d5dee2a0ae8ba4a5eaa1839853590e2ece707/app/src/main/AndroidManifest.xml#L53-L56)?

Android app development is not something I've delved into before.

**Comment by MrJohnZoidberg** [comment]
@politas Naah that's not a good way to solve this issue, it would influence the behavior of the complete app in a negative way. We need to add or move some buttons to the top of the screen or sth like that. Or change the behavior of the enter/action key of the keyboard.

**Comment by martin-braun** [comment]
@dominiczedler Moving the button in the header would make it harder to reach, though. Best practice would really be to adjust the edge insets when the soft keyboard is shown. I wonder why this would break the UI of the design. 

If this is really not possible, maybe it is possible to move the sticking footer up above the soft keyboard if it is shown.

**Comment by dominiczedler** [comment]
There is now a new UI behavior in the latest nightly builds.
