### ISSUE TITLE
Barcode scanning not recognising products

### ISSUE THREAD

**Issue by diagonali** [patzly/grocy-android#408]
Sorry if this is a known issue and will be fixed as the development carries on but I remember the old app recognised products when they were scanned and populated the name and other info. It's currently not doing that in beta01. Is this coming in this release eventually? Thanks

**Comment by MrJohnZoidberg** [comment]
Hi, this is a known issue and it will be implemented soon again.
The issue for that is #353 :)

**Comment by diagonali** [comment]
> Hi, this is a known issue and it will be implemented soon again.
> The issue for that is #353 :)

Ok thanks very much
