### ISSUE TITLE
Don't assume port 8123 during setup

### ISSUE THREAD

**Issue by nicogramm** [patzly/grocy-android#413]
Hello 👋
I'm running a reverse proxy setup with Home Assistant, which exposes it on the default HTTPS port 443.
When I setup the app, scan the api-token qr-code and enter the URL without any port, it automatically assumes port 8123.
This of course then leads to the app not being able to connect with the instance.

My workaround is to enter the URL with the HTTPS port 443 appended:
So
`<example.org>:443`
instead of just
`<example.org>`

I think this behavior isn't intended or expected by the general user.
I recognise this issue is fairly low priority but it would make the onboarding just that bit more perfect.

Thank you for your great work so far!

**Comment by MrJohnZoidberg** [comment]
Hi, thank you for your nice words! This indeed not a gread behavior and I was planning to change that anyway (before final v2.0.0 release). I just thought that the normal user forgets to append the port 8123 and so I assumed that it would be the best solution to append 8123 if there isn't a port appended already... Do you have any ideas how the interface could be better but still easy to use for "normal users" which don't think about ports?
I was thinking about a new info/selection field with the port which is used with the current written URL. Maybe also a selection field so that one can change that default port to something other? Or am I thinking too complex and there are simpler solutions?

Thanks in advance for your ideas (if you have some) :)

**Comment by nicogramm** [comment]
Hi, thanks for getting back so quickly!

Maybe I'm thinking too simple here but maybe you could first try to reach the instance on port 443 if there's none specified, because that's what's expected by users with reverse proxy setups (or if they just straight up changed the port of HA).
If that fails however you could still silently try port 8123 and use that if it's successful.

And because these are the only two reasonable guesses we can make, the last step after this would be to fail. 
The failure message should however mention neither port 443 (or 80 if the http radio button is checked) or 8123 being reachable so the user is aware what trouble shooting steps they don't need to try anymore.

These are the first things coming to my mind

**Comment by MrJohnZoidberg** [comment]
Thanks for your ideas, I will try these out soon.:+1:

**Comment by MrJohnZoidberg** [comment]
How do you find this idea? Yes, with that interface you need a bit knowledge about ports but I think this ok.
The 443 in the description would change automatically to 80 if the user enters a http URL. And these two options would disappear if the user appends a port after the URL.
What do you think?

![grocy-login](https://user-images.githubusercontent.com/27244574/119044363-6422f400-b9ba-11eb-9df9-28c990e5b75d.png)

**Comment by nicogramm** [comment]
I mean that could work, sure.
But I don't quite understand yet why you would want to expose that as an UI option like that at all.
I mean if it doesn't work from the technical side of things, my bad. But wouldn't it be the most convenient to just silently check both ports for a valid API response when the user submitted the URL without any port?
And if that fails you can still display an error like we couldn't get a connection.
The options would work, but if you plan to add a check button anyways, you could also just put the check in the background and more or less auto configure the port if my thoughts make sense.

**Comment by jfwerner** [comment]
Bit late to the party but issue is still open so I'll jump in. I don't see a big issue with the default behavior. "Normies" will not think about ports and it will work as intended. People with other solutions will think about the port and put it in anyways.

Maybe a cleaner solution that the 2 buttons would be to automatically fill the 8123 port into the URL field when the users leaves it? That way it's apparent what the software will use, normies will leave it and techies might change it.

But with a self hosted solution like grocy, there won't be many people that don't know what a port is anyways. I would just force people to enter a port along with the URL. Pantryparty does this too I think
