### ISSUE TITLE
[2.0.0-beta01] Units in shopping list mixed, purchases wrong amount.

### ISSUE THREAD

**Issue by anha7196** [patzly/grocy-android#416]
Hi! 
In the shopping list the units are mixed for me if the product has different purchase and stock units. If for example i have burger buns, purchase unit packet, stock unit piece, i see pieces in the list, but packages if i enter the utem, but with the same number: So 8 pieses in the list and 8 packages in the item, and if i make the purchase, the pre-filled field is for 8 packages (64 pieces). 
Is this a bug or something setup wrongly on my side?

**Comment by MrJohnZoidberg** [comment]
Oh, thanks for reporting that, it's a bug! :)

**Comment by anha7196** [comment]
Great, tell me if i can help by testing something or something!
