### ISSUE TITLE
[v2.0.0-beta02] Invisible date picker in light theme

### ISSUE THREAD

**Issue by mstmob** [patzly/grocy-android#422]
The date picker in the purchase view does not show the date (the date is invisible).
However in dark theme the date is shown correctly as expected.
Probably the text color of the date picker element is white and not adapted when in light theme.

## Steps to reproduce
- Go to 'Purchase' view
- Type in some product
- Click on due date

### Expected
The date (DD, MM, YYYY) is shown in light theme and can be selected by scrolling over the date elements.

### Actual
The date elements are invisible; only the horizontal bars of the UI elements are shown but not the text inside the elements.

**Comment by MrJohnZoidberg** [comment]
Hi, which Android version do you have?

**Comment by mstmob** [comment]
Hi
Android Version is 7.1.1

**Comment by MrJohnZoidberg** [comment]
Hey, is it working in the latest beta or is it still invisible? I ask because Proguard can make trouble with the workaround i used and I want to make sure it didn't.

**Comment by mstmob** [comment]
Hey, for me it is working fine. :+1:  Thank you!!
