### ISSUE TITLE
Openfoodfacts integration doesn't seem to be working

### ISSUE THREAD

**Issue by jfwerner** [patzly/grocy-android#427]
> Client version 2.0.0beta02
> Server version 3.0.1

I assume that the idea behind the Open Food Facts integration would be only when adding a product: Scan a barcode, all info gets prefilled and it adds a new product to the server automatically with stock amount, categories and even calories etc maybe.

Thing is I can't seem to notice any effect of the DB when I scan things. Is it not working or have I not found the function? Apps like PantryParty seem to get the correct product name through OFF but not more like categories and stock units.

When going into Masterdata and products there is the for now grayed out barcodes field, is that the way you have it planned? So yeah that would be my suggestion, have it prefill everything, though I am not sure how easy it will be to use the category information. If the categories in OFF are sorted by "magnitude" it shouldn't be a problem to automatically create/use parent product "Essig", then create the subproduct "Balsamico Essig" or even the specific product.

**Comment by MrJohnZoidberg** [comment]
Hi, OFF is not implemented yet but it will come with v2.0.0 . Issue is #353.

**Comment by jfwerner** [comment]
ah sorry for the duplicate, searched for the wrong keyword

**Comment by MrJohnZoidberg** [comment]
I'm sorry too, I've just added "OpenFoodFacts" to the issue title so it's easier to find.👍
