### ISSUE TITLE
Sort/group shopping list by store

### ISSUE THREAD

**Issue by bramvrensen** [patzly/grocy-android#430]
As a user I would like to be able to sort/filter/group my shopping list on "store" so that I only see the relevant shopping list items for the store that I am in.

Since the introduction of Stores in Grocy one has the ability to sort/group the shoppinglist by Store in the web version. This allows me to see all items for a particular store on the shopping list. The android app sorts on product group without the opportunity to change this which, in my case, is holding me back from starting to use the app.

An even better solution might be to have the ability to make a separate list for each store and be able to transfer items from 1 list to the other but I guess that is more grocy related that the android app related.

**Comment by politas** [comment]
I'd just like to say that for me, grouping by store is a better solution than having separate lists per store.

**Comment by MrJohnZoidberg** [comment]
This functionality is still missing on the shopping mode page (note for me)
