### ISSUE TITLE
Add error message for 403 response "no permission"

### ISSUE THREAD

**Issue by nuovo10** [patzly/grocy-android#432]
I have grocy 3.0.1 server. It does not work to be able to add products to the purchase list from the stock view.
If I enter with the demo function, it works.
Greetings

**Comment by MrJohnZoidberg** [comment]
Not a problem anymore or why did you close the issue?

**Comment by nuovo10** [comment]
I have reinstalled Grocy and Grocy android and it works already. 

Thanks

**Comment by nuovo10** [comment]
I've been doing tests. The error disappears if the "edit master data" option is activated.
