### ISSUE TITLE
[Workaround] App can't find product & "Could not upload barcode"

### ISSUE THREAD

**Issue by Shredder5262** [patzly/grocy-android#433]
Testing out this Grocy 2.0 app, so far it is the most seemless experience when using grocy. However, i have an issue where i scan a product and it grabs the barcode and i see it on the app, I have to manually select the product (typing in the first couple of letters) ...then fill out the quantity and so on...once I click the grocy cart (I am in the purchase section, but it doesn't matter what section i am in I get the same result) I get the error message "could not upload barcode" 

In a perfect world...I would expect it to find the product of the barcode it just scanned, then i select the quantity and price  and store and done. 

But as of right now, it's not until i delete the barcode from the app (after scanning it) that i am allowed to upload/update the info in grocy...either remove the barcode number from being stored after it's scanned, or match it to the stored product in grocy

I see the error message in the debut logs as "Unexpected response code 400 for Http:// GrocyURL/api/objects/product_barcodes

I am using server version 3.1.0 ...which by the way The app states that version 3.1.0 is not supported but according to everything i have read and the fact that this app is running and connected to 3.1.0 would be untrue

**Comment by Shredder5262** [comment]
After doing some looking this may be similar to issue #431 , but not certain

**Comment by MrJohnZoidberg** [comment]
Yeah there is an issue on grocy side with version 3.1.0 because the API returns all barcodes as an interger which is a breaking change but unwanted. So zeros like here `000023345` will be cut of to `23345` and maybe there is a type issue too. I will look into it as soon as I have time.

**Comment by Shredder5262** [comment]
I'm finding this to be the case with many other things too.....

**Comment by MrJohnZoidberg** [comment]
Do you use the grocy Add-on for Home Assistant?

**Comment by MrJohnZoidberg** [comment]
I'm sorry, this is indeed a server issue (grocy/grocy#1564) and I'm afraid I cannot fix this in our app... Because the reponse for the "get all product barcodes" request contains the barcodes already without the zeros and I cannot get them in another way. So we will have to wait for a new grocy server version.

**Comment by MrJohnZoidberg** [comment]
Here is a [simple workaround](https://github.com/patzly/grocy-android/issues/431#issuecomment-899648931) for those who already have server version 3.1.0 and who have access to the server file system.

**Comment by Shredder5262** [comment]
a bug with grocy!?...impossible (sarcasm)....honestly can't say as I'm surprised. I'll hold my nasty comments there, don't want to get banned from here also.  
Thank you for providing a work around and a solution, this is the level of support I as an end user expect when raising an issue. Kudo's Sir

**Comment by Shredder5262** [comment]
Worked like a charm! :)

**Comment by Akaito** [comment]
I'm running gorcy server version 3.3.1 as part of Home Assistant running on a Raspberry Pi 4.  When using the grocy app on Android and attempting to purchase a product by scanning its barcode, I'm getting this same "Could not upload barcode" message.
