### ISSUE TITLE
Show tasklist overview in app

### ISSUE THREAD

**Issue by Shredder5262** [patzly/grocy-android#435]
It's my personal opinion that managing these sections via the app would not be necessary however i would like to be able to see who is assigned a chore on a given day without checking the web interface. This would be classified as a future enhancement.

**Comment by mcbloch** [comment]
Because of personal interest I'm working on the implementation of the task list. This could be made generic depending on the feature differences compared to chore lists and battery lists.

**Comment by ITguy3118** [comment]
Just circling around to this again to see if this was any closer to being implemented, I'm sure you both have plenty to keep busy, Simply curious is all.

**Comment by MrJohnZoidberg** [comment]
v2.0.0 will be released soon, after that I hope that I can work on these features. :)

**Comment by ITguy3118** [comment]
Sounds good, thanks for the feedback!

**Comment by MrJohnZoidberg** [comment]
The task list feature will be finished with v2.2.0, I've had to move it because I would like to finish v2.1.0 and don't have enough time right now to implement the missing pages. :)
