### ISSUE TITLE
Bug shopping mode

### ISSUE THREAD

**Issue by wurmmehl** [patzly/grocy-android#439]
Hey guys,

I think I found a bug in shopping mode. When you have completely shopped the top category the app automatically jumps to the purchased items section. 
I don't think that's how it should happen. If I would always buy the top category because it might just be all in order, then I always have to go back up to the unpurchased items.
Is that the way it's supposed to be?

many greetings

**Comment by MrJohnZoidberg** [comment]
Hey,
yes this is indeed not the way it's supposed to be... I hope that I can fix it.

Many greetings
