### ISSUE TITLE
Possible to add a counter to subtract from stock amount when consuming?

### ISSUE THREAD

**Issue by Shredder5262** [patzly/grocy-android#440]
This may exist already and i don't know it/see it/ or have it enabled, but when i go into the Consume option, it would be helpful to know after selecting a product how much is currently in stock then, when i increase the amount of pieces I want to consume, the total amount in stock decreases as i change the consume value.

so for example, I would select 
Ketchup
Ketchup has 32 Oz total in the bottle 
quantity unit is oz
Amount in Oz's either starts at 32 or has a separate text box stating 32 Oz. currently in stock 
The consume amount is whatever is specified in grocy as the default consume amount. If i were to increase the consume value, the total value is decreased  by the number entered (consumed) by the user.... so 32 Oz becomes 31 Oz, increasing the consume amount again by 1 , the total stock amount decreases  31 Oz to  30 oz, etc, etc. 

As it currently is now, I never know how much is currently in stock until i enter a number over the in stock amount. 

Does a counter like this exist already?  If not, can it be added on the next go around, please?

**Comment by MrJohnZoidberg** [comment]
That's the information which you can see after you tap on the small "information" icon on the bottom. But yes, that can be displayed always on the page.
I've added an info line below the product field, it contains the amount which is currently in stock. I think it is not necessary to change that during increasing or decreasing of the consume amount field value.

**Comment by Shredder5262** [comment]
Thank you Sir, Always appreciated, I assume that will be in a new package that's not yet available?

**Comment by MrJohnZoidberg** [comment]
You're welcome.

Yes, that's right, we will publish a new beta as soon as there is a new grocy server version with the bug fixes.
