### ISSUE TITLE
App not accepting valid acme cert

### ISSUE THREAD

**Issue by zdegraaf** [patzly/grocy-android#442]
I've setup a grocy instance using the linuxserver docker container and passed a certificate generated by Let's Encrypt/acme to the container and verified that it is working by logging in through Chrome on my phone. But no matter what I do, when I try to login using the app and https, I am consistently get the, "Certificate Missing" error. I've tried running it through my squid reverse proxy with a wildcard cert for my domain and a direct connection to the containers exposed https port, 9284, with both a wildcard and a domain specific cert and all have the same results. 

So far I love the app and grocy as a whole, but it is significantly less useful if I can't encrypt my traffic so that I can use the app outside my network.

**Comment by MrJohnZoidberg** [comment]
Did you try our latest beta version? Maybe you can also try to store the certificate in your Android user certificate store?

**Comment by zdegraaf** [comment]
I just installed the beta and it didn't help. So far I haven't been able to figure out what cert type I need for the android 11 certificate store.

**Comment by MrJohnZoidberg** [comment]
I'm sorry, I don't have an idea where the problem could be on the App's side... Let's encrypt certificates work for all people except you, and Conscrypt should do the rest for old Android versions. So I don't know what we can do here...

**Comment by MrJohnZoidberg** [comment]
If you have any questions or need more help, feel free to reopen this issue. Currently I cannot do anything for you, because I don't know where the problem could be.
