### ISSUE TITLE
Open Food Facts Integration

### ISSUE THREAD

**Issue by michucz** [patzly/grocy-android#461]
Hi and thank you a lot for your great work.

I saw in your latest release notes that you removed the setting for Open Food Facts because it isn't implemented yet. I wanted to ask if there is a rough timeframe you could give for when it might be implemented? If not, i understand and I will wait patiently.
Cheers

**Comment by patzly** [comment]
Hi, thanks for your question! We will release the last beta version today or tomorrow! There you will find the option again in settings.

**Comment by michucz** [comment]
Awewome, thank you so much for your quick answer

**Comment by michucz** [comment]
Hi,

I just installed the latest beta to try the openfoodfacts integration and i don't know if i'm missing something.
I activated the option in settings but it can't find any of the products i scan. I tried with the openfoodfacts android app and it had no problem finding them.

**Comment by MrJohnZoidberg** [comment]
How do you scan the products? The currently only way is to go to the purchase page and scan an unknown barcode (which is not in grocy database) and then a new page should open where the Product name  is prefilled if it was found on OFF and if the option is enabled.

**Comment by michucz** [comment]
Hi again,

thank you so much, i was just being a derp and didn't realize i should scan new items theough the purchase option. Works great, thank you once again.

**Comment by MrJohnZoidberg** [comment]
No problem :) We didn't write anywhere yet how to use OFF and I hope I can integrate it on the other pages too.
