### ISSUE TITLE
'Open' function

### ISSUE THREAD

**Issue by dexn** [patzly/grocy-android#465]
I feel that 'Open' is just as important as the Consume, Purchase, Transfer and Inventory functions. Would it be possible to add this? I've drawn an example of what I envision for reference. I included an option to transfer the product for cases like a jar from the pantry being opened and then stored in the fridge.

![Open_Grocy](https://user-images.githubusercontent.com/2460478/142510113-32dfef6b-d23c-477a-baf1-c48bbab4f9d2.png)

**Comment by dexn** [comment]
I was also thinking that if you didn't want to add another button to the main screen, an option could be to change the function of the 'Open' icon in the bottom bar of the 'Consume' screen. I was thinking it could be always visible and when selected it changes to the 'Open' screen I proposed above.

**Comment by MrJohnZoidberg** [comment]
Hi, the open option is available on the bottom app bar on the consume page. I'm sorry that you couldn't see the button, it is only visible if you enter a product which can be opened.

Another page for this is not necessary I think... The grocy server UI has the 'open' button on the consume page, too.

**Comment by MrJohnZoidberg** [comment]
Okay sorry, I just saw that I didn't understand you right. I will thought about it again but please let me some time for it :)

**Comment by MrJohnZoidberg** [comment]
Our app forms and pages are mostly the same as on the server interface for consistency. And to have "open" as a whole new page and with transfer option, it should be requested on the server first...
