### ISSUE TITLE
OpenFoodFacts implementation

### ISSUE THREAD

**Issue by maniche04** [patzly/grocy-android#466]
Hi,

Firstly,  the app is fantastic. Thank you.

I wanted to understand if and for what features is the OpenFoodFacts implemented? As a new user, I tried the Inventory feature to scan some barcodes and expected that the Product Name would be auto looked up. However, I had to put in the details manually. I thus wanted to understand what feature uses the integration with OpenFoodFacts.

Thanks,

**Comment by MrJohnZoidberg** [comment]
Hi, the Open Food Facts lookup is currently only implemented on the purchase page. It will be also available on the inventory page in the final v2.0.0 version.
