### ISSUE TITLE
Shopping list is unusable after using in offline mode

### ISSUE THREAD

**Issue by zagl** [patzly/grocy-android#47]
To test offline mode I opened the shopping list in the app and then I disabled wifi. I got a message that I am in offline mode. I checked some elements in the list. After enabling wifi again and reloading the shopping list It does not load anymore. The rest of the app is usable as before.

App Version is 1.5.0
Grocy Version is 2.7.1

**Comment by MrJohnZoidberg** [comment]
Oops, I can reproduce that – thanks a lot for reporting this bug!
I will try to fix it.

**Comment by MrJohnZoidberg** [comment]
Ah, I found it: The "start" command for the sync queue was missing...
