### ISSUE TITLE
[Home Assistant] Unerwarteter Antwort-Code - Code: 405

### ISSUE THREAD

**Issue by ondukil** [patzly/grocy-android#478]
Hi
i can´t get the App to work with Grocy on Home Assistant. After submitting all the needed credentials all i get is "Unerwarteter Antwort-Code  Code: 405
My Pixel 3a runs on Android 12
HA OS is  7.1
Grocy App Version is 2.0.0
Grocy HA Add-on Version is 0.16.0
![Screenshot_20220105-000147](https://user-images.githubusercontent.com/85987272/148137732-889c9181-84d7-41af-9d2d-10239bc75d6b.png)

**Comment by MrJohnZoidberg** [comment]
Is related to #249, I will investigate as soon as I have enough time.

**Comment by MrJohnZoidberg** [comment]
Hi @KTibow, you also had a 405 error with the alpha version of our app when trying to connect to your Home Assistant and you wrote that it was you local instance which was responsible for the error. In this issue there is also a 405 error and I don't know why, can you explain me further why there was such an error with your local instance?

@ondukil Can you explain how you use Home Assistant? Is is hosted in the cloud, only local on your LAN or do you use Nabu Casa?

**Comment by ondukil** [comment]
@MrJohnZoidberg I use nabucasa

**Comment by KTibow** [comment]
That was a while ago. Right now, I'm not running into this error anymore. I set the url to `https://[domain here].duckdns.org/api/hassio_ingress/[code here; this is confusing to get]`.

**Comment by MrJohnZoidberg** [comment]
We've released a new version, can you please try the connection again and send a screenshot from the error page if the issue still occurs? Thanks!

**Comment by ondukil** [comment]
Works fine now. Thank you for your effort to solve the problem.
