### ISSUE TITLE
Scanning a barcode for the 1st time while purchase/consume/inventory page is populated will still ask to choose the product

### ISSUE THREAD

**Issue by RaitaroH** [patzly/grocy-android#480]
Hello, thank you very much for the amazing app. One of the best apps I have seen and used.

Version 2.0.0

I have encountered a weird behaviour that I consider to be buggy. Consider the following steps:
1. add a product to the shopping list
2. go to shopping list
3. select item to open the `List Entry` bottom dialog which slides from the bottom
4. select the 🛒  icon
5. the `Purchase` dialog shows up with the item already populated. Nothing wrong so far
6. now click the barcode scanner to scan. I do this in order to associate a barcode with that product for the first time
7. at this point the `Choose product` dialog is shown instead of the barcode simply being linked to the product

We can do this another way:
1. go to `Purchase`, `Consume` or `Inventory` page
2. manually select a product first
3. now click the barcode scanner to scan. Yet again the `Choose product` dialog is shown.

To avoid this, I would have to go to `Purchase` and then use the scanner and choose the product. That is fine. Having a Shopping list, and choosing purchase from there makes sense and is intuitive; as such adding a barcode from an already populated dialog should work without asking me what product that is.

**Comment by MrJohnZoidberg** [comment]
Thanks for your detailed description!

**Comment by RaitaroH** [comment]
🚀
