### ISSUE TITLE
Add product to master data automatically when it isn't already and gets added to shopping list

### ISSUE THREAD

**Issue by Fxsch** [patzly/grocy-android#481]
Adding products to the master data first and then to the shopping list is annoying when you just want to add something to the shopping list quickly, it would be easier when the app would do that by itself.

**Comment by MrJohnZoidberg** [comment]
Adding a product to master data needs some data which you either have to fill out or set a default value in stock settings. The app cannot simply create a product just from a new entry in the shopping list. But you can enter a not existing product name as a new entry an the app will ask if you want to create a new product with this name.

**Comment by Fxsch** [comment]
This only works if you type in the name of the product and tap on enter on the keyboard but not when you close the keyboard and tap on the upload button. That's why I didn't know this.

**Comment by MrJohnZoidberg** [comment]
Oh thank you, this is a bug because on all other transaction pages the popup appears also if you tap on the green Floating Action Button. I will fix this :)
