### ISSUE TITLE
Application closes if phone is rotated after successful barcode scan

### ISSUE THREAD

**Issue by aldem** [patzly/grocy-android#487]
I tried to scan a barcode and had to rotate the phone to landscape mode, but once scan is completed application closes when I rotate it back to portrait mode. Actually it looks like that any double rotation after successful scan leads to this issue.

This problem is reproducible on two different phones - Samsung Galaxy Note 8 (Android 9) and Pixel 6 (Android 12), app version 2.1.0 - thus I believe it is not device or OS related.

### Steps to reproduce:

- Choose "Purchase"
- Activate barcode scanner
- Scan something
- Rotate phone and make sure orientation changes
- Rotate it back

**Comment by MrJohnZoidberg** [comment]
I cannot reproduce the bug, can you enable logging in the app settings (debugging category) and repeat the crash? After that, there is maybe something meaningful for me in the log.

**Comment by aldem** [comment]
Sure, see attached file please. Also note that this only happens if scanner is invoked from Inventory or Purchase, not if you invoke it directly from start screen.

[Grocy-qr-crash.txt](https://github.com/patzly/grocy-android/files/7982698/Grocy-qr-crash.txt)

**Comment by MrJohnZoidberg** [comment]
I tried to prevent the crash, but it may still occur (because I could not find the source of the problem). Please reopen the issue if it is still not fixed after we've released a new version.
