### ISSUE TITLE
Improve recognition of online/offline changes

### ISSUE THREAD

**Issue by Gitieyup** [patzly/grocy-android#492]
In different versions of the app (2.0.0-beta05, 2.0.0 and 2.1.0), it appears that when disconnected from the home network. The shopping list cannot be modified in offline mode in shopping mode to cross off done groceries which have been gathered/purchased in the shop. The shopping list and all is however present in offline mode to help remind which items to  purchase.

Rather seems to be a lack of a feature then it to be a bug as the shopping list is accessible in offline mode as told in the description of this Github page.

Is there the possibility of implementing a offline feature so that items when crossed off the shopping list in shopping mode, it will remember that in offline mode and then update it when connected to the home network?

Currently to me the way groceries can be handled now are the following when back from shopping and connected to the home network (shopping lists always made based onthe "Add missing products" feature);

1. Individually selecting the groceries in the shopping list and adjust the amount which have been purchased.

2. Selecting purchase all and then dismissing/skipping the groceries which have not been purchased and adjust the amount which have been purchased.

3. Crossing off the groceries in shopping mode, then buying the groceries which are crossed off and deemed done and adjusting the amount which have been purchased.

If method 3 partially could be done offline (in the store/shop or on the way back) and synced to the server when connected to the home network. That would have our preference. Although If there are other methods, I would be interested to know. 

Thanks in advance and thank you for the wonderful app!

**Comment by MrJohnZoidberg** [comment]
Thanks for your long issue description. Method 3 is already possible when you are not connected to Internet (possible since version 1.4.0 of our app)... So, this is not working on your device? What does the app when you toggle the done status of an item on the shopping list page or shopping mode page while you're offline and what happens after you are back online? The app should display a message "Entries synced successfully" and the changes should be on the server.

**Comment by Gitieyup** [comment]
Hi There,

When offline, It just does nothing or so it seemed with default app settings. When I turned on the feature called "Show loading circle for all requests", I turned off Wifi once more and noticed that while it seemed to do nothing. The circle was being shown. So I decided to wait, which in turn after a few min prompted the message that it couldn't connect and it went into offline mode. This however made it possible to mark products as done and cross them off. Turning on the phone, with some delay the message prompted "Entries synced succesfully".

It became clear to me that the issue was that it took very long for the app to finally decide to go into offline mode and for the offline feature crossing off to become a possibility. Did a few runs with the app reinstalled 2.1.0 version via F-Droid app store and while it did differ. It took between 1-2,5 min for the app to go into offline mode.

Then I checked some other default settings being the the setting in Settings/Network "Loading Time-out". Default value is 30 sec, but as mentioned before, It took way longer in practice. First I went 10 seconds, which took around ~30 seconds. Then 5 seconds, which took 10-15 seconds for offline mode to be initiated. When I decided to go with the value of 1 second, the app kinda worked from what I saw the way I would want it to work. Being that after a few seconds, the app goes into offline mode, while also going online after a few seconds with connecting to the wifi home network.

Think I will try this also on the other phones that make use of the app and see how it goes but this might fix it with hopefully no drawbacks. The app seems way more responsive now when going offline/online.

Tested this on another android phone on a different version. Same issue but the same solution of lowering "Loading Time-out" to 1 sec seems to yield the same result. 

This change seems to have fixed our issue.

If anything else related to this comes to my attention I will let you know.

Thank you for your help, hope the above gave some info.

**Comment by MrJohnZoidberg** [comment]
Thanks for the details, it seems that the connection changes are not recognized properly by the app on your devices. But the offline/online behavior is a known issue and should be improved (for example it doesn't recognize that it is online again if the screen was turned of while the change occures on my devices). So I will change the issue title to something more general and hope that I can improve the behavior in the future.

**Comment by dominiczedler** [comment]
I hope the problems were solved in the latest nightly. The issue where the app displays an offline bar on the top if the network is already back again can remain - but now you can simply swipe down and if the request was successful the app will update its online state.
