### ISSUE TITLE
Request - Connection to External Accounts

### ISSUE THREAD

**Issue by megamays08** [patzly/grocy-android#493]
I looked through previous issues/requests and didn't see anything along these lines yet. To make the process of adding items to inventory after a recent purchase - being able to login to an external account to pull order details (items, cost, etc) over into the inventory would be amazing. For instance, I login to Grocy and connect my Kroger/Walmart/etc account to pull my order information over.

**Comment by MrJohnZoidberg** [comment]
Thanks for your request, but it is very unlikely that we will implement connections for specific stores. That would be very hard and time consuming and we would have to know the API details of stores we never heard of... Sorry.
