### ISSUE TITLE
Sort Shopping List by Location

### ISSUE THREAD

**Issue by blindm0use** [patzly/grocy-android#494]
**Please add "Location" sort filter in the shopping list**. **Location**, from what I understood, **can be used for** both:

1. Locating products in your stock/at home;
**2. Locating products in the shop for faster shopping.**

I am more of an option "2" user and want to have **an ability to sort my shopping list by location in the store**, so not roam around the store for remaining items. **This sorting method would help to complete a shopping list by single store's location/section.**
For eliminating conflicts of different stores being grouped into one shopping list, a single shopping list per store can be created, or in the future revisions **an automatic shopping list creation by store would be great to implement.**

For future purposes:
- "Section in the store" can be to added as for location in the store;
- "Location in stock" can be used for locating and tracking stock or purchased goods.

**Comment by patzly** [comment]
All of your requests belong to the [grocy server application](https://github.com/grocy/grocy/). Grocy Android only uses the official API to manage the data on your server, but all the features available in our app have to be supported by the API and therefore be implemented in the server application.

One already available feature you are looking for is called product groups. If you have stored a product group in each of your products, the shopping list shows the items grouped by product groups, so you can easily walk through the store and have all fruits and vegetables in one place for example.

For seperate stores you can easily create seperate shopping lists, that's what this feature is for. We don't understand what you mean with automatic shopping list creation, but we think this request also belongs to the grocy server application and not in this repository.

**Comment by blindm0use** [comment]
> All of your requests belong to the [grocy server application](https://github.com/grocy/grocy/). Grocy Android only uses the official API to manage the data on your server, but all the features available in our app have to be supported by the API and therefore be implemented in the server application.
> 
> One already available feature you are looking for is called product groups. If you have stored a product group in each of your products, the shopping list shows the items grouped by product groups, so you can easily walk through the store and have all fruits and vegetables in one place for example.
> 
> For seperate stores you can easily create seperate shopping lists, that's what this feature is for. We don't understand what you mean with automatic shopping list creation, but we think this request also belongs to the grocy server application and not in this repository.

Kindly thank you for the tip! Using product groups correctly now;)
