### ISSUE TITLE
Allow items to be marked as opened through the app.

### ISSUE THREAD

**Issue by kbehren** [patzly/grocy-android#495]
Similar to consume it would be nice to be able to mark a package as opened through the app.

Also thank you for this great app just started getting into grocy and this has been really helpful.

**Comment by MrJohnZoidberg** [comment]
Thanks for your nice words! You can open a Package already with our app, maybe you have to enable the feature in the grocy server configuration file. The button for open should be displayed next to the consume button on the product details bottom sheet when you are on the stock overview page or in the bottom app bar on the consume transaction page.

**Comment by kbehren** [comment]
Ohh ... found it now that you explained where it is.

I expected it in the consume button dialog, like on the website where consume has an "OK" and a "Mark as opened" button, my intention was to scan the barcode to mark it as open.

This will work just fine, it just confused me a bit.
