### ISSUE TITLE
Shopping List Batch Mode - Use default purchase unit

### ISSUE THREAD

**Issue by rscafidi** [patzly/grocy-android#497]
Hello, I'm not sure if this is already a feature and I just can't find it, but it seems that the Shopping List purchase mode does not use the default purchase unit.  Once my inventory for an item drops below the amount I set, I can add the missing items to the list.  When I mark the item as purchased while using the shopping list, it appears to be purchasing only the "missing" amount, not the amount that is purchased with the purchase unit amount.

For example, here's a scenario of my configuration:
Minimum Inventory Amount for Canned Black Beans:  12
Inventory unit:  Can
Purchase unit: Pack
Current Stock Amount:  10 Cans
Needed amount:  2 Cans
Default purchase unit to inventory conversion:  12

Current behavior with Shopping List Batch Purchase:
_Defaults to inventory unit, so in this example, 2 Cans_

Desired behavior:
In my opinion, it should do the math and select the minimum number of Purchase Units to which the conversion is >= the needed items.  So in the example above, it would record a purchase of 1 Pack of canned beans, adding 12 Cans to the inventory.

As I see it behaving now, the inventory will be off if I do a batch purchase.  I've tried to streamline our inventory process as much as possible, so we do not scan items into inventory, I only scan on consumption. I was hoping to take advantage of the batch purchase/shopping list feature.

**Comment by MrJohnZoidberg** [comment]
Sorry for the late reply. The behavior of this workflow is equal to the behavior on the grocy server (I've just confirmed this with a test). Please open an issue in the server repository if you think that the behavior is wrong, we just implement the behavior of the server in our app, so that there are no differences for users of both platforms.

**Comment by rscafidi** [comment]
Thanks for the response!  Would you be able to clue me in to the equivalent workflow within the web application?  On the web app, I only see "Add item to inventory" on the Shopping list page.  Before I make a post on the grocy server repo, I just wanted to confirm, does your app equate "Purchase done items" to the Grocy workflow of "Add this item to stock"?  Thanks again.
