### ISSUE TITLE
Hard to see which items are set as done on shopping list

### ISSUE THREAD

**Issue by Fxsch** [patzly/grocy-android#498]
On the shopping list, setting an item as done (by clicking on it, then on the checkmark or by swiping them to the right and clicking on the checkmark) only makes the font strike through but doesn't change the position or color, making it hard to distinguish from the rest

**Comment by MrJohnZoidberg** [comment]
I hope it is enough when items are greyed out. If you want to see only done or undone items, you can use the status filter for that.
