### ISSUE TITLE
Cannot edit quantity unit after adding new product to inventory

### ISSUE THREAD

**Issue by geeksrus** [patzly/grocy-android#499]
Originally posted here and author replied that this is an app issue: https://github.com/grocy/grocy/issues/1794

**Comment by MrJohnZoidberg** [comment]
> When I go into Grocy web (version 3.2.0) afterwards to edit the product, I am unable to edit the Quantity unit field under Edit Barcode. It is grayed out for me.

I think this is no app issue since you talk about the webpage... And you wrote that you can edit it in our app, so here should be no problem.
