### ISSUE TITLE
Mark stock as open

### ISSUE THREAD

**Issue by ManniDerLibero** [patzly/grocy-android#500]
I try to mark stock as open. But it looks like that it cannot be done via the app?
Even if I add '0.5', I won't be marked as open.

I am using:
grocy-android 2.1.0
grovy 3.2.

![2022-02-21 19_11_47-Window](https://user-images.githubusercontent.com/31795480/155008001-3c5a3408-8d72-4ac5-8e1c-378e960d06eb.png)
![2022-02-21 19_12_09-Window](https://user-images.githubusercontent.com/31795480/155008005-6db8d12e-6ab8-4fd0-bc48-caa71dcb68b1.png)
![2022-02-21 19_12_24-Window](https://user-images.githubusercontent.com/31795480/155008014-5e29e976-79a3-46a1-b620-957e07266643.png)
0

**Comment by MrJohnZoidberg** [comment]
![Screenshot_20220221_213207](https://user-images.githubusercontent.com/27244574/155022930-1fa5e4fa-8010-4ea4-9090-6199e4bc900f.png)

Hey, did you tap this button or the green one? If you didn't see the open button, we should display it somewhere else or add a beginner mode message.

**Comment by ManniDerLibero** [comment]
Thank you for the fast reply. It look like the correct button.
![image](https://user-images.githubusercontent.com/31795480/155279747-5fabe341-c028-4377-b7df-fb3352e05957.png)

But it removes the stock instead of marking as open.
![image](https://user-images.githubusercontent.com/31795480/155279836-5307c52c-5012-4bf4-a06f-e49c5098ceab.png)

![image](https://user-images.githubusercontent.com/31795480/155279902-89b77be8-6fca-4980-bfd1-7b4490e68562.png)

But if I click the button in grocy.
![image](https://user-images.githubusercontent.com/31795480/155280034-822c0060-4508-4a80-b581-12f06bc04084.png)

It is marked as open:
![image](https://user-images.githubusercontent.com/31795480/155280068-8240eed9-d296-447b-bb5b-0a4ba14f8ae5.png)

**Comment by ManniDerLibero** [comment]
I changed the barcode scanner and it works... 
If "ML Kit" is activated, the "mark as open" button will consume the stock.
If "ZXing" is activated, the button marks the stock as open.
Strange.

![image](https://user-images.githubusercontent.com/31795480/155590062-aebbc84c-85f3-4fac-9b66-99b52d2bd75a.png)

![image](https://user-images.githubusercontent.com/31795480/155590078-d64b942b-38c4-4d2a-b1dd-48909325d71a.png)

**Comment by MrJohnZoidberg** [comment]
I don't think that it has something to do with the scanner, instead the issue concerns the quickmode: I just saw that the open button acts like the consume button when quickmode is activated (so page title is blue). This is a bug and will be fixed.
