### ISSUE TITLE
Bestand am Lagerort

### ISSUE THREAD

**Issue by Matt77CHE** [patzly/grocy-android#502]
Wenn ein Artikel an mehreren Standorten gelagert wird, ist dies nicht als solches ersichtlich - es wird die Gesamt-Menge angezeigt.
Wenn ich einen Standort auswähle, werden mir nicht die Artikel von diesem Standort angezeigt.

**Comment by MrJohnZoidberg** [comment]
Die Übersicht über den Bestand von einem Produkt wird mit #403 eingeführt.
In der aktuellen Version sollte der Standort-Filter auf der Stockoverview Seite so funktionieren, wie Sie wünschen. Es sollten die Produkte angezeigt werden, die an dem ausgewählten Standort Bestand haben.
