### ISSUE TITLE
Standort ändern/hinzufügen

### ISSUE THREAD

**Issue by Babakz78** [patzly/grocy-android#503]
Beim Versuch, in der Android App einen Standort zu ändern oder hinzufügen zu wollen, stürzt sie ab

**Comment by MrJohnZoidberg** [comment]
Meinen Sie die Standorte in den Stammdaten?

Bitte aktivieren Sie in den Einstellungen das Debugging und schicken hier einen Ausschnitt des Logs (Screenshots oder copy&paste), nachdem Sie den Crash nochmal "durchgeführt" haben. Danke.

**Comment by MrJohnZoidberg** [comment]
@Babakz78 Können Sie sich bitte noch einmal Zeit nehmen und helfen, das Problem zu lösen?

**Comment by Babakz78** [comment]
-------- beginning of crash
03-16 09:55:43.357 11695 11695 E AndroidRuntime: FATAL EXCEPTION: main
03-16 09:55:43.357 11695 11695 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 11695
03-16 09:55:43.357 11695 11695 E AndroidRuntime: java.lang.RuntimeException: Missing type parameter.
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at com.google.gson.reflect.TypeToken.<init>(SourceFile:10)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.MasterLocationFragment$1.<init>(SourceFile:1)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.TasksViewModel$$ExternalSyntheticLambda9.onResponse(SourceFile:10)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$$ExternalSyntheticLambda2.onResponse(Unknown Source:6)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.CustomStringRequest$$ExternalSyntheticLambda1.onResponse(SourceFile:3)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(SourceFile:5)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(SourceFile:5)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:210)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7124)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-16 09:55:43.357 11695 11695 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)
03-16 09:55:50.265 11843 11843 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.

**Comment by MrJohnZoidberg** [comment]
Thank you, I can reproduce the issue with the F-Droid build, the app crashes with master location page and master quantity unit page. A fix will come with the next version.
