### ISSUE TITLE
Special characters in name of new product will be removed and/or deleted

### ISSUE THREAD

**Issue by ManniDerLibero** [patzly/grocy-android#505]
If I want to add new products to this beautiful software, special characters like "%" or "+" create a probem.

Example:
If name contains % -> Name is empty in next window
![image](https://user-images.githubusercontent.com/31795480/158584671-4b5814c2-3785-4b2d-bdee-cfcb86bbaabb.png)
Productname on "Produkt erstellen" screen is empty:
![image](https://user-images.githubusercontent.com/31795480/158584800-1df91ae5-056e-4821-9e6b-574c7fcbad72.png)

The "+" character:
![image](https://user-images.githubusercontent.com/31795480/158585387-ebb7cb31-3b98-40a3-82c9-5a12cf2bdc07.png)
->
![image](https://user-images.githubusercontent.com/31795480/158585427-215c210b-9683-40f1-9b2e-01511ebf1a26.png)

Some other characters:
![image](https://user-images.githubusercontent.com/31795480/158585552-b7c2e10f-b079-439d-9431-fa8174d0416a.png)
->
![image](https://user-images.githubusercontent.com/31795480/158585575-760b8d70-c953-4fb1-9048-3962b5c6f1aa.png)

Best regards

**Comment by MrJohnZoidberg** [comment]
Thanks for reporting!
