### ISSUE TITLE
App crash when adding or editing locations

### ISSUE THREAD

**Issue by danwdart** [patzly/grocy-android#506]
When I add or edit a location, the app crashes.
Will see if I can logcat if not reproducable.

Thanks

Version 2.1.1, grocy 3.1.3

**Comment by MrJohnZoidberg** [comment]
Thanks for reporting, the issue is already fixed (#503, was reported in German) for the next version. The problem was Proguard which required a new rule for not deleting necessary classes with newer Gradle versions.

**Comment by danwdart** [comment]
Thanks!
