### ISSUE TITLE
Selection of child products in purchase form

### ISSUE THREAD

**Issue by notEvil** [patzly/grocy-android#508]
Hi,

a couple months ago I started using grocy and I like the app a lot! There is one thing that could make a big difference for me:

In the purchase form, show a selection of child products in case the product is a parent product. Maybe "< name >" where < and > are buttons that switch to the previous/next child product.

My preferred approach to grocy is as follows. First add a parent product with a certain unit (for instance litre) to the shopping list. The amount represents the need. In the grocery I pick products based on preference or availability and mark the parent product as done. At home I go through the shopping list again and "purchase" child products using the prefilled forms. The child products of a parent product are usually of the same brand in different sizes and are tracked in whole numbers. For me this is the most efficient way of using grocy and the only thing missing is the selection of child product in the prefilled purchase form.

This approach maybe unusual and I'm aware that parent product isn't a "core" feature in grocy (products aren't inherently hierarchical).

**Comment by MrJohnZoidberg** [comment]
Hey, I will look into it as soon as I can find time for it. :)

**Comment by dominiczedler** [comment]
I hope the now implemented solution works for you! You can test the latest nightly build in a few minutes if you want.

**Comment by notEvil** [comment]
Just installed nightly but couldn't figure out how to get there. What I've tried:
1. disable own stock for parent product
2. add parent product to shopping list
3. from shopping list, purchase

opens the usual purchase form for the parent product.

**Comment by dominiczedler** [comment]
https://user-images.githubusercontent.com/27244574/210082901-005d3152-e598-4ca8-beaa-d7249211fb31.mp4

For me it's working, I don't know why your nightly doesn't do that...

**Comment by notEvil** [comment]
Thanks a lot! After a clean install it worked, don't know why it didn't before. Very much appreciated!!
