### ISSUE TITLE
Feature Request: Client SSL certificate

### ISSUE THREAD

**Issue by kitlaan** [patzly/grocy-android#510]
I was experimenting with mutual-TLS (aka client SSL certs), and looks like the app needs to be specially plumbed to load them for outbound connections.  (Similarly to what was done in the past to allow user-loaded server CA certs, looks like there's available plumbing to hook up user-loaded client certs.)

As it currently stands, the app does not offer up any client certs to the server.  Using android chrome, it'll ask which client cert to use to connect.

See:
https://blog.superautomation.co.uk/2016/04/implementing-android-keychain-to.html
https://android-developers.googleblog.com/2012/03/unifying-key-store-access-in-ics.html

**Comment by MrJohnZoidberg** [comment]
Thanks for the suggestion. :)

**Comment by kitlaan** [comment]
Another link -- the HASS folks are working on something: https://github.com/home-assistant/android/pull/2526

**Comment by dominiczedler** [comment]
We decided to close issues where we think that they will never be implemented. We have limited time for this project and thus we want to concentrate on the important things and enhancements which keep the app running.

You can always contribute with code if it is not too bad. :)
