### ISSUE TITLE
Implement latest server version changes

### ISSUE THREAD

**Issue by MrJohnZoidberg** [patzly/grocy-android#511]
### New feature: Notes and Userfields for stock entries

- [x] Stock entries can now have notes
  - For example to distinguish between same, yet different products (e.g. having only a generic product "Chocolate" and note in that field what special one it is exactly this time - as an alternative to have sub products)
  - Or for example to track ownership of stock items when sharing the fridge with your flatmates
  - => New field on the purchase and inventory (and stock entry edit) page
  - => New column on the stock entries and stock journal page
  - => Visible also in the "Use a specific stock item" dropdown on the consume and transfer page

### Stock

- [x] It's now possible to change a products stock QU, even after it was once added to stock
  - When the product was once added to stock, there needs to exist a corresponding unit conversion for the new QU
- [x] Product card, stock overiew and stock entries page optimizations regarding displaying prices:
  - [x] Prices are now shown per default purchase quantity unit, instead of per stock QU and when clicking/hovering, a tooltip shows the price per stock QU
  - [x] The price history chart is now based on the value per purchase QU, instead of per stock QU
- [x] New product option "Default consume location" (not mandatory, defaults to not set / empty)
  - When set, stock entries at that location will be consumed first
  - => This will be automatically taken into account when consuming from the stock overview page and all other places where no specific location can be selected
  - [x] => On the consume page the location is preselected in the following order:
    1. The new default consume location, if the product currently has any stock there, otherwise
    2. The products default location, if the product currently has any stock there, otherwise
    3. The first location where the product currently has any stock
- [x] New product option "Disable own stock" (defaults to disabled)
  - [x] When enabled, the corresponding product can't have own stock, means it will not be selectable on purchase (useful for parent products which are just used as a summary/total view of the sub products)
- [x] The price entered on the inventory page is now related to the selected quantity unit (like on the purchase page, was always related to the products stock QU before)

### Shopping list

- [x] Added a new shopping list setting (top right corner settings menu) to automatically add products, that are below their defined min. stock amount, to the shopping list (defaults to disabled)

### Chores

- [x] It's now possible to manually reschedule / assign chores
  - [x] Add model properties
  - [x] New entry "Reschedule next execution" in the context/more menu on the chores overview page
  - [x] If you have rescheduled a chore and want to continue the normal schedule/assignment instead, use the "Clear" button in the same dialog
  - [x] Rescheduled/reassigned chores will be highlighted with an corresponding icon next to the "Next estimated tracking date" / "Assigned to"

### API

- Endpoint `/stock/products/{productId}`:
  - [x] New field/property `current_price` which returns the current price of the corresponding product, based on the stock entry to use next (defined by the default consume rule "Opened first, then first due first, then first in first out") or on the last price if the product is currently not in stock
  - [x] The field/property  `oldest_price` is deprecated and will be removed in a future version (this had no real sense, currently returns the same as `current_price`)

**Comment by berrnd** [comment]
> => On the consume page the location is preselected in the following order: 
> [...]

Just wanted to add a maybe useful hint regarding that and the endpoint [`/stock/products/{productId}/entries`](https://demo.grocy.info/api#/Stock/get_stock_products__productId__entries):

The list there also already reflects that stock entries at the default consume location should be used first and additionally to that the response is ordered accordingly, each item now also has a `priority` property (higher number = use first).

Example:
https://test-7191uc00p0n1vsfl91zey9.demo.grocy.info
Default consume location = Candy Cupboard (id 4)
![grafik](https://user-images.githubusercontent.com/2161815/162566833-fd6d90d1-1007-40ee-bf29-2e4f2b276c45.png)

Even though the normal "consume rule" would result in that the first stock entry in the list would be consumed (because due first), the last one at the Candy Cupboard location now takes higher precedence:

https://test-7191uc00p0n1vsfl91zey9.demo.grocy.info/api/stock/products/5/entries

```
[
  {
    "priority": "-1",
    "id": "81",
    "product_id": "5",
    "amount": "1",
    "best_before_date": "2022-05-05",
    "purchased_date": "2022-04-09",
    "stock_id": "6251573512dcf",
    "price": "1",
    "open": "0",
    "opened_date": null,
    "row_created_timestamp": "2022-04-09 11:53:09",
    "location_id": "4",
    "shopping_location_id": null,
    "note": null
  },
  {
    "priority": "-2",
    "id": "76",
    "product_id": "5",
    "amount": "1",
    "best_before_date": "2022-05-01",
    "purchased_date": "2022-04-09",
    "stock_id": "625156ef90cba",
    "price": "1",
    "open": "0",
    "opened_date": null,
    "row_created_timestamp": "2022-04-09 11:50:39",
    "location_id": "2",
    "shopping_location_id": "1",
    "note": ""
  },
 ...
]
```

**Comment by MrJohnZoidberg** [comment]
@berrnd Thanks for your help, this is indeed useful!
