### ISSUE TITLE
API key not working - com.android.volley.AuthFailureError

### ISSUE THREAD

**Issue by sym0nd0** [patzly/grocy-android#516]
Hi,
I'm just setting up Grocy now, using Home Assistant OS and it's all gone smoothly from that perspective.

I've just installed the Android app and tried to scan a QR code, both using my duckdns URL and Nabu Casa, but the app just errors out
`API key not working` `com.android.volley.AuthFailureError`.

![image](https://user-images.githubusercontent.com/55590428/162889528-c7b0bb50-90bf-4157-9ee0-721f2c1a0947.png)

Grocy Android 2.1.1
Grocy 3.2.0
Home Assistant core-2022.4.2
Grocy Home Assistant Add-on 0.17.0
Android 12

I've tried the manual Home Assistant flow to try and test if this is a local issue, which I assume it probably is, but I don't know what my Ingress Identifier is or where to find it in Home Assistant 🤦‍♂️, so can't progress.

Please let me know if you need any further information.

**Comment by sym0nd0** [comment]
Apologies, search didn't turn up anything relevant, hence opening the issue.

Latest update only became available to me in Play Store 7 minutes ago. I'll give it a whirl now.

**Comment by MrJohnZoidberg** [comment]
Great to hear that it worked for you!
