### ISSUE TITLE
Consume partial amount

### ISSUE THREAD

**Issue by rynas** [patzly/grocy-android#52]
When 1 Pack (unit) of a Product is added. 0.5 Pack cannot be consumed. The Web interface though allows to do so. Do i miss something?

**Comment by MrJohnZoidberg** [comment]
Hi, that's right, we didn't implement that yet – but it will be possible soon.

**Comment by patzly** [comment]
Is this function really necessary? I would simply mark the product as opened and only consume it in Grocy when it is empty.
