### ISSUE TITLE
App crashes when adding a new product via purchase

### ISSUE THREAD

**Issue by mcbloch** [patzly/grocy-android#523]
Not trying to do anything strange. 

steps to reproduce:
1. press the purchase button on the homepage
2. scan a barcode
3. tap the 'Create new product' button
4. enter a name
5. choose the quantity unit
6. try to save the product 

and then it crashes. Logs can be found below. 

I did just update the app to the newest version. 2.2.0. (I uninstalled a local dev version and then installed the official one from the Google play store)
I also just upgraded the server from 3.1.2 to 3.2.0.

- I can successfully create a new item and a purchase for it in the web interface. 
- I can successfully create a new item in the app by entering a name manually instead of scanning the barcode and then creating a new item.
- It crashes for all the barcodes (3) i tried yet.
- Tried to clear storage and cache. Issue persists.

Android app logs
```
--------- beginning of crash
04-16 22:32:55.789 14379 14379 E AndroidRuntime: FATAL EXCEPTION: main
04-16 22:32:55.789 14379 14379 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 14379
04-16 22:32:55.789 14379 14379 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.lifecycle.LiveData.getValue()' on a null object reference
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.BindingAdaptersUtil.setErrorMessage(BindingAdaptersUtil.java:1)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.databinding.FragmentChooseProductBindingImpl.executeBindings(FragmentChooseProductBindingImpl.java:69)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:5)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at androidx.databinding.ViewDataBinding$7.run(ViewDataBinding.java:19)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at androidx.databinding.ViewDataBinding$8.doFrame(ViewDataBinding.java:3)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:1040)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:245)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8024)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
04-16 22:32:55.789 14379 14379 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by MrJohnZoidberg** [comment]
Thanks for the detailed report, this has been fixed already but the bugfix release will be released tomorrow I think. :-)

(Duplicate of #518, I appreciate your log and the steps to reproduce it, but you can look for other (closed too) issues first to save yourself the time for writing)

**Comment by mcbloch** [comment]
> Thanks for the detailed report, this has been fixed already but the bugfix release will be released tomorrow I think. :-)
> 
> (Duplicate of #518, I appreciate your log and the steps to reproduce it, but you can look for other (closed too) issues first to save yourself the time for writing)

Ah damn haha, I wrote almost exactly the same. I wrote it on mobile via the report functionality of the app, so I didn't have a look first, should have done that indeed. Thanks for the quick reply :)

**Comment by MrJohnZoidberg** [comment]
All fine, I invest much time for development of the app so the users can also invest some time for reporting ;)
