### ISSUE TITLE
Feature Request: Prefill Store for Batch

### ISSUE THREAD

**Issue by blubbel42** [patzly/grocy-android#525]
Hello, 
When shopping I'll do it in one store after the other. Wether i scan while shopping or later when putting the items in storage.
So It would be great if there could be implemented a prefill option for the "store" field. Like: I'm going to an aldi, mark anything I purchase now as "aldi", until I select the next store or stop shopping.
I can't think of how to explain it better. Please ask if clarification is needed.
Perhaps this belongs to grocy rather than to the app, I'm not sure

And: Thranks for this really great work!

**Comment by MrJohnZoidberg** [comment]
Thanks for your request, I will look how we can implement that. :-)

**Comment by dominiczedler** [comment]
https://github.com/patzly/grocy-android/assets/27244574/5a2f885d-b539-46df-8f50-d25fbb9061c7
