### ISSUE TITLE
Occasional crashes using Tor

### ISSUE THREAD

**Issue by CodeAssemblingChicken** [patzly/grocy-android#527]
Hello,
I am experiencing occasional crashes when using Tor/Orbot. It seems to happen at random and in any activity and is not (at least not immediately) caused by an input.
For reference, I'm using version 2.2.1 on CalyxOS Android 12. Here is the error log:

> 04-26 10:45:52.902  1252  1252 E AndroidRuntime: FATAL EXCEPTION: main
04-26 10:45:52.902  1252  1252 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 1252
04-26 10:45:52.902  1252  1252 E AndroidRuntime: java.lang.IllegalArgumentException: Receiver not registered: info.guardianproject.netcipher.proxy.OrbotHelper$1@28a6f45
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1555)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1797)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:769)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at info.guardianproject.netcipher.proxy.OrbotHelper$2.run(OrbotHelper.java:4)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-26 10:45:52.902  1252  1252 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

I could imagine that it's linked to my setup and that you can't do anything about it, but I wanted to let you know anyway.
Thanks for your time, and for creating this beautiful app :)

**Comment by MrJohnZoidberg** [comment]
Thanks for pointing that out, but I'm really afraid there's nothing we can do about it... We simply use OrbotHelper to start the Tor connection if not started just like the manual of the module describes. And I couldn't find the error with this module on the Internet and couldn't find methods in it to prevent the error.
Sorry :-)
