### ISSUE TITLE
shopping list: one tap/one swipe to mark entry as done

### ISSUE THREAD

**Issue by 234567432** [patzly/grocy-android#529]
Is it possible to change the "right swipe" behaviour of shopping list items to mark them done immediately instead of tapping them again (maybe via settings)? Or change the tapping behaviour (short tap: mark as done; long tap: open current submenu)?
When I am shopping, I am always trying to catch my children and having the shopping list on the smartphone in parallel, so time is of the essence

**Comment by MrJohnZoidberg** [comment]
Hey, for this behavior there is already the page "shopping mode" which you can reach through the menu on the normal shopping list page or by long tapping on the "shopping list" info on the start overview page of the app. You can even reach it with a menu entry on your home screen if you set it up in the app settings. And the shopping mode also has an own settings category where you can tweak some options for it. I hope this helps. :-)
