### ISSUE TITLE
Feature Request: Local Network setting

### ISSUE THREAD

**Issue by Kurisutian** [patzly/grocy-android#53]
Here's a request I find very handy to have in an app like this which I also found eg. in the official Home Assistant app: Distinguish between local and remote network. 
In the HA app I can tell the name of the local WiFi network and once connected the app uses the local address. Whenever I am not connected to that local WiFi network I can enter a second address (usually the one exposed to the internet) and the connection will be established through this address. 
This way, whenever being at home it's possible to run all local and no internet connection is required at all. Comes in handy if the WAN connection is failing and you still need to adjust things. Also in the case of using the app at home it does not make much sense to have traffic from the grocy installation send to the internet and get it back into the same network to the app. 

It would be awesome to integrate this option (perhaps similar to how the HA app has integrated it?). 

Thanks a lot!

**Comment by edenhaus** [comment]
You can also use Pi Hole (or any other dns resolver; Ad Guard Addon exists for Hassio) for your home network. So you can point the extrernal url directly to your local device, which is running grocy.
So the traffic is not leaving your network and in case of Pi Hole or Ad Guard you can also block ads network wide.

**Comment by cyberjacob** [comment]
As Eden said, the easiest way to do this is with Split-DNS, whereby something (whether Pi-Hole, or another DNS server) gives a different result based on if you're at home or away. The other method would be to turn on Hairpin NAT on your router. Settings for this vary between routers, however Google should be able to help you.

**Comment by MrJohnZoidberg** [comment]
Hey, I've decided to close this issue because like other people wrote here, there are other solutions for this. IMHO for me it is too much work to implement that and there would be additional Android permissions needed (where other users could worry about).
Additionally, for most users this feature won't have any benefits (IMHO).

**Comment by HydrelioxGitHub** [comment]
If anyone know how can I configure my nginx proxy manager to avoid certificate issue, or where can I find help, please contact me !
