### ISSUE TITLE
[Bug]: Only Standard purchase unit possible.

### ISSUE THREAD

**Issue by Mega-Cookie** [patzly/grocy-android#530]
I have 3 QUs for eggs:
pieces, 6 piece carton and 10 piece carton with according conversions.

Standard stock unit is pieces and and standard purchase unit is 6 piece carton.

On the webpage I still can choose 10 piece carton. On the app it's not possible.

**Comment by MrJohnZoidberg** [comment]
I tried it with your example and I have the 10 piece carton in my list.


![Screenshot_20220430_015136](https://user-images.githubusercontent.com/27244574/166081600-67cf11b8-d180-4959-90fd-b4d288ef9ecc.png)

Which conversions do you have? I have these (the piece to 6 peace carton conversion is the factor 'purchase to stock' in the product I think):
![Screenshot_20220430_015309](https://user-images.githubusercontent.com/27244574/166081679-7f1ab2b8-48ac-4388-8ea5-7a6a56311816.png)

**Comment by Mega-Cookie** [comment]
Maybe because I set the conversions for the QU not the product (as is mentioned in https://github.com/patzly/grocy-android/issues/490)
Here is how is for me:

![Screenshot 2022-04-30 115821](https://user-images.githubusercontent.com/70167487/166101381-2811f3ec-b9c8-4c84-adfa-f595a4f185e0.jpg)

![Screenshot 2022-04-30 115935](https://user-images.githubusercontent.com/70167487/166101388-473408c7-e66c-4806-be18-c28b9a78e47d.jpg)

![Screenshot 2022-04-30 115946](https://user-images.githubusercontent.com/70167487/166101392-839b97d3-8836-4d50-905b-e93d0f9115b1.jpg)

![20220430_120030668_3033](https://user-images.githubusercontent.com/70167487/166101481-fc868b1f-95d0-4978-b601-25d0a8cb4c69.jpg)
