### ISSUE TITLE
Shopping list keyboard sight obstruction 

### ISSUE THREAD

**Issue by zunami** [patzly/grocy-android#532]
Hello!

I like to use your app to organize my household privately.

I find but when entering the purchases hindering as the buttons are arranged because the keyboard is automatically in the way.

I always quickly enter what we need e.g. like here bananas. but I can not immediately record them because I first have to try to get the keyboard away.

Example attached
![Screenshot_2022-05-05-08-37-40-61_ded3d01f237383c8e0209ace216d3455](https://user-images.githubusercontent.com/4697822/166874362-3ddfa168-e910-4e11-bad5-d94c9db8ecbd.jpg)
![Screenshot_2022-05-05-08-37-50-90_ded3d01f237383c8e0209ace216d3455](https://user-images.githubusercontent.com/4697822/166874370-b39377bd-3e21-42d4-a7c9-aca2fd5997a6.jpg)

**Comment by MrJohnZoidberg** [comment]
You just have to tap twice on the Enter key on your keyboard and the item will be added. There will maybe soon be a better technique for the bottom buttons while the keyboard is open.
