### ISSUE TITLE
Feature Request: Enable continuous update also in "normal" shopping list mode

### ISSUE THREAD

**Issue by schnillerman** [patzly/grocy-android#533]
It seems that **continuous updates / sync** with the server are only activated with _shopping mode_ active inside _shopping list view_.

In my personal opinion, continuous sync makes sense also without _shopping mode_ active since shopping lists might be processed (during shopping) by someone else even while administrating the list.

Also, adding items to the list while someone else is shopping should be synchronized immediately (but this is already implemented I think).

**Comment by MrJohnZoidberg** [comment]
While you are administrating the list, the app automatically reloads the data for the shopping list page if there were changes during staying on an edit page. So the app does something like that:
1. *(user opens shopping list page)*
2. app refreshes data if there were changes on the server regarding shopping list data
3. *(user taps on an item and navigates to the edit page of it, then saves changes and navigates back to shopping list page)*
4. app refreshes data if there were changes on the server regarding shopping list data

So on every shopping list page load, the data is refreshed if necessary. In my opinion, there is no need for a continuous update process on that page. If you want to stay on this page and want to see updates, then I think you should instead open the shopping mode page.
