### ISSUE TITLE
Warn, but allow attempts to change default qty unit

### ISSUE THREAD

**Issue by CloCkWeRX** [patzly/grocy-android#535]
1. Add a product, with inventory: 0/never purchased, via grocy itself
2. Try to change the unit

Expected:
You can, as never purchased.
UI should warn me, but still let me try if I am sure

Actual:
You can't. UI bocks you.

**Comment by MrJohnZoidberg** [comment]
Is already implemented for the next release, the unit change will be always possible for server v3.3.0+ and if a conversion for the unit exist.
