### ISSUE TITLE
Product images

### ISSUE THREAD

**Issue by CloCkWeRX** [patzly/grocy-android#536]
1. Scan a product, with lookups from OFF enabled

Expected:
I'm suggested the front product image to use, if available.

Actual:
I'm not prompted.

Related: #507

**Comment by MrJohnZoidberg** [comment]
Not related to #507 because the other issue is about internal barcode details from grocy and not OFF as I described there.

I will change the title to something more general, because images are generally not supported in our app yet.

**Comment by martin-braun** [comment]
@dominiczedler I think a first good start would be to display product images in the pop-out when opening them from the inventory list or product master data list.

I took the time to add a couple of product images (backside of Fix products, i.e. Maggi Fix, Knorr Fix) to have access to their guides in the supermarket to get the missing ingredients in case I have the Fix product itself at home. So this would be very handy.

I understand that I could use the receipt feature for that, but it seems overkill for me at the moment. I also understand that image support is a huge topic, so my hope it that we can get at least view support for images on the first glance.

Thanks so much! :)

**Comment by Londoneye02** [comment]
Having the pictures in the shopping list would be also very helpful while you are in the supermarket
