### ISSUE TITLE
App crashes in dark mode

### ISSUE THREAD

**Issue by Kurisutian** [patzly/grocy-android#54]
Hi there,

I am currently having trouble to switch to dark mode. As soon as I do, the app crashes and cannot be opened again. I have to delete all data from it through the phone to start over and have to set it up all again. Did check it multiple times but it was always the same.

Let me know what information is needed, so I will be able to send them to help. 

Thanks!

**Comment by MrJohnZoidberg** [comment]
Hey,
Thanks for reporting this bug!
Which Android Version is on your phone?

**Comment by Kurisutian** [comment]
It's Android 8

**Comment by patzly** [comment]
Do you mean you try to switch to dark mode in the **app settings** or with a **global system** dark mode?

**Comment by patzly** [comment]
We identified the problem, but we'll need some time to solve it.

**Comment by MrJohnZoidberg** [comment]
This bug was hopefully fixed in 0c93cbdd1b05ba59ee34a9f8be4e3905ed4a84e5.
Please reopen this issue if the crash still occurs with the new version, which will be released soon.
