### ISSUE TITLE
Hint for button on main page

### ISSUE THREAD

**Issue by vaderf** [patzly/grocy-android#540]
Hi grocy-android team,

First thank you for developing and maintaining this app!

The scanner shortcut from the main/front/welcome page of the app (the scanner button at the bottom of the screen) is very useful but can only be used for consuming an item from the stock/inventory. It would be great if we could use it for adding an item like in the inventory menu. Ideally, I would see an inventory icon next to the consume icon to let the user decide to add or remove the item. Alternatively, an option related to scanner in parameters could be added to set the default behavior of the scanner shortcut either to consume or to add items.

Thank you for considering this.

**Comment by MrJohnZoidberg** [comment]
Thanks for your report, purchase is already possible by long tapping on the button. :-)

We should add a hint for that somewhere...
