### ISSUE TITLE
Scanner to upload dater

### ISSUE THREAD

**Issue by adtwomey** [patzly/grocy-android#546]
![Screenshot_20220523-212655_MyNetDiary](https://user-images.githubusercontent.com/14849762/169809646-dbb37bca-ed14-45ca-93f7-ec7ed221f73b.jpg)
I have a app, don't kown how it works or how it gets its info but when add a product by a scan will be nice to have this information saved on the grocery server. I have the unlocked grocery anyway we can upgrade this.

**Comment by adtwomey** [comment]
![16533055034944655915596065059588](https://user-images.githubusercontent.com/14849762/169810116-de069e62-d15f-4f48-b92b-1747772a6608.jpg)
![16533055202114404982692854018891](https://user-images.githubusercontent.com/14849762/169810154-5c237835-db6d-4b17-aede-e4c33beb1683.jpg)

**Comment by MrJohnZoidberg** [comment]
What information do you mean? Just the calories or all from your screenshot? Every detail of a product which should be saved must be supported by the grocy server... So most of the values from your screenshot cannot be stored on the server because there are no fields for them in a product object.

**Comment by MrJohnZoidberg** [comment]
Please reopen the issue if you want to provide more information.
