### ISSUE TITLE
Self-signed certificates not working

### ISSUE THREAD

**Issue by Gitoffomalawn** [patzly/grocy-android#551]
### Setup
I'm running the [Grocy docker version](https://github.com/linuxserver/docker-grocy) using the `latest` tag, which is currently on version 3.3.0. In order to reach it over HTTPS, I'm using [Nginx Proxy Manager](https://github.com/NginxProxyManager/nginx-proxy-manager) with a self-signed certificate for a non-routable domain (`.lan`). The root certificate is imported in my Android certificate store as a trusted root, and works with all other apps for other services hosted internally in a similar manner. I'm trying to connect to the Grocy server using the Android app (version 2.2.1) with a generated API key.

### Issue

I can't connect to the Grocy Android app to my self-hosted server which uses a self-signed certificate. I keep getting the following error:
![Screenshot_20220528-230137](https://user-images.githubusercontent.com/25043070/170842864-03d11c44-ee78-4ae0-9978-aea693966161.jpg)

I can reach the Grocy server just fine over HTTPS when using a browser. However, connecting using the app produces the error above. Connecting through HTTP using the app also works just fine. The error message leads me to believe the error is the result of a component used by the app.

**Comment by MrJohnZoidberg** [comment]
Hey, it seems that the hostname from the first part of the error message ("hostname *** not verified") doesn't match the Common Name (CN) or an subject alternative name (subjectAltNames) in the part below that message.

The hostname like you are using it must be given in the certificate either as CN or one subjectAltName.

Hope this helps.

**Comment by MrJohnZoidberg** [comment]
You can reopen the issue if you still have problems.
