### ISSUE TITLE
Improve date formats

### ISSUE THREAD

**Issue by enjunear** [patzly/grocy-android#555]
The date picker and the display of dates is generally in the format `mmm, d yyyy`.
This format predominantly only makes sense to inhabitants of very few nations on earth.

I'd suggest implementing an option to use a more sensible date format for those that wish to.
Either `dd-mm-yyyy`, or RFC/ISO format `yyyy-mm-dd`.

**Comment by MrJohnZoidberg** [comment]
I don't know which version you are using, but I can't reproduce your problem:

<img src="https://user-images.githubusercontent.com/27244574/197547572-edf5b475-5306-4d84-81e4-6e2b39ba6382.jpeg" height="250"><img src="https://user-images.githubusercontent.com/27244574/197548417-228ff5d0-06e8-439c-8759-dcf3bb12ffa7.jpeg" height="250">

<img src="https://user-images.githubusercontent.com/27244574/197548913-418c02bf-7fa0-48a7-99ae-a02f3243d3ce.jpeg" height="80"><img src="https://user-images.githubusercontent.com/27244574/197549064-a021d856-1c61-4de8-9100-4ab5b92b6e63.jpeg" height="80">


Or with activated keyboard option in behavior settings:

<img src="https://user-images.githubusercontent.com/27244574/197549655-123e9fbc-1186-4cdb-96e9-db91214d72ec.jpeg" height="180"><img src="https://user-images.githubusercontent.com/27244574/197549783-483f6135-c5f1-4123-81ba-e83abaf621b6.jpeg" height="180">


> The date picker and the display of dates is generally in the format mmm, d yyyy.

So I cannot understand where you see such behavior. The app displays dates in the current locale's format and the input changes also dynamically depending on your locale or language.
