### ISSUE TITLE
Server version 3.3.1

### ISSUE THREAD

**Issue by Akirainblack** [patzly/grocy-android#558]
Any idea when you might start supporting server 3.3.1?

Thank you,

**Comment by patzly** [comment]
Hi, please make sure you understand the following (also helpful for other Grocy Android users who read this issue):

- We will publish an update as soon as we have time, currently we are both studying and have exams and other stuff to do.
- You have the full control over your server – If you know that our App wasn't updated yet to support the new grocy version (read the changelog for that), just don't update your grocy server application and wait for us to publish the update which supports the new version, even if that takes some weeks or months. Every major grocy update means that we have to implement changes of the API, this simply takes time. 
- Nevertheless, if you already have updated your server application, a warning appears in the app. This warning can simply be ignored, just read the message. It says that a minor lift of the version (e.g. x.x.0 to x.x.1) doesn't make any difference for our app. You can simply tap on IGNORE and that's it – The app should work normally.

But please make sure you follow the second advice next time, that's the best.
