### ISSUE TITLE
Chores reschedule bug

### ISSUE THREAD

**Issue by grossqx** [patzly/grocy-android#564]
I am using app version 2.3.0 ( receiving beta releases )
Android 12, Pixel 4a 5g

After I tried to reschedule a chore it crashed at the moment I pressed the round cloud icon button to submit.
Now when I just enter the chores page it crashes right away every time.

I'll be glad to provide any additional information if needed. Thanks

**Comment by grossqx** [comment]
From what I can see in the web interface, the chore did reschedule. But it caused an issue in the app and in another grocy-related application - grocy-custom-component for home assistant. I had this issue there before for different reasons: (https://github.com/custom-components/grocy/issues/238) 
I believe this happens because of invalid date format. Maybe it is unrelated, but hope it is helpful.

**Comment by MrJohnZoidberg** [comment]
Thanks for reporting! Is fixed now, there were also issues with chores rescheduling which have time tracking enabled, which is also fixed now.
