### ISSUE TITLE
No user account change available in app for mobile

### ISSUE THREAD

**Issue by Terrassa5** [patzly/grocy-android#567]
We've installed Grocy in Home Assistant and created different user accounts for each family member. All family members have installed Grocy app on their Android cell phones. Chores are assigned to the different accounts. In the Grocy app installed in our cell phones there's no way to select the user so when someone marks a chore as done from their cell app it appears as executed by user admin instead of the correct username.

**Comment by MrJohnZoidberg** [comment]
On your grocy server you create an API key for the currently logged in user, so you just have to generate API keys for all users and the app will use the right account.
