### ISSUE TITLE
Label not printing when "purchasing" a product

### ISSUE THREAD

**Issue by jtommi** [patzly/grocy-android#570]
When purchasing a product, grocy doesn't call the webhook to print the corresponding label.

I tried this with:
- grocy 3.3.1
- grocy-android 2.2.1 and 2.3.0

I also tried in the grocy server settings to set LABEL_PRINTER_RUN_SERVER to false but that didn't help.

**Comment by wedganw** [comment]
Is there a plan to implement this feature in the near future?

It would be really useful for those, wo use the mobile app e.g. for things in the freezer.
As a workaround I use the purchasing interface through the web page but it isn't realy ideal to use.

**Comment by MrJohnZoidberg** [comment]
Maybe we can implement this, since it shouldn't be too much work. I just didn't know that there is an API call to print something.

![image](https://user-images.githubusercontent.com/27244574/208551505-54cca46b-4019-492c-94dc-dd66860d0b58.jpeg)

**Comment by jtommi** [comment]
This feature is what's currently holding me back from starting to use Grocy and Grocy Android, since the Grocy webinterface isn't great for "purchasing" products, especially on mobile.

I have no knowledge in Java, but I have knowledge in APIs in general and have a label printer setup in Grocy so I'd be glad to help test this.

**Comment by wedganw** [comment]
Small update:

Until this feature is fully implemented, I've tried adding it myself. My knowledge of java and app development isn't really good, but I managed to get it working. When purchasing it prints out the label acording to the choises on product level in groy.  Printing labels from the stock menu is also possible.
Anyone interested in this feature can check out my fork of this project. The code is probably not the cleanest, but for me it's enough for now. So please don't hate :D

If you have any questions, I'm happy to help

**Comment by dominiczedler** [comment]
Could someone test the implementation in latest nightly please?

**Comment by jtommi** [comment]
I downloaded [Grocy-Android-master-20230105.apk](https://github.com/patzly/grocy-android/releases/download/nightly/Grocy-Android-master-20230105.apk).
I'll give it a try in the next days

**Comment by jtommi** [comment]
A bit late, but I tried it now in the latest release 3.3.1 and with the server v4.0.2 and it works.
@dominiczedler Thank you
