### ISSUE TITLE
Allow negative keyboard input value (-1) for due dates when editing products

### ISSUE THREAD

**Issue by towadroid** [patzly/grocy-android#576]
Currently when editing products (in the master data) it is not possible to set the default due days (and default due dates after freezing) to -1 to indicate that the product is never overdue.

**Comment by patzly** [comment]
For me it is working on the demo server and on my own as it should🤷🏻‍♂️
Can you please describe what you mean with "not possible"? If you mean typing with keyboard then yeah, you need to tap on the arrow-down icon on the right.

**Comment by patzly** [comment]
You also could upload a screen recording so we can understand your procedure.

**Comment by towadroid** [comment]
> If you mean typing with keyboard then yeah, you need to tap on the arrow-down icon on the right.

Thanks! I was too focused on the keyboard and didn't even notice the arrow icons. Although slightly unintuitive that you can't input the minus sign, it works for me as well!
