### ISSUE TITLE
The Notes section of the Purchase and Inventory add screens are limited to 10 characters

### ISSUE THREAD

**Issue by Razseal** [patzly/grocy-android#577]
Repro steps

1. open app
2. select inventory or purchase
3. scan barcode or select an existing product
4. scroll bottom of the screen
5. select note section
6. Note text box is limited to 10 total characters

This same issue doesnt seem to happen on the shopping list when trying to add an item.

**Comment by MrJohnZoidberg** [comment]
Thanks for reporting!
