### ISSUE TITLE
Prevent adding recipe ingredients with a unit for which no conversion exists

### ISSUE THREAD

**Issue by Lykos153** [patzly/grocy-android#580]
Yesterday I added an ingredient to a recipe and used a unit for which no conversion exists, which lead to [this problem](https://github.com/grocy/grocy/issues/2013). The web UI already blocks such actions and as of https://github.com/grocy/grocy/commit/e8f76e5694f2defb69435bccfaeb8de96870322c, it is now forbidden by the API as well. It would be great if the app would only show the unit options for which a conversion exists.

**Comment by dominiczedler** [comment]
I think this is fixed now as I added other fixes (#612) which should prevent displaying other units in the selection bottom sheet without conversions. You can reopen the issue if there is still a problem with that.
