### ISSUE TITLE
Crash when adding to shopping list

### ISSUE THREAD

**Issue by Mats-Kalleberg** [patzly/grocy-android#582]
Tried to add a product to the shopping list and it crashed

**Log:** 
--------- beginning of main
10-03 15:09:47.901 19565 19565 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
10-03 15:09:47.901 19565 19565 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
10-03 15:09:50.102 19565 19565 E art     : invalid stream - problem with parameter iterator in /data/app/xyz.zedler.patrick.grocy-1/base.apk for method void xyz.zedler.patrick.grocy.generated.callback.OnItemClickListener.onItemClick(android.widget.AdapterView, android.view.View, int, long)
--------- beginning of crash
10-03 15:09:50.125 19565 19565 E AndroidRuntime: FATAL EXCEPTION: main
10-03 15:09:50.125 19565 19565 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 19565
10-03 15:09:50.125 19565 19565 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to load quantity units from product
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.QuantityUnitConversionUtil.getUnitFactors(QuantityUnitConversionUtil.java:19)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.ShoppingListItemEditViewModel.setProduct(ShoppingListItemEditViewModel.java:9)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.databinding.FragmentShoppingListItemEditBindingImpl._internalCallbackOnItemClick(FragmentShoppingListItemEditBindingImpl.java:4)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.generated.callback.OnItemClickListener.onItemClick(OnItemClickListener.java)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:906)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.widget.AutoCompleteTextView.access$500(AutoCompleteTextView.java:91)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1202)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-03 15:09:50.125 19565 19565 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-03 15:10:09.935 29708 29708 E art     : invalid stream - problem with parameter iterator in /data/app/xyz.zedler.patrick.grocy-1/base.apk for method void xyz.zedler.patrick.grocy.generated.callback.OnItemClickListener.onItemClick(android.widget.AdapterView, android.view.View, int, long)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: FATAL EXCEPTION: main
10-03 15:10:09.935 29708 29708 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 29708
10-03 15:10:09.935 29708 29708 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to load quantity units from product
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.util.QuantityUnitConversionUtil.getUnitFactors(QuantityUnitConversionUtil.java:19)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.ShoppingListItemEditViewModel.setProduct(ShoppingListItemEditViewModel.java:9)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.databinding.FragmentShoppingListItemEditBindingImpl._internalCallbackOnItemClick(FragmentShoppingListItemEditBindingImpl.java:4)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.generated.callback.OnItemClickListener.onItemClick(OnItemClickListener.java)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:906)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.widget.AutoCompleteTextView.access$500(AutoCompleteTextView.java:91)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1202)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-03 15:10:09.935 29708 29708 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by MrJohnZoidberg** [comment]
Can you reproduce it everytime or was it a one time crash?

**Comment by Mats-Kalleberg** [comment]
It happens everytime, even if i wait to make sure everything is loaded in. it might just be the table im using

**Comment by MrJohnZoidberg** [comment]
It seems that your database has some products where quantity units are linked which don't exist anymore... Please check them out, I will fix the crash but cannot help you regarding the issue that some quantity units can't be loaded from the product you want to add to the shopping list.
