### ISSUE TITLE
Bug:  Stuck Notes

### ISSUE THREAD

**Issue by Garonic** [patzly/grocy-android#583]
- Grocy android app skips recording a bunch of information if
	    you add a new (not in products) item to a shopping list
	    along with a Note.  It won't let you make any subsequent
	    changes to the note, other than deletion.

**Comment by Garonic** [comment]
When the product is displayed in the shopping list:
- the name of the product "Summer Sausage" disappears
- the note appears where the name of the product should be "This is the product everyone's talking about.", and it appears in italics.
- a "1" appears in place of where the note should appear.

It is corrupted in the same way on the actual website (which is running the master version, not the release version).

**Comment by MrJohnZoidberg** [comment]
>  the name of the product "Summer Sausage" disappears
the note appears where the name of the product should be "This is the product everyone's talking about.", and it appears in italics.
a "1" appears in place of where the note should appear.

This would mean that the product wasn't created on the server during the workflow and thus the shopping list item only contains the note and amount as info. When you wrote the name of the new product into the shopping list form, did the app ask for an action how you want to create the new product?

**Comment by MrJohnZoidberg** [comment]
> It won't let you make any subsequent changes to the note, other than deletion.

I've fixed this bug, please answer the question above to help us spotting the other issue.

**Comment by dominiczedler** [comment]
I think we can close the issue for now and can reopen it if there is still a problem.

**Comment by Garonic** [comment]
Howdy there!

Sorry, I hadn't noticed your initial message in my email until now.

Anyhow, the problem happens if the user clicks outside of the drop down
menu.  So, the app doesn't get the opportunity to ask how to create the
product.

I guess I'll need to update the software on the server to identify if there
are any remaining issues.

Thanks.
