### ISSUE TITLE
Wrong ingredient amount in the recipe view

### ISSUE THREAD

**Issue by Quantum1337** [patzly/grocy-android#584]
Hello together,

I have the following recipe (created in the WebView):
![grafik](https://user-images.githubusercontent.com/36477626/194885827-5b16c7a6-f9d2-4303-8695-70a37f81e8da.png)

When i want to have a view on this recipe within the app, i get the following:
![Screenshot_20221010-161206_Grocy](https://user-images.githubusercontent.com/36477626/194887242-52e5f73b-7f59-4cc4-b3f7-9fd59b179553.png)

In detail an ingredient will look like this:
"Bestandsmengeneinheit" is "Kilogramm".

![grafik](https://user-images.githubusercontent.com/36477626/194887957-1aecdc8c-ec85-4d1e-8007-0519d57b8bcf.png)

There seems to be a problem with unit conversions.

Thank you !

**Comment by MrJohnZoidberg** [comment]
Mmh, which amount did you have in the input field above the ingredients?

**Comment by MrJohnZoidberg** [comment]
I've spotted the lines where the wrong amount was calculated :)

**Comment by Quantum1337** [comment]
Thank you for digging into this topic.

I think you are half way there. I have tested your nightly build. It seems that it isn't correct like it is now.

![Screenshot_20221012-193348_Grocy](https://user-images.githubusercontent.com/36477626/195410829-b4925ab9-acd7-4c71-b091-32eff9868e7d.png)

Whats missing is the conversion between the unit defined in "Bestandsmengeneinheit" and the unit shown in the recipe view.

For example:
For the ingredient "Langkornreis" a factor 1000 is missing. 
"Bestandsmengeneinheit" is kilogramm, unit in recipe view is gramm.

See "ME-Umrechnung" in the last screenshot of my first post.

Thanks for your work.

**Comment by MrJohnZoidberg** [comment]
Hopefully fixed with [7d4f01f](https://github.com/patzly/grocy-android/commit/7d4f01f6c7dd01210ec4d2331dcad917f6a3eea5).

**Comment by Quantum1337** [comment]
I have tested it again. It is better but not perfect :)

For the ingredient "Olivenöl" nothing changed. Its still 0.02 "Esslöffel". But after I change "Gewünschte Portionen" from 4 to X it is correct for the desired servings. When i then change it back to the base servings it is also correct. When i go to the recipe overview and make an update (pull the thump down) the amount will be reset to 0.02. Maybe it has something to do with the "Umlaut" ? Its the only unit which contains an "Umlaut".

For the ingredients "Paprika" and "Rispentomaten" the amount is not calculated correctly. **It was:**

![grafik](https://user-images.githubusercontent.com/36477626/195902421-2aedbeee-3888-4845-a8f7-e8370ee9b080.png)

**now it is:**

![grafik](https://user-images.githubusercontent.com/36477626/195906363-4c564303-f51d-4d22-afbc-1bf65b56972f.png)

**it should be:**

1 x "Paprika"
2 x  "Rispentomaten"

Last but not least the amount of "Prisen" is wrong either:

![grafik](https://user-images.githubusercontent.com/36477626/195906868-3f64c23b-5be3-477d-b783-db858842f483.png)

Those two where the only one which where correct in the past and now incorrect by the "ME-Umrechnung" factor...


Thanks a lot !! I appreciate your work :). If you have any question please let me know i will assist you as much as i can.

**Comment by Quantum1337** [comment]
For point 2 i have the reason:

![grafik](https://user-images.githubusercontent.com/36477626/195920429-35df57c0-172b-4f7b-a636-cf05840f3300.png)

Index 3, 4, 5 are the same conversion. But a "Stück" is not defined the same way for a "Speisezwiebel", "Paprika" and for "Rispentomaten", because the mean weight for a "Stück" is not the same for each of these vegetables.

It seems that the first one is correct, and the second and third are only a copy of the first.

**Comment by MrJohnZoidberg** [comment]
Now your three points should be fixed :-)
If not, simply reopen the issue again. Thanks for your examples and screenshots, they were a huge help!

**Comment by MrJohnZoidberg** [comment]
You can test the fixes with the new nightly build (should be available in a few minutes), I hope they are working. 😁

**Comment by Quantum1337** [comment]
Seems to work ! Thanks a lot too :)
