### ISSUE TITLE
Ingredient amount set in the recipe view not correctly passed to the server

### ISSUE THREAD

**Issue by Quantum1337** [patzly/grocy-android#585]
Hello there,

i think this topic highly relates to [Post](https://github.com/patzly/grocy-android/issues/584#issuecomment-1276537305) - (#584).
When creating a new recipe (here "Test") within the app and adding an ingredient. The app will show me the following:

![Screenshot_20221012-204415_Grocy](https://user-images.githubusercontent.com/36477626/195423358-e6001579-a411-4be7-9f52-45fbbaf5baa4.png)

The WebUI has now wrong values:

![image](https://user-images.githubusercontent.com/36477626/195423977-bae7f1a6-1101-45a4-a24d-6392481a4e6b.png)

I think this is because you are not taking into account, that there is a factor of 1000 between the "Bestandsmengeneinheit" Kilogramm and the recipe unit Gramm

The product "Langkornreis" has the following standard conversions:

![image](https://user-images.githubusercontent.com/36477626/195425084-d1a87a98-5dce-46f4-b818-3d7397e915a3.png)

Thank you for your work !

**Comment by MrJohnZoidberg** [comment]
Hopefully fixed with [7d4f01f](https://github.com/patzly/grocy-android/commit/7d4f01f6c7dd01210ec4d2331dcad917f6a3eea5).
You can test the fix with the newest nightly build. :) Thank you!

**Comment by Quantum1337** [comment]
Seems not to be fixed. When i add an ingredient in the app, the value is passed incorrect to the server. For example:

There is a conversion 1kg <-> 1000g for Meat. 
Now i want to add 500g of Meat as an ingredient (Baseunit is kg). The server will show then 500000g.

Furthermore, when I'm in the ingredient overview i have the same bug as it was fixed in #584. See:
![Screenshot_20221025-183654_Grocy](https://user-images.githubusercontent.com/36477626/197833746-c1ea660c-4750-49f2-a87c-752a2c368cf4.png)

Thanks for digging into this :)

**Comment by dominiczedler** [comment]
Should be fixed now, please test it with the latest nightly. :)
The mistake was that the conversions and stock unit relations were ignored on sending and displaying the amounts.

**Comment by Quantum1337** [comment]
It works like expected now. Thanks a lot !
