### ISSUE TITLE
Permit external access

### ISSUE THREAD

**Issue by calderon67** [patzly/grocy-android#586]
First of all, thank you for your incredible job.

As a useful suggestion, it would be really appreciated to have the possibility of use the app from external internet conection. Currently I am using ngixn proxy manager with ssl certificate.

Thanks a lot

**Comment by jsternadel** [comment]
The app can already be used on external internet connections.  Your network that is hosting your Grocy instance needs to allow incoming public internet traffic.

For example I have Grocy located on subdomain at https://erp.mypersonaldomain.com.  My router (Unifi Edge Router PoE) forwards ports 80 and 443 to my Swag docker using SSL on my unRAID server.  The proxy then forwards traffic to the Grocy docker.  I can use the app to reach my Grocy instance as long as I have a wifi or mobile data connection no matter where in am.

**Comment by calderon67** [comment]
I access to home assistant with a dns of duckdns.org, so the external access configuraction is ok. How can I know where to redirect traffic? And also, how should I make it know to the app?

**Comment by jsternadel** [comment]
Have you tried the steps in the FAQ for connecting the app via HASS?
https://github.com/patzly/grocy-android/blob/master/FAQ.md#user-content-faq4

Other than that I'm afraid I can't be of much help as I run Grocy stand-alone outside of my HASS instance.

**Comment by calderon67** [comment]
I have discovered a way of doing it. The QRs have to be scanned on an external access using dns domain. After that it works perfectly well. Hope this helps anyone else and thank you for your work!
