### ISSUE TITLE
AuthFailureError when using custom user permissions

### ISSUE THREAD

**Issue by jsternadel** [patzly/grocy-android#587]
Full log line with debug logging enabled:
`ShoppingListItemEditViewModel: saveItem: com.android.volley.AuthFailureError`

Version:
Grocy 3.3.1
Grocy Android: 2.3.0

Steps to Reproduce:
1. Create a new user
2. Uncheck "All Permissions" and enable full "Shopping List" permissions along with any other permissions
3. Log in as new user on device using API Key
4. Try to add items to the Shopping List
5. Receive "No permissions for this Action" toast pop up

Expected Behavior:
Add the product to the shopping list

I looked over the FAQ and did not find any mention of the app needing to be used by a user with "All Permissions" set.  And quite frankly its a tad dangerous to let the wife use the app with full permissions enabled.  I have no idea what she might delete on it.  Its been awhile since I worked on an android app but if you need more info for this bug I could fire up the dev tools and plug the device in to get more data from logcat.

**Comment by jsternadel** [comment]
Ignore this.  Seems to be an issue with Grocy itself.  I just discovered that when using 2 separate browsers.

**Comment by patzly** [comment]
Yes you're right, that should be a bug in grocy itself because we only call the grocy API to do the requested actions. Thank you for your efforts!
