### ISSUE TITLE
Application crashes when attempting to edit description of a product 

### ISSUE THREAD

**Issue by ArthurWolfhound** [patzly/grocy-android#589]
https://user-images.githubusercontent.com/16789106/199956475-55ec2929-2d7f-4d9d-a59c-6a1a7edb7836.mp4

Model name: Samsung Galaxy Note10+
Model number: SM-N9750
Android: 12 (One UI 4.1)
Security Patch: August 2022
Kernel version: 4.14.190-24304207-abN9750ZSS5HVH1 #2 Mon Aug 15 15:55:56 KST 2022

Please let me know if I can attach logs somehow

**Comment by MrJohnZoidberg** [comment]
Could you please enable the logs in our app's settings and after the crash, look up the log and upload the section with the crash here? Thank you!

**Comment by dominiczedler** [comment]
I think, like in #603, you have the app version 2.3.0 - the crash hopefully won't occur in the current nightly builds. Can you confirm or test that?
