### ISSUE TITLE
Feature request: Translation to Norwegian

### ISSUE THREAD

**Issue by teitrand** [patzly/grocy-android#59]
I can help translate it to Norwegian if you want.

**Comment by patzly** [comment]
Please read the [contribution section of our README](https://github.com/patzly/grocy-android#contribution) ;)
I just added Norwegian to the languages, so please [join our Transifex project](https://www.transifex.com/signup/?join_project=grocy-android) and help translate all strings!
I'll be notified when the translation is finished to include Norwegian in an update :)

**Comment by MrJohnZoidberg** [comment]
Thank you for contributing to this project!
We will include your language after it reached 80%, so I will close this issue now. :)

**Comment by teitrand** [comment]
Hi! When will the norwegian language that I translated become available in the app?

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MrJohnZoidberg** [comment]
Hi, sorry for the long waiting time. We will publish a new version today, the Playstore version will have a slight delay. :)

**Comment by patzly** [comment]
Nobody can use the Norwegian translation because of the wrong language code...
The right code for norwegian bokmål @teitrand translated is `nb_NO`, not `no`.
Let's see how we can change it without destroying the Transifex structure! (I found no option, thanks Transifex)

**Comment by MrJohnZoidberg** [comment]
Fixed in 1.8.5 which will be soon released.
