### ISSUE TITLE
Error when scanning the API-Barcode for the server

### ISSUE THREAD

**Issue by OliSti1** [patzly/grocy-android#590]
When I scan the API-Barcode in my grocy installation to connect the app to my grocy installation  I get the Error:
com.android.volley.Volley.Error:  java.lang.RuntimeException: Bad URL: /api/system/info

The connection with the manual way is possible.

I installed the nightly build version today
I use grocy 3.3.1

**Comment by blowk** [comment]
Same here.

When entering it manually, I get error: com.android.volley.AuthFailureError

**Comment by dominiczedler** [comment]
@OliSti1 This error with Bad URL: /api/system/info means that the QR code didn't contain any URL information, so I think that your grocy instance is not configured correctly or it has a special configuration - and your grocy doesn't know it's URL in this case, so it cannot be copied into a QR code.

**Comment by dominiczedler** [comment]
So I think we can do nothing useful for you. If you want to make sure that I'm telling you the right things, you could scan the API QR code from grocy with another app on your phone to see what it contains.
