### ISSUE TITLE
New version missing on F-Droid [2.3.0]

### ISSUE THREAD

**Issue by igor-cali** [patzly/grocy-android#591]
Version `2.3.0` is available in the Play Store repo, but it is missing on F-Droid.
Last version available in F-Droid is `2.2.1`.

See also https://github.com/patzly/grocy-android/issues/566.

**Comment by patzly** [comment]
v2.3.0 is still the last version we released, so you have to wait for the next release (which will be compatible with F-Droid again) :)
This takes time because I'm currently working on the Material You redesign (progress in #588), you can use the nightly builds to test the current progress.
