### ISSUE TITLE
Default due days after freezing 

### ISSUE THREAD

**Issue by JakeD22** [patzly/grocy-android#593]
The default due days after freezing is not automatically being pulled from the server for that item and being put into the date field.

**Comment by MrJohnZoidberg** [comment]
@JakeD22 Can you describe the issue and your workflow where it occurs more clearly?

**Comment by JakeD22** [comment]
@dominiczedler i will gladly elaborate i should have done that to begin with. We have a freezer rule for beef that the expiry date is pushed out several months. when adding this in on the app it seems to ignore this rule we have set. for example i scan beef mince and say i have put it in the freezer, its supposed to add 150 days to the expiry as its in a freezer but that doesnt seem to be the case.
