### ISSUE TITLE
New master product: Stock units vs. shopping units

### ISSUE THREAD

**Issue by schnillerman** [patzly/grocy-android#596]
Hi,

I discovered a bug in the app v2.3.0.

**Background**: Adding a new master product with different stock and shopping units results in not being able to set the stock unit to be the same as the shipping unit once product is created/saved in the master data. When editing the product, only the already set unit is available in the drop down list of stock units.

According to the help note, stock units can only be changed if a conversion between stock and shopping units is defined.

See following pictures:

![Screenshot_20221215_021814_Grocy](https://user-images.githubusercontent.com/17252473/207750877-efafea64-2b46-4160-a00e-ead7bad23bb8.jpg)
![Screenshot_20221215_021812_Grocy](https://user-images.githubusercontent.com/17252473/207750882-f60b795b-5082-47f5-915a-6f0a1c5e554f.jpg)

**Error**: If I add a conversion for the product between the set stock and shopping units of the same product, an error is displayed ("Ein Fehler ist aufgetreten", see following picture).
![Screenshot_20221215_022259_Grocy](https://user-images.githubusercontent.com/17252473/207750833-a5f8d13e-4ada-48a2-ba51-ac8c7aa9a6fe.jpg)

**Steps to reproduce**:

1. Add new product, choose different units for stock/shopping, save product.
2. Try to change stock unit - only same option displayed.
3. Try to add conversion between both units, e.g. 1:1.
4. Error is displayed.

**Workaround**:
1. Create conversion between stock unit and arbitrary third unit
2. Create conversion between shopping and third unit
3. Change product's stock unit to match shopping unit
4. Delete all conversations

**Additional note**: On the server (v3.3.2), a 1:1 conversion between stock and shopping units is suggested when adding new product even if units are the same:

![Screenshot_20221215_023737_Chrome](https://user-images.githubusercontent.com/17252473/207752135-57be986a-0cea-43b1-9648-251665ae7cc6.jpg)

**Comment by dominiczedler** [comment]
This bug should be gone with [a0536e2](https://github.com/patzly/grocy-android/commit/a0536e28db6cadc964310d2b0763ae5d315ce51f) (will be released with v3.3.0). Please open a new issue if it still occurs then.
