### ISSUE TITLE
Respect systemwide "disable animations" setting

### ISSUE THREAD

**Issue by anna328p** [patzly/grocy-android#597]
App still has (slow) animations even when they are turned off systemwide

**Comment by patzly** [comment]
Thanks! Yes, I have no idea how to change that, the documentation on how to change this does not exist.. maybe the Android team publish something about that in the future.

**Comment by patzly** [comment]
The newest nightly build (in the release section) should respect the accessibility option!

**Comment by patzly** [comment]
@anna328p Does it work?

**Comment by anna328p** [comment]
haven't tested, i'm on the latest play store build. will try it now

**Comment by patzly** [comment]
Okay thanks!

**Comment by anna328p** [comment]
I'm unable to download the nightly build. ![Screenshot_20221223-155724.png](https://user-images.githubusercontent.com/9790772/209408959-78454ef8-37f3-47f4-8809-009399c97662.png)

**Comment by MrJohnZoidberg** [comment]
I think the latest nightly build failed and the Apk file is missing, I will build it manually so in a few minutes you can find it again.

**Comment by MrJohnZoidberg** [comment]
@anna328p Now you can download the nightly APK :)

**Comment by patzly** [comment]
@anna328p Does it work?

**Comment by dominiczedler** [comment]
We can reopen it if there is still a problem.
