### ISSUE TITLE
Can't login: Cleartext HTTP traffic not permitted

### ISSUE THREAD

**Issue by duylong** [patzly/grocy-android#6]
Hi,

I have a error on the login page: An error occured. This error is not clear. No problem with a browser and the api key is correct. 

My URL server is http://192.168.x.x:8080, tested also without http://. 

Do you know this issue ?

**Comment by patzly** [comment]
The logcat of your device should contain the words `requestLogin: VolleyError:` followed by a more specific error name. Could you please give us this information?
Otherwise we'll take a closer look into this issue when we have time.

**Comment by Gsyltc** [comment]
Hi,

I cannot connect to my personnal server (with docker in a swarm cluster).
I get an error message : "An error Occured" while login

Web site is reachable over internet and LAN.
**Web url is an ovh public address**
route is : 
ovh -> ISP router -> docker swarm ingress -> docker container (LinuxServer.io)

Internet Browser :
Web server connection over LAN : OK
Web server : connection over Internet
API Key :! Created and valid
TLS Encryption : Not for the moment (Will be implemented via Load Balancer later)
Demo server is reachable with the app.
Android version : 10

Thanks

**Comment by patzly** [comment]
> The **logcat** of your device should contain `LoginActivity: requestLogin: VolleyError:` followed by a more specific error description.
> If this is the case, please send this part of the logcat to `patrick@zedler.xyz`.
> Right now we have to learn for our Abitur, so please be patient. Nevertheless we're trying to solve this issue.

@Gsyltc Please send me your logcat of the moment where the error occures, too. This would be really helpful!

**Comment by Gsyltc** [comment]
> > The **logcat** of your device should contain `LoginActivity: requestLogin: VolleyError:` followed by a more specific error description.

Where can I find it please ?

**Comment by patzly** [comment]
[**How to Get a Logcat for Reporting Bugs on Android**](https://www.makeuseof.com/tag/get-logcat-reporting-bugs-android/)

If this is too much trouble for you, please be patient. We're working at least on an update where the error description is displayed.

**Comment by Gsyltc** [comment]
I think it will be ok.
I will do this this in the evening.

Thanks

**Comment by Roxxor91** [comment]
Got the "same" error, here the log:
05-28 12:00:16.370  6459  6459 E LoginActivity: requestLogin: VolleyError: c.a.b.m: java.io.IOException: Cleartext HTTP traffic to 192.168.10.5 not permitted
I'm using the app internally, so I don't really need TLS. When trying TLS instead of http, the handshake fails, but that's an issue of my server configuration.

**Comment by patzly** [comment]
@Roxxor91 Thanks for the logcat!

The error shouldn't occur in the latest release anymore, as `http` is allowed now.

@Gsyltc please update your Play Store rating accordingly.

**Comment by duylong** [comment]
The last release resolve this issue. Thanks ;)

**Comment by patzly** [comment]
Glad to hear that!
