### ISSUE TITLE
ML Kit Scanner shows only black screen

### ISSUE THREAD

**Issue by r100gs** [patzly/grocy-android#602]
Hello together,

first I would like to say thankyou making this great app.
It works almost fine, but I tried to use the ML Kit Scanner and it only shows a black screen.
My device is a xiaomi 12 with Android 13 (MiUI 13.2.4)
PLease contact me if you need further information or if I can try something.

Best regards,
Stefan

**Comment by r100gs** [comment]
I tested it several times without success, but now it seems to work, so closing this issue

**Comment by patzly** [comment]
Okay weird but glad that it's working now and tank you!
