### ISSUE TITLE
Crash when editing a recipe

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#603]
The App crashes immediatly when i click on preparation in the edit recipe screen.

**Comment by MrJohnZoidberg** [comment]
Could you please enable the logs in our app's settings and after the crash, look up the log and upload the section with the crash here? Thank you!

**Comment by Saturo78** [comment]
Here is the log:

--------- beginning of main
12-22 20:41:30.843 16695 16695 E ViewUtil: icon animation requires AnimVectorDrawable
--------- beginning of crash
12-22 20:41:34.296 16695 16695 E AndroidRuntime: FATAL EXCEPTION: main
12-22 20:41:34.296 16695 16695 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 16695
12-22 20:41:34.296 16695 16695 E AndroidRuntime: java.lang.IllegalAccessError: Field 'org.ccil.cowan.tagsoup.ElementType.theAtts' is inaccessible to class 'org.wordpress.aztec.AztecHtmlSchema' (declaration of 'org.wordpress.aztec.AztecHtmlSchema' appears in /data/app/~~T0NPgfBUWzbThM73xKu52A==/xyz.zedler.patrick.grocy-8Ipi0_QEl9daT2MP8iItgQ==/base.apk)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at org.wordpress.aztec.AztecHtmlSchema.<init>(AztecHtmlSchema.kt:3)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at org.wordpress.aztec.Html$HtmlParser.<clinit>(Unknown Source:2)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at org.wordpress.aztec.AztecParser.fromHtml(AztecParser.kt:5)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:5)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.EditorHtmlFragment.onViewCreated(EditorHtmlFragment.java:18)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:45)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:138)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(Unknown Source:3)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8751)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
12-22 20:41:34.296 16695 16695 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
12-22 20:41:37.994 16972 16972 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
12-22 20:41:37.995 16972 16972 E USNET   : USNET: appName:  xyz.zedler.patrick.grocy

**Comment by dominiczedler** [comment]
Ah this is not the latest app version, please give us the version as an information in the beginning when you describe a bug. The Aztec Html Editor is not used anymore in the nightly builds, so I hope the crash also won't occur anymore if you use these prereleases.
