### ISSUE TITLE
Feature Request: Transaction to scan and set barcode to product

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#605]
I would be really happy if there is a way to scan a barcode, check if the barcode is connected to any product. If not open a input window to select to which product it belongs and then do nothing else as put the barcode to the products masterdata.

**Comment by patzly** [comment]
I like that idea!

**Comment by tjhowse** [comment]
I've been using the "Inventory" screen (Hamburger, 📋) to do this, with one slight wrinkle. If the quantity in stock is already correct for this item it won't let me submit the page to link the barcode to the product, instead I must:
* Scan a previously unknown barcode,
* Search for and select the product,
* Get a "Cannot be equal to #" error,
* Increase the amount by 1, submit,
* Scan again, decrease the amount by 1 back to the correct amount, submit again.

This process would be better if it were:
* Scan a previously unknown barcode,
* Search for and select the product,
* Submit.

It looks like both our needs could be met by simply removing the validation on the inventory page that rejects submissions that change the in-stock amount to the same value it already has.

**Comment by dominiczedler** [comment]
@tjhowse Thanks for your pull request, I've solved it in another way but it should also work like what you want to achieve:

![image](https://user-images.githubusercontent.com/27244574/220811319-2ef3eda1-99b6-427e-b186-0fcc66c9daae.jpeg)

**Comment by tjhowse** [comment]
Love it! Thanks!

**Comment by Saturo78** [comment]
Would it be possible to set the barcode infotext also in this step? I use this a lot with generic products to store brandinfos in the barcode infotext.
