### ISSUE TITLE
Feature request: disable parent with disabled stock in purchase dialog

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#606]
The purchase dialog shows also parent products with "disable own stock"

Instead of this i would find it very helpful when in the case of buying such a parent (because it is used in a recipe) the valid childs are shown in the purchase dialog.

**Comment by dominiczedler** [comment]
I think this is a duplicate of #508. I think I can implement this right now quickly.

**Comment by dominiczedler** [comment]
There is now a selection for child products implemented, if the selected parent product has no own stock.
