### ISSUE TITLE
Bug: edit recipe wrong amount on overview page

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#612]
I have found another issue when edditing a recipe.
Here is my scenario:

Product:  Butter 
Conversation 1 Pack=250g

Recipe:
Add 10g Butter
Go to recipe overview
Here you found 2500g Butter
Edit recipe
Ingrediens
There is still set 10 g 

I think here exists an issue which sets 10 packs = 10x250g = 2500g when adding 10g.

**Comment by Saturo78** [comment]
I think this could be related to #611.

**Comment by dominiczedler** [comment]
Should be fixed now, please test it with the latest nightly. :)

**Comment by Saturo78** [comment]
I think there is still a little issue.
I have a product with the following conversations:
Purchase Piece Storage Piece 1:1
1 Piece = 10 Parts (own unit)
1 Part = 3 g

When i use 1 part in a recipe the overview page shows
this equals 3 Piece
