### ISSUE TITLE
Recipes: Add price factor field

### ISSUE THREAD

**Issue by dominiczedler** [patzly/grocy-android#615]

**Comment by vanMacG** [comment]
I think I just stumbled upon this.
To be more precise: the price factor is a field in a recipe ingredient.
When adding an ingredient via web-interface the default value "1" is entered/saved along with.
When adding an ingredient via app, the field is missing but saved nevertheless. When editing the ingredient via web-interface the value is "0", resulting in an error and other changes can't be saved:

![grafik](https://github.com/patzly/grocy-android/assets/8269814/4f756aff-04b1-4356-b0d4-aea5b0eb26f3)

Maybe you can add the default value "1" as a quick-fix, this would at least solve the error on editing.
