### ISSUE TITLE
ML Kit Barcode scanner not functional on Pixel 6 Pro

### ISSUE THREAD

**Issue by jeschmidt** [patzly/grocy-android#616]
On my Pixel 6 Pro, the ZXing barcode scanner works just fine.  I bought the Play Store unlock key and enabled the ML Kit scanner because I wanted to support the devs and try out the better scanner.  Unfortunately it doesn't work on my Pixel 6 Pro, possibly because of the multiple hardware cameras?  The little window that normally shows camera image data is just black and the grocy app doesn't exactly crash but it behaves very sluggishly until you back out of the screen with the scanner visible.  I'm happy to send debug data if helpful as it's very easy to reproduce the problem.  Thanks!

**Comment by floriandaur** [comment]
Same issue here on a Pixel 6a

**Comment by patzly** [comment]
That's not good, I'm always on a Pixel 6 and all works as expected... Maybe you can find any debugging info on the logcat page in the app or when you search grocy in your device's logcat so we can have a look?
Please make sure you have installed the latest nightly build from the releases page here. Thank you for your purchase!

**Comment by floriandaur** [comment]
I tried the nightly, there I have no option to choose between ML and the
Xzing barcode scanner option in the settings.

Patrick Zedler ***@***.***> schrieb am Di., 3. Jan. 2023,
14:14:

**Comment by jeschmidt** [comment]
I won't be able to test nightly builds unfortunately because my phone is locked to install apps only from the Play Store.  I'll try to find logcat debug info to help!

**Comment by DunklerPhoenix** [comment]
Same with pixel 4XL. Additionaly whole screen beginn flickering. It looks like the app tries to go full screen, but can't

**Comment by patzly** [comment]
@DunklerPhoenix as @floriandaur mentioned, nightly doesn't include the MLkit library (that 's because it's built with master and master is the branch for F-Droid without MLkit) so maybe you've just tested ZXing.
I will upload a test apk here with the MLkit option included, hopefully it works then because I have no idea what we can do in case of these problems... As I said I cannot reproduce it on my own devices and it's weird that Google's own devices have problems with their camera libraries.

**Comment by DunklerPhoenix** [comment]
Are you sure? There is an APK under releases with ml kit and I can choose it in the ui
![Screenshot_20230104-150056](https://user-images.githubusercontent.com/1261305/210571555-83d48348-1d91-4289-85e0-3f5543574011.png)
![Screenshot_20230104-150035](https://user-images.githubusercontent.com/1261305/210571563-72898bc6-baa2-4335-bda5-e6e8357d5210.png)

**Comment by patzly** [comment]
@DunklerPhoenix Yeah I updated my answer, my brother didn't tell me that he added the other option :D

**Comment by floriandaur** [comment]
@patzly : confirm that it works with the nightly for me as well.

**Comment by jeschmidt** [comment]
Great, I look forward to that nightly version making its way into the Play Store so my (locked-down) phone can use the update!  Any idea what version to be looking out for?  I'm on 2.3.0 right now.

**Comment by patzly** [comment]
@jeschmidt Maybe you can google your device for a method to unlock installation of downloaded apks? This is a very crucial feature of Android phones, so I would find it very bad if your phone is really locked in such a way, I never heard of that before.

**Comment by patzly** [comment]
And yes, v2.3.0 is the current Play Store release and the next will be the big v3.0.0 redesign.

**Comment by jeschmidt** [comment]
I appreciate the suggestion but it's a work phone, locked by my employer.  Even if I could (easily) bypass the restriction, I am not supposed to.  So I'll wait for 3.0.0 to hit the Play Store, thanks!

**Comment by krazyguy2312** [comment]
Can confirm, Pixel 6 pro with ML Kit enabled on Play Store version, same behavior as OP.

Sideloaded the nightly apk and fixed the problem.  

On a side note, I love the newer UI.

**Comment by patzly** [comment]
@krazyguy2312 Thank you! Glad you like it, that was much work over last year and is still not completely finished :)
I think we will leave this issue open until we release v3.0.0 so other users with the problem can see it.
