### ISSUE TITLE
Shopping List indicator not visible for products with too long names

### ISSUE THREAD

**Issue by martin-braun** [patzly/grocy-android#617]
Some products names are so long that you are unable to see the suffix dot icon that indicates that the item is on the shopping list.

![image](https://user-images.githubusercontent.com/24259245/210367292-ea14eea1-95fb-4343-b882-742a74a97495.png)

You can see "meridol" is on the shopping list, because there is a blue dot behind the name. Very useful. However, 2 of the 3 following products are on the shopping list as well, but it can't be seen, because the name is too long. 

I think it would be much better to just turn the font of the product name bluish as well. Or alternatively, display a little shopping cart icon in the 2nd row behind "(X opened)". This way it would be visible all the time.

Thanks.

**Comment by Saturo78** [comment]
Maybe you could use shorter product names or set your devise to landscape mode.

**Comment by martin-braun** [comment]
@Saturo78 That would be a work-around, but not really a welcoming one. I really think we have the space for those indicators in the bottom line of each product, but I will use landscape mode to see if the products are in the shopping cart for now.

Most product names are generated from the APIs that you can enable in the backend and they are long.

**Comment by patzly** [comment]
I mostly shorten the fetched names from Open Food Facts because they are far too long and most parts of the product name are not really helpful, that would be my solution.
We will probably not add a new icon to the second line, instead we will make sure that the blue dot is displayed at the end no matter how long the name is.
