### ISSUE TITLE
Feature request: Add barcode info when assigning barcode to product

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#619]
I'm looking for a workflow to fill the barcode info field when i assign a barcode to an existing product via the purchase dialog.
Mayby its posible to open an input form to enter the information?

**Comment by patzly** [comment]
On the overview page, long-press the scan button in the bottom bar to go to the purchase page in scan mode, then scan the barcode and type in the name for the existing product, select it from drop-down and purchase the product. The new barcode is now stored in the existing product.

**Comment by dominiczedler** [comment]
@patzly I think that is not the question, he wants to enter fill information for the barcode which is currently not asked in the app (I think grocy webinterface doesn't ask details either).

I will investigate which way can be implemented to support this feature.

**Comment by patzly** [comment]
Oh I see!

**Comment by dominiczedler** [comment]
The note field on the purchase form will be written into the note field from the barcode (if it was unknown barcode). This will be also the behavior in grocy server 4.0 .
