### ISSUE TITLE
Cannot change server

### ISSUE THREAD

**Issue by NeilS1966** [patzly/grocy-android#621]
I have just changed Grocy servers. I now have a new server running at a new URL and would like to reconfigure the Grocy app from the old server to the new one. 

When I click Settings>Server and then click Server URL, the Stock Overview page is displayed. I was expecting a dialog box to allow me to enter my new server URL.

Am I missing something here?
Grocy App Version: 2.3.0

**Comment by dominiczedler** [comment]
Log out? :)

**Comment by NeilS1966** [comment]
That did it! Thank you.

**Comment by dominiczedler** [comment]
You're welcome.

**Comment by NeilS1966** [comment]
I am self hosting Grocy in a docker container and tunnel into it from a public IP. I scanned the QR code when I was logged in locally and I was connected to it.
However when I logged out and tried to scan the QR code from my public URL, I received a message "Not a valid grocy instance".
Any clues as to why this happens?
