### ISSUE TITLE
Please provide the nightly build with a different App ID

### ISSUE THREAD

**Issue by martin-braun** [patzly/grocy-android#623]
I'd like to use stable and nightly builds of this app side by side. I want test new features without risking to lose the ability to do something due to crashes. It would be nice if the nightly build would use `xyz.zedler.patrick.grocynightly` instead of `xyz.zedler.patrick.grocy`, so one can side-load it to the F-Droid build.

Thanks.

**Comment by patzly** [comment]
Hmm then we would need another branch because the package name is hardcoded in many places of the app, I will talk with my brother whether this is possible but the idea is good.

**Comment by martin-braun** [comment]
Afaik, you can load a different `AndroidManifest.xml` for `debug` builds. If you maintain a different branch, you most likely need to cherry-pick constantly, which will be annoying after a while.

I assume your nightly build is a release build as well. In this case, it might be worth to explore a nightly build pipeline that replaces the app ID in these files prior build, but I don't know if this is possible with the GitHub actions workflow.

Thanks for considering it.

**Comment by dominiczedler** [comment]
Should be working in the latest nightly builds, the app name is now "Grocy Nightly".
