### ISSUE TITLE
Connexion

### ISSUE THREAD

**Issue by schumi2309** [patzly/grocy-android#628]
hello,

I am connected outside to home assistant via nabu casa.
here is the kind of url i have to connect to it:

https://xxxxx.ui.nabu.casa/

If I put this url like that or with: 9192 it doesn't work!
so, how to do ?

**Comment by patzly** [comment]
Hi, you need to expand the extra fields on the login page. Please read the [FAQ](https://github.com/patzly/grocy-android/blob/master/FAQ.md) for more information.

**Comment by dominiczedler** [comment]
Scanning a QR code does not work for you? The app gives you the necessary instructions to do that.

**Comment by patzly** [comment]
Please try it with the latest v3.0.0 release and open this issue again if you still have any problems.
