### ISSUE TITLE
Can't add product to database (mobile)

### ISSUE THREAD

**Issue by tom2411** [patzly/grocy-android#629]
When i try to add a new product to my DB the stock format is grey and i can't put a value on it so because it's an mandatory field, I can't add a new product.
This behavior is only on the mobile app.
Whereas on the website it works well.

**Comment by dominiczedler** [comment]
Do you have already at least one quantity unit in your master data?

**Comment by patzly** [comment]
Please test the latest release v3.0.0 and open this issue again if you still have any issues.
