### ISSUE TITLE
Bug: Dark icon in dark mode

### ISSUE THREAD

**Issue by martin-braun** [patzly/grocy-android#631]
Minor bug in the nightly build: From your shopping list, edit an entry, then click on the small (!) icon in the bottom left to edit the master data of the product, so a bottom panel of the product itself opens.

The edit icon is black, even on the dark mode.

![image](https://user-images.githubusercontent.com/24259245/211227593-5b8abad6-71e3-4766-bc55-8a14990d6d77.png)

**Comment by patzly** [comment]
Thank you!
