### ISSUE TITLE
Add to shopping list does nothing (from recipe view)

### ISSUE THREAD

**Issue by Quantum1337** [patzly/grocy-android#632]
Hello,
when i want to add the ingredients from a recipe into the shopping list ("Zum Einkaufszettel hinzufügen" Button in the specific recipe), nothing happens. The shopping list stays empty.
Thanks for your work

**Comment by patzly** [comment]
Hi, this feature is not implemented yet, only the button is already there :)

**Comment by Quantum1337** [comment]
ahh ok good to know, thank you for the hint :)

**Comment by dominiczedler** [comment]
This action should work in the next nighty build, if there are still any problems please tell us. :)
