### ISSUE TITLE
New product should inherit some data from parent product on creation

### ISSUE THREAD

**Issue by martin-braun** [patzly/grocy-android#636]
When creating a new product - before setting any other properties - I set the parent product, I kinda expect that it inherits most of the properties from the parent product, so that I can make further adjustments based on the parent product's properties.

Things that could be set are: 

- default due days
- due days when freezing
- due days when stopped freezing
- storage location
- consume location
- purchase store (location)

Especially inheritance of the due days would be helpful. So if I once know how long my product lasts, I don't have to think about how long my children product last when creating them, again.

**Comment by martin-braun** [comment]
There is an [issue at grocy](https://github.com/grocy/grocy/issues/1304) about that. The common work-around is to simply duplicate the parent product and make it a child product to get what I want. However, in the app this is not really possible when I create a new product after scanning a barcode.

Whether @berrnd implements such functionality in grocy or not, it'll be a callback that is triggered after setting a parent product, thus there are changes required in grocy-android as well to make this happen on the mobile app.

**Comment by dominiczedler** [comment]
Thanks for the suggestion, I added a copy action to the product choose page which opens after barcode scan on purchase or inventory page (consume page too, but there it is not possible to create new products anyway).

If you have a product Schokolade you can now

- scan for example "Kinder Schokolade" barcode
- after that "choose product" page opens
- product name "Kinder Schokolade" is loaded from Open Food Facts
- App performs fuzzy search and first entry is possibly "Schokolade" now
- There you can tap on the copy symbol on the right
- New product has all properties of "Schokolade" now and "Kinder Schokolade" is already in the name field.

**Comment by martin-braun** [comment]
@dominiczedler Thanks a lot, this is very sufficient. Then I just need to assign the parent product and I'm good to go. If I understand correctly, it will also allow me to choose a similar product that has the same parent product and use its selections incl. the same parent product.(?)

I will give detailed feedback once I can test the feature in detail. Again, thanks a lot! :)

**Comment by dominiczedler** [comment]
Thanks for the compliment, I also thought that this change is very useful for all people, because it makes it totally easy to create products quickly after scan. Yes, I think the parent product property should also be copied.😄
