### ISSUE TITLE
UI: Clear Shopping List "Proceed" Button Barely Pressable 

### ISSUE THREAD

**Issue by cslux** [patzly/grocy-android#641]
The "Proceed" button is almost completely behind the system 3-button navigation.
![grocy-android-ui-bug](https://user-images.githubusercontent.com/1712313/213887655-d7ebf13d-1280-4235-b5cc-bf8fcd4f30e9.png)

**Comment by patzly** [comment]
That's a result of the ongoing redesign and the reason why the new version is still in the alpha phase :)
See #588 for my progress of the redesign, unfinishes components are still ugly and have a wrong layout because of the global changes.

**Comment by patzly** [comment]
But in the latest alpha it should not look like that anymore? I already redesigned that dialog a few days ago.

**Comment by cslux** [comment]
@patzly I can confirm this issue is gone in the nightly build version (Grocy-Android-master-20230122.apk)

Thank you!
