### ISSUE TITLE
Force close at start

### ISSUE THREAD

**Issue by HydrelioxGitHub** [patzly/grocy-android#643]
After update to 3.0 on Google Store, I can not start the app any more, it crashed every time. I've filled a report "send comment".

**Comment by patzly** [comment]
Can you please look at your device's logcat (for example with [Logcat NO ROOT](https://play.google.com/store/apps/details?id=com.tananaev.logcat), but you also need adb on your pc for that, or simply google how to get the logcat of an Android phone). Then you can search for grocy and the crashes should be displayed, this are the lines we need.

**Comment by HydrelioxGitHub** [comment]
I've wiped all data app (storage and cache) and now it seems to start. I will reconfigure it to see if everything is ok.

**Comment by patzly** [comment]
Nice! Please open the issue again with a crashlog if it happens again.
