### ISSUE TITLE
Support disabled grocy features 

### ISSUE THREAD

**Issue by tzbob** [patzly/grocy-android#647]
We mainly use grocy to track chores conveniently and although the app says it only supports stock management I think it's selling itself short! The main page is perfect for a quick glance at the chores even though you still need the server to set it up. 

It would thus be awesome to remove the stock feature warning and just hide the stock features when they're disabled on the server. It'd make it a perfect UI for a quick recipe/chores/etc. glance!

**Comment by patzly** [comment]
I think that's possible, thanks for your suggestion!
