### ISSUE TITLE
Stop scan when not in stock

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#649]
When you scan a product in cosume mode which is not in stock then there is prompted a message "product x is not on stock" directly after this message the barcode gets scanned again and this repeats over and over as long the barcode is in front of the camera.

Maybe its better to switch to the purchase or invetory mode in this case?

**Comment by dominiczedler** [comment]
Mmh I would say this is intended behavior. Asking for purchase or inventory doesn't make sense in my opinion because the user selected "consume" intentionally. The server website behaves the same I think.
