### ISSUE TITLE
Quickscan Confirmation/ Cancle below back button

### ISSUE THREAD

**Issue by userbradley** [patzly/grocy-android#653]
Not sure if this is just a me issue, but when quick scan is enabled, the `Confirm` and `Cancel` button are below the native android back button

Device: Zebra TC56DJ
Android: 6.0.1
Grocy server: 3.2.2
App version: 3.0.0

Let me know if you would like a screen capture of this behaviour, or if anyone else has similar issues

**Comment by patzly** [comment]
Do you have the latest stable release installed or a previous nightly build? If latest stable, please attach a screenshot because I could not reproduce your issue.

**Comment by patzly** [comment]
I think there aren't any navigation bar related issues in the current/next version anymore. Please reopen the issue again with a screenshot if the issue still exists.

**Comment by userbradley** [comment]
[IMG_0661.mov.zip](https://github.com/patzly/grocy-android/files/10716284/IMG_0661.mov.zip)
Latest stable build. 

Attached is a video!

**Comment by patzly** [comment]
Thanks! Are you sure this is only in this dialog or does the bottom navigation drawer (tap on the left button in the bottom bar) has the same issue? I mean does the navigation bar also cover the last element of the drawer? Because it uses the exact same method like in the confirm dialog..

**Comment by userbradley** [comment]
This seems to be the only dialogue I know does this.

Is there any that you want me to try?

**Comment by userbradley** [comment]
Sorry I just realised what you asked. Any one that pulls up the quick scan interface does that (purchase, consume)

**Comment by patzly** [comment]
Can you please try out the latest nightly and look if the issue still exists?

**Comment by dominiczedler** [comment]
In the Android 6.0 Emulator it looks for me like this with the latest nightly:

![image](https://user-images.githubusercontent.com/27244574/220815131-3a156d86-4bf1-42f9-9692-4d0dffc9f42b.jpeg)

Please tell us if the issue is still there for you in the latest nightly build. :)

**Comment by userbradley** [comment]
Sorry, been away from my computer for a while. Let me give it a go just now

**Comment by dominiczedler** [comment]
Does the bug still occur in the latest release `v3.2.0`?

**Comment by userbradley** [comment]
Hey, I've had to abandon Grocy due to upstream issues I'm waiting on the Dev to resolve. 

We can close this for now and once upstream issues are resolved I'll let you know!

Thanks for the help!
