### ISSUE TITLE
Shortcuts checked but where to find?

### ISSUE THREAD

**Issue by WHagenauw** [patzly/grocy-android#655]
In the menu I checked 4 shortcuts but don't see any difference in the layout. I cannot find them. I even changed the checked ones but not to be found. 
Where will they have to appear?

Kind regards,

Wim Hagenauw

**Comment by manuelkue** [comment]
If your launcher supports shortcuts you will see them for example when you long-press on the Grocy icon:
![image](https://user-images.githubusercontent.com/44258924/217083143-5917fee2-a805-4feb-bd82-066f70dc629e.png)

Depending on your launcher you will then also be able to create a shortcut from there (hold a shortcut in the dropdown and move it to the desired place).
