### ISSUE TITLE
Add product to shopping list by external scanner failed

### ISSUE THREAD

**Issue by WHagenauw** [patzly/grocy-android#656]
I use an external scanner which is working for e.g. consume a product. So I know the scanner is working for my problem below:
Now I wanted to add a product to the shopping list by clicking on shopping list in the main screen and than the + icon. I used the external scanner and it scanned the numbers from the barcode. That's all, nothing further happened. When I click the button to add it to the list it informs me that the product code does not exist and if I want to add it to an existing product. When I want to do that nothing happened. I am sure that the barcode (checked it again) is in my database so I also tested it with the camera in my tablet and than it works. 
Seems like it is not comparing the numbers with the database when an external scanner is used.

Kind regards

Wim Hagenauw

**Comment by dominiczedler** [comment]
Thanks for your description! The issue will be fixed in the next nightly build or in the upcoming v3.1.0 release.
