### ISSUE TITLE
Price details in offline mode

### ISSUE THREAD

**Issue by alkuzman** [patzly/grocy-android#664]
I have been using Grocy for a few days now. I would like to say that I really like how things are organized, how the app looks, and its responsiveness.

One feature that would be really useful for me is a min and average price in offline mode.

**Comment by dominiczedler** [comment]
Thanks for your compliments!

What page do you mean with offline mode? Stock page and Shopping list page have an extra field option where you can display the price. This is also available if you're offline.

**Comment by alkuzman** [comment]
Sorry, my bad. That was everything I needed. Thank you.
