### ISSUE TITLE
Reverse selfie scanner image?

### ISSUE THREAD

**Issue by martin-braun** [patzly/grocy-android#668]
I'm trying to use this app on standing tablet, so I decided to test the selfie camera scanner, but it seems the image is always mirrored and I didn't find a way to mirror it in the settings. Is this even possible to fix, maybe there is a solution that doesn't require you to take action?

Thanks!

**Comment by dominiczedler** [comment]
I just tried it with the ML Kit scanner and it also recognized the mirrored barcode. But we could add an option for ZXing scanner because there it hasn't worked for me.

**Comment by dominiczedler** [comment]
I've red this answer on stackoverflow: https://stackoverflow.com/a/16506518

> You don't actually want to flip the image data from the front camera. It is presented to an app the way the camera sees it. When Android flings the image onto a SurfaceView, it will mirror it, since it is more intuitive that way. But you don't need to, and shouldn't, mirror it in your code. 

It would make sense that the image is not mirrored internally, so recognition should work also for you...

Maybe the focus of the camera has issues with the distance of the barcodes in your setup or you can try ML Kit scanner which works better for low quality cameras like on the front of devices.

**Comment by martin-braun** [comment]
@dominiczedler I think you are probably right, the front cam is trash.
