### ISSUE TITLE
Due message appeared not in main screen

### ISSUE THREAD

**Issue by WHagenauw** [patzly/grocy-android#672]
I got a message from Grocy App that an item is due in 5 days and thought it would also appear on the main screen. So that it stays there until I solve it (or use it). But it isn't. Is this a bug or a enhancement?
Also when I clicked the Due message I was hoping it would show me the item that is due but showed an empty list. I needed to search the item myself.

**Comment by WHagenauw** [comment]
I got the message again for the warning that it will expire in 4 days and now it behaves as expected......

**Comment by dominiczedler** [comment]
I'm closing this issue, as we are currently working on an improved implementation for reminders which should be more reliable. Please open a new issue after the upcoming release if the issue still persists.
