### ISSUE TITLE
APP crashes randomly

### ISSUE THREAD

**Issue by DanielCarlWalther** [patzly/grocy-android#673]
--------- beginning of crash
03-18 09:25:29.556 29177 29177 E AndroidRuntime: FATAL EXCEPTION: main
03-18 09:25:29.556 29177 29177 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 29177
03-18 09:25:29.556 29177 29177 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String xyz.zedler.patrick.grocy.model.Location.getName()' on a null object reference
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.behavior.SystemBarBehavior$$ExternalSyntheticLambda1.onResponse(R8$$SyntheticClass:55)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$21$$ExternalSyntheticLambda0.onResponse(R8$$SyntheticClass:44)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$$ExternalSyntheticLambda18.onResponse(Unknown Source:6)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.CustomStringRequest$$ExternalSyntheticLambda0.onResponse(R8$$SyntheticClass:25)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:11)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:34)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-18 09:25:29.556 29177 29177 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
--------- beginning of main
03-18 09:25:31.183 29385 29385 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
03-18 09:25:40.510 29385 29385 E AndroidRuntime: FATAL EXCEPTION: main
03-18 09:25:40.510 29385 29385 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 29385
03-18 09:25:40.510 29385 29385 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String xyz.zedler.patrick.grocy.model.Location.getName()' on a null object reference
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.behavior.SystemBarBehavior$$ExternalSyntheticLambda1.onResponse(R8$$SyntheticClass:55)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$21$$ExternalSyntheticLambda0.onResponse(R8$$SyntheticClass:44)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$$ExternalSyntheticLambda18.onResponse(Unknown Source:6)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.CustomStringRequest$$ExternalSyntheticLambda0.onResponse(R8$$SyntheticClass:25)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:11)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:34)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-18 09:25:40.510 29385 29385 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-18 09:25:45.977 29513 29513 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
03-18 09:26:06.245 29513 29513 E AndroidRuntime: FATAL EXCEPTION: main
03-18 09:26:06.245 29513 29513 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 29513
03-18 09:26:06.245 29513 29513 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String xyz.zedler.patrick.grocy.model.Location.getName()' on a null object reference
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.behavior.SystemBarBehavior$$ExternalSyntheticLambda1.onResponse(R8$$SyntheticClass:55)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$21$$ExternalSyntheticLambda0.onResponse(R8$$SyntheticClass:44)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$$ExternalSyntheticLambda18.onResponse(Unknown Source:6)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.CustomStringRequest$$ExternalSyntheticLambda0.onResponse(R8$$SyntheticClass:25)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:11)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:34)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-18 09:26:06.245 29513 29513 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-18 09:26:12.432 29669 29669 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.

**Comment by dominiczedler** [comment]
When does the app crash? Please give us a hint on what page it occurs and after which action.
