### ISSUE TITLE
App crashes when adding a new item in offline mode

### ISSUE THREAD

**Issue by saknarf** [patzly/grocy-android#674]
I am a new user of grocy and don't know yet how good the app functions without an internet connection, but I guess it should not crash.

It happens when I try to create a new item while beeing in offline mode.

Log output:
`
--------- beginning of crash
03-18 18:30:47.882 15366 15366 E AndroidRuntime: FATAL EXCEPTION: main
03-18 18:30:47.882 15366 15366 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 15366
03-18 18:30:47.882 15366 15366 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnectedOrConnecting()' on a null object reference
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.ConnectivityLiveData.<init>(ConnectivityLiveData.java:13)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel.<init>(MasterProductViewModel.java:114)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel$MasterProductViewModelFactory.create(MasterProductViewModel.java:2)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider$Factory$-CC.$default$create(ViewModelProvider.kt:11)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel$MasterProductViewModelFactory.create(MasterProductViewModel.java:1)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:10)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:16)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.MasterProductFragment.onViewCreated(MasterProductFragment.java:35)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:254)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:146)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1046)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:92)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:74)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:4)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7703)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
03-18 18:30:47.882 15366 15366 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: FATAL EXCEPTION: main
03-18 23:44:07.096 28730 28730 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 28730
03-18 23:44:07.096 28730 28730 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnectedOrConnecting()' on a null object reference
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.ConnectivityLiveData.<init>(ConnectivityLiveData.java:13)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel.<init>(MasterProductViewModel.java:114)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel$MasterProductViewModelFactory.create(MasterProductViewModel.java:2)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider$Factory$-CC.$default$create(ViewModelProvider.kt:11)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel$MasterProductViewModelFactory.create(MasterProductViewModel.java:1)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:10)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:16)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.MasterProductFragment.onViewCreated(MasterProductFragment.java:35)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:254)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:146)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1046)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:92)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:74)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:4)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7703)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
03-18 23:44:07.096 28730 28730 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
--------- beginning of main
03-19 00:08:26.687 28958 28958 E AndroidRuntime: FATAL EXCEPTION: main
03-19 00:08:26.687 28958 28958 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 28958
03-19 00:08:26.687 28958 28958 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnectedOrConnecting()' on a null object reference
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.ConnectivityLiveData.<init>(ConnectivityLiveData.java:13)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel.<init>(MasterProductViewModel.java:114)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel$MasterProductViewModelFactory.create(MasterProductViewModel.java:2)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider$Factory$-CC.$default$create(ViewModelProvider.kt:11)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.viewmodel.MasterProductViewModel$MasterProductViewModelFactory.create(MasterProductViewModel.java:1)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:10)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:16)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.MasterProductFragment.onViewCreated(MasterProductFragment.java:35)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:254)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:146)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1046)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:92)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:74)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:4)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7703)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
03-19 00:08:26.687 28958 28958 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
03-19 00:08:35.803 32014 32014 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
03-19 00:08:35.826 32014 32014 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
03-19 00:08:35.898 32014 32036 E ion     : ioctl c0044901 failed with code -1: Invalid argument
`

**Comment by patzly** [comment]
Thanks! Can you please explain exactly what you have done to get (and to reproduce) this crash? I tried to create a product in master products while being offline and it doesn't crash for me, it shows an offline error instead.

**Comment by saknarf** [comment]
1. Add new item to the stock
![Img1_grocy_bug](https://user-images.githubusercontent.com/33717436/226163450-54c3a1d4-24e9-441c-98c7-e6afc9fc0c21.png)

2. Scan Item that does not yet exists in the db
3. Klick the create new item button
![Img2_grocy_bug_1](https://user-images.githubusercontent.com/33717436/226163517-eb7016be-4306-4745-83f6-da66232b7ea7.png)

4. Crash

**Comment by patzly** [comment]
Thanks! I sadly still cannot reproduce it on my device, the master product page opens normally when I tap on the create new product option while offline..

**Comment by dominiczedler** [comment]
It seems that you used an older version of our app, in the latest version the crash cannot occur because the object is not called what produces a null pointer exception on your side. So please test it with the latest nightly or stable version. You can reopen the issue if the crash still occurs with the latest version (then there should be other log messages though).
