### ISSUE TITLE
Adding items to shopping list throws error (from recipe tab)

### ISSUE THREAD

**Issue by Auroria-code** [patzly/grocy-android#675]
Okay, we use HA (and as i said in issue #670, the app is not working current, so i can't show a video of what i mean) and we have some products that do not have a stock, but we can put them on the shopping list normally. However, when we try to put the things needed for a recipe on the list, it just says "an error accrued" and nothing happens. Even if we were to deselect the items that dont have a stock, it still does not work. Since this does on HA, i think this might be an errror of the app, but i shall be corrected if it is due to wrong configuration. (Newest version from HA, newest form app)

**Comment by dominiczedler** [comment]
Mmh I can't reproduce the error, can you test it again after our next version is released? You can also send me log lines if you still can reproduce the problem with the current version.

**Comment by dominiczedler** [comment]
Ping :) We've released version 3.2.1 yesterday.

**Comment by Auroria-code** [comment]
I tried it again, and I also am not able to reproduce this problem... Maybe it was just a one time thing that my head told me happens more often than it did.

**Comment by dominiczedler** [comment]
Okay thanks, you can reopen the issue (if you have the button for it) anytime if the bug occurs again. Or you can open a new issue.
