### ISSUE TITLE
Take Quick Consume Amount from Product instead from Barcode

### ISSUE THREAD

**Issue by maxu359** [patzly/grocy-android#677]
I don't know if this is just a user error or not:
Just a quick example:
I buy flour in 1kg and 5kg packs.
I scan them and the barcode defines than one pack has an amount of 1000g and the other one 5000g,
My quick consume amount is 100g.
So when I buy them and scan them, everything is perfect.
But if I scan the barcode for consume, it always takes 1000g(if I scan the 1kg pack)  or 5000g(scan the 5kg pack).
It doesn't take the quick consume amount of the product. 
Is it somehow possible to always take the quick consume amount instead of the amount which is linked to the barcode?
PS: Thanks for the great App:)

**Comment by Saturo78** [comment]
Not really a good idea.
Then everyone not using the quick consume amount has to enter the amount instead of simply scannig the barcode which represents the amount.

There i did not second this!

**Comment by dominiczedler** [comment]
@maxu359 Thanks for your compliment! I think your desired behavior is neither implemented in the server nor in our app. The quick consume amount is only the amount for the button "Consume" on the stock overview page. The barcode amounts behave like they should. Maybe you can ask on Reddit (grocy subreddit) how this could be done better in your setup, or if you think this is a feature request, search for an open issue or create an issue in the grocy server repository.
