### ISSUE TITLE
Quantity unit can't be changed after first purchase on new products

### ISSUE THREAD

**Issue by politas** [patzly/grocy-android#678]
Getting this thrown on creating new products, whether from the product list, or when using the search term as a new product. 

First noticed on 3.1.0, is still happening on 3.1.1

![Screenshot_20230406-084821.jpg](https://user-images.githubusercontent.com/2109967/230208444-ba9267d8-6033-4e0f-97e9-156ec0e0cb5e.jpg)

**Comment by politas** [comment]
Still happening on 3.2.1

**Comment by dominiczedler** [comment]
Which grocy version do you use and which Android version?

**Comment by dominiczedler** [comment]
Okay I can reproduce the bug, it's below grocy server version 3.3.0.
