### ISSUE TITLE
Bar code

### ISSUE THREAD

**Issue by rich5963** [patzly/grocy-android#680]
Hi 
I am having problems with the bar code in set up for HA, as it keeps telling me it's not a long lived token from Home Assistant. I am using nabu.casa to get to my server. Any idea's 
Thanks 
![IMG_20230419_193834](https://user-images.githubusercontent.com/130484708/233170081-d5503cd9-d815-46c1-b210-737d51e6682b.jpg)

**Comment by patzly** [comment]
Do you mean you don't know how to install and use the nightly? You can simply download it from the release page here on GitHub and install the apk. It should work side by side with the Play Store version as the package names are different. Or did you mean the nightly also doesn't work for you?

**Comment by rich5963** [comment]
I have now tried it doing the demo server it works but it still rejects the bar code in home assistant as it's not a long lived token from Home Assistant.

**Comment by rich5963** [comment]
Ok I have updated all the nightly version. When I add it by manually, then I press get API key it will take me to the dashboard but then I put the API key in & it doesn't work.
See attached photos
![Screenshot_2023-04-20-16-08-47-441_xyz zedler patrick grocy-edit](https://user-images.githubusercontent.com/130484708/233418122-db0edb94-d83e-4548-9403-567539e5ba88.jpg)
![Screenshot_2023-04-20-16-03-58-929_xyz zedler patrick grocy-edit](https://user-images.githubusercontent.com/130484708/233418310-dca83f69-fcbe-460a-98c5-b905c8c87762.jpg)

**Comment by rich5963** [comment]
Sorry it doesn't work if I put the port number in when I press create API key

**Comment by dominiczedler** [comment]
In your screenshot you are using the standard form but like the card above the form says, you have to tap on it and then there will be more fields for home assistant.

Please wait for the next official release of our app and then reopen the issue if the problem with the recognition still persists. We never had any problems since I changed the recognised formats...
