### ISSUE TITLE
Feature request / help : adding price and quantity after scanning

### ISSUE THREAD

**Issue by languagemaniac** [patzly/grocy-android#681]
Hi, I just installed grocy for the first time and I'm using it through the Android app.

I'm not sure if I'm doing it the right way but when I purchase something in grocy I do it by scanning the barcode, but after I do that it goes to another page where I see no option to input the price, instead I input the rest of the data, save it, and then it automatically goes into a countdown until it's definitely purchased which I have to cancel and then I input the price and the quantity and purchase it.

When I correctly set the price and scan the product again it does add the price automatically so this is only a problem when you scan something for the first time. 

I think it would be better to be able to set the price and the quantity after I scan it so I don't have to cancel any countdowns.

Like I said, I might be doing it the wrong way so I'd appreciate any comments on this.

I plan to fully implement grocy soon but for now I'm just learning / testing how everything works.

**Comment by dominiczedler** [comment]
Hey, thanks for your question! The countdown appears only in quick mode which you can toggle through long-tapping on the title bar of the purchase page. With quick mode of you can always enter all information in the fields. For a product grocy stores the last price and it will be filled automatically the next time. So after the first purchase with a price this field will be filled also in quick mode. Hope this helps. :-)
