### ISSUE TITLE
Creating or editing a unit conversion not possible

### ISSUE THREAD

**Issue by VNRARA** [patzly/grocy-android#682]
Creating or editing any quantity unit conversion gives a network error.

**Comment by patzly** [comment]
I cannot reproduce that, are you sure this wasn't a temporary error? Please try to give as much information as possible like error logs etc.

**Comment by dominiczedler** [comment]
Why did you close the issue? :) 
You can see crash logs in our app when you open the settings page and navigate to "Debugging".

**Comment by VNRARA** [comment]
--------- beginning of main
04-27 20:57:11.810 26220 26332 E Volley  : [836] BasicNetwork.performRequest: Unexpected response code 400 for https://gr. domain.nl/api/objects/quantity_unit_conversions
04-27 20:57:11.829 26220 26220 E MasterProductCatConversionsEditViewModel: saveItem: com.android.volley.ClientError

**Comment by VNRARA** [comment]
Commit 7488d214 may have made it worse...
