### ISSUE TITLE
Translation for brazillian portuguese

### ISSUE THREAD

**Issue by albarreto** [patzly/grocy-android#687]
Brazillian portuguese is a bit diferent to portugal portuguese.
I can help you with this, if you wish.

**Comment by VNRARA** [comment]
I'd file a request via their translate tool: [https://aphttps://app.transifex.com/patzly/grocy-androidp.transifex.com/patzly/grocy-android](https://app.transifex.com/patzly/grocy-android/languages/)

**Comment by patzly** [comment]
Brazillian Portuguese is already there and 60% translated, you can simply complete it.

**Comment by patzly** [comment]
Brazillian Portuguese is already there and 60% translated, you can simply complete it. Thank you for your contributions!

**Comment by patzly** [comment]
Brazillian Portuguese is already there and 60% translated, you can simply complete it. Thank you for your contributions!

**Comment by VNRARA** [comment]
Huh. I also didn't see that. I think it must've been a glitch in transifex when I went to look for that language.

**Comment by albarreto** [comment]
Hard work since yesterday.
94% translated

---
Aurélio Barreto


Em ter., 9 de mai. de 2023 às 06:41, Patrick Zedler <
***@***.***> escreveu:

**Comment by albarreto** [comment]
By the way, there's no option for Brazilian Portuguese on
Appearance/Language.
"Follow system" option uses "Português (Portugal)", but I use "Português
(Brasil)"


---
Aurélio Barreto


Em ter., 9 de mai. de 2023 às 10:57, Aurélio Lima Barreto <
***@***.***> escreveu:

**Comment by patzly** [comment]
That's because we have to implement the new language first and fetch it from Transifex, so no worries.

**Comment by albarreto** [comment]
Hi, brazilian portuguese is 100% done. A lot of work here :-)
When are they available on that great app?

---
Aurélio Barreto


Em ter., 9 de mai. de 2023 às 12:16, Aurélio Lima Barreto <
***@***.***> escreveu:

**Comment by dominiczedler** [comment]
We can't tell you the exact release date of the next version, it will come in one or two weeks I think. :-)

**Comment by VNRARA** [comment]
I guess I'll have to finish Dutch real quick
😁👍🏽
