### ISSUE TITLE
Crash when changing stock amount manually

### ISSUE THREAD

**Issue by VNRARA** [patzly/grocy-android#691]
Crash when changing stock amount manually.

Unfortunately no logs get created.

Replicated by changing stock amount for any product after messing with QU of said product using (i) icon.

**Comment by dominiczedler** [comment]
Thanks but I need more info for fixing this. Also there should be always a relevant section in the logs after a crash :-) Please try to reproduce it with the demo instance or give more info about the steps you have to do for the crash to occur.

**Comment by VNRARA** [comment]
I've tried, didn't manage. Weird because at first it was happening constantly when I was still in the setup period of adding stock. Maybe it has to do with not having beginner mode enabled anymore? Idk. I'll let you know if it happens again.

**Comment by dominiczedler** [comment]
Please reopen or create a new issue with more information and logs  if the crash still occurs.
