### ISSUE TITLE
Overview startpage with empty text after theme change

### ISSUE THREAD

**Issue by dominiczedler** [patzly/grocy-android#695]

**Comment by VNRARA** [comment]
Is this where all fields in the overview page stay unpopulated? I've had that happen a lot without a theme change.

**Comment by patzly** [comment]
@VNRARA Yeah me too, but we still don't know the reason. You can simply refresh the page with swipe down to populate it again, maybe it has to do with database fetching after the fragment was stopped and I hope we get it fixed soon.
