### ISSUE TITLE
SQLite errors not catched

### ISSUE THREAD

**Issue by dominiczedler** [patzly/grocy-android#698]

**Comment by dominiczedler** [comment]
@Atemu You have something big in one of your recipes, please look if you have a large image or sth like that in the preparation description of a recipe (this would explain the exception). I will implement a catch for SQLite errors, that is indeed still missing.

**Comment by dominiczedler** [comment]
@Atemu You have something big in one of your recipes, please look if you have a large image or sth like that in the preparation description of a recipe (this would explain the exception). I will implement a catch for SQLite errors, that is indeed still missing.

**Comment by Atemu** [comment]
Continuation from https://github.com/patzly/grocy-android/issues/652#issuecomment-1547356247

**Comment by Atemu** [comment]
We do indeed have a recipe with an image in its preparation description and the HTML is therefore little more than a huge block of base64.

That should be perfectly valid though since the web UI allows you to embed images into recipe descriptions like this.

**Comment by Atemu** [comment]
Deleting said recipe does indeed fix the issue after clearing the app's data.

**Comment by Atemu** [comment]
1\. Is not an option since images can have arbitrary sizes and current standards will put most images past the 2M mark.
2\. Sounds like a good idea. You could simply mirror the Grocy server's path structure: `/recipe/{id}/preparation.html`. I don't really think we need a database to hold most of this information to begin with since we only query for titles for search.
3\. Sounds hairy to implement and generally unclean.

Related question: Why does grocy-android need to store recipes locally at all? I could understand keeping recipes cached after loading them once to speed up access the next time but why do they need to be fetched and persisted unconditionally?

Also, it seems ChatGPT is being confidently incorrect (as it does); CursorWindow size can be increased on newer API levels: https://medium.com/androiddevelopers/large-database-queries-on-android-cb043ae626e8 (bottom)

**Comment by berrnd** [comment]
> Generally it is not the best practice of the grocy server to store images in the text

Just wanted to add that here for completeness: Recipe pictures (and product pictures, equipment files and Userfield-files) are not stored in the database, but on disk in `<GROCY_DATAPATH>/storage`.

That images (and much more) are also possible to be used in any WYSIWYG editor (like for the recipe preparation text) is a feature of the used editor component [Summernote](https://summernote.org/). By default all embedded files are converted to "BASE64 data URIs" which can lead to very much text data at the end. That's not a general problem for SQLite (which grocy also uses server-side).

Theoretically this could be changed ([doc ref](https://summernote.org/deep-dive/#onimageupload)) and if that's a big problem here, I can have a look (shouldn't be too much todo).

**Comment by VNRARA** [comment]
@dominiczedler @patzly 

Going back to the title of this issue: The app still shows tons of ambiguous network errors when adding a existing or a conflicting conversion or barcode. Does this issue cover that? If not would it be handy to make a list somewhere with all vague errors that aren't handled/shown properly yet to avoid separate issues, put them here as I come across them or do you guess prefer one new issue per error.

**Comment by Atemu** [comment]
@VNRARA that's a different topic. I'd appreciate you open a separate issue on that.

**Comment by dominiczedler** [comment]
@berrnd Thanks for your comment! For now it seems possible to simply increase the limit in our app. So it is not necessary to make things more complex with Summernote (I'm currently using Summernote too in our app). :)

@Atemu 
> Related question: Why does grocy-android need to store recipes locally at all? I could understand keeping recipes cached after loading them once to speed up access the next time but why do they need to be fetched and persisted unconditionally?

We want the possibility in our app to view pages like lists also while being offline. I think there is no difference between caching and storing.

> Also, it seems ChatGPT is being confidently incorrect (as it does); CursorWindow size can be increased on newer API levels

Yes, you're right. I've added some lines which extend the limit to 10 MB (I don't know how much impact on speed this has but I would not make it too large).

Generally, error catching and details view of errors will be strongly improved in the upcoming release. If embedded pictures still exceed the limit in summary of 10 MB, an error while loading will be displayed.
