### ISSUE TITLE
Implement translation contribution possibility

### ISSUE THREAD

**Issue by prohand** [patzly/grocy-android#7]
Hello,

Can you implement french or other langage in this app ?

Thank you

**Comment by patzly** [comment]
A translation contribution possibility is already planned :+1:

**Comment by patzly** [comment]
Maybe [weblate.org](https://weblate.org/en/) as translation platform

**Comment by MrJohnZoidberg** [comment]
Hello, we finally improved our app so it can be translated now via [Transifex](https://www.transifex.com/grocy-android/grocy-android/)!

If you want to translate it into French, you can create an account in Transifex and notify us through it (we then have to approve your request). It is our first translatable project, so we don't have that much knowledge about localization like other developers maybe.  :)

Please report any problems with strings which can't be translated well into French in a separate issue. Maybe we have to improve some of our string structures.

**Comment by MrJohnZoidberg** [comment]
@prohand 
Wow, well done!
We will include your translation in the next release, which will be published hopefully tomorrow. :)

**Comment by prohand** [comment]
Thank you :)
