### ISSUE TITLE
App crashes when trying to edit Masterdata/Products

### ISSUE THREAD

**Issue by edddii** [patzly/grocy-android#70]
Hi! I'm using version 1.8.0 from F-Droid (Izzys Repo). Server is running version 2.7.1

In the menu I can tap "masterdata" and then "products". All fine. When tapping on any product the app crashes.
Adding new products works fine. The problem only occurs when editing existing ones.

This happens on three different devices with different Android versions.

**Comment by patzly** [comment]
Hello! Can you provide us any logs of the crashes? There's no problem on all of our devices, so it's hard to find such a bug without any error messages.

You can find a logging screen in settings if you don't have much knowledge about Android logcat, there you can copy the important lines or you can send us a screenshot here.

Does the demo work in your case? It sounds like there are some malformed numbers in your database...

**Comment by edddii** [comment]
This is the log output: https://bin.snopyta.org/?9d81c313003d633c#7kX5M83CN4m8ffXLANzDWdHMdGwcw5EdLq5WCvQx1LNF

Demo Mode works. So, I guess somethings wrong on my servers installation.

**Comment by patzly** [comment]
We've found the bug: it seems that you have disabled location tracking in the grocy config and we've forgotten to check if the location list is initialized...
We'll fix this as soon as possible, until the next update you can enable location tracking and it should work.
