### ISSUE TITLE
Product image not showing

### ISSUE THREAD

**Issue by WHagenauw** [patzly/grocy-android#700]
Since the last app 3.2 I was hoping to see the pictures I have stored in the grocy server for each product. The place in the app is showing but no picture. Am I expecting something different or is there something wrong.

Wim

**Comment by dominiczedler** [comment]
Is the bug also fixed for you now? For me it was working with that change.

**Comment by WHagenauw** [comment]
Yes it is working now for me too

Thanks

Op ma 22 mei 2023 om 13:40 schreef Dominic Zedler ***@***.***
