### ISSUE TITLE
Buttons are asymmetrical

### ISSUE THREAD

**Issue by VNRARA** [patzly/grocy-android#703]
![Screenshot_20230521_050303_Grocy](https://github.com/patzly/grocy-android/assets/3942672/f3bc3616-a42f-4fee-8036-0b682ee1d6c6)

**Comment by dominiczedler** [comment]
Creating such an issue is ridiculous. Please focus on the important things, we did that because the buttons are all arranged to the right on the home page. If you really think this is an issue, please describe it in a way we can understand the reason.
Thank you for using our app.

**Comment by VNRARA** [comment]
It's two second worth of work in Android studio. Idk how to pr or I'd do it myself. Left margin is not the same as the buttons in the other part above. You focus on a beautiful app and then do stuff like this. 
Alignment to the right doesn't make sense in anyway. 

![Screenshot_20230522_151325_Grocy](https://github.com/patzly/grocy-android/assets/3942672/66bdc823-2bfb-40e2-8fb2-f98861b92d5b)

**Comment by VNRARA** [comment]
It doesn't make sense when two buttons just don't scroll and are an eyesore. It's even more of an eyesore on the samsung A41.

**Comment by patzly** [comment]
@VNRARA The right-aligned buttons are a common design practice in the Material 3 guidelines, e. g. in M3 dialogs the title is left-aligned like in our cards and to make things compensated for the eye the bottom buttons are right-aligned.
As my brother said, the buttons are to long for some languages so we had to make them scrollable. The right padding on the left side is included, but only when scrolled to the left edge of the last button exactly like in the stock overview card. An outer margin for container like you want would cut off the buttons.

**Comment by VNRARA** [comment]
You mention dialog boxes which usually have 2 options or 3 max. Middle and Right or Left Middle Right (equidistant).

It doens't make sense to scroll more to the right AND align to the right as if it were RTL instead of LTR. Also 

![image](https://github.com/patzly/grocy-android/assets/3942672/6ec45298-cb3b-4454-afc5-9183bfd5d55b)

If I just roughly compare the guide to this it still doesn't make sense.

**Comment by patzly** [comment]
![Screenshot 2023-05-22 at 17 52 40](https://github.com/patzly/grocy-android/assets/33599892/9e115a96-fcf6-4876-ba22-a0d5053c48b8)

**Comment by VNRARA** [comment]
android:layout_gravity="begin" 

Is much better for the eye on the main layout list where everything is more cramped. 

![image](https://github.com/patzly/grocy-android/assets/3942672/51e0ef30-e2a2-4c85-8689-b3a948b4a222)
