### ISSUE TITLE
Failed to add conversion with exists already in other product

### ISSUE THREAD

**Issue by VNRARA** [patzly/grocy-android#707]
Removing a used unit allowed a broken unit to break my entire database and a specific unit (renamed to stuk) in my database keeps giving errors.

![Screenshot_20230523_221822_Grocy](https://github.com/patzly/grocy-android/assets/3942672/677f02ad-6d7c-4c24-ac2e-30ccf004ef8e)

**Comment by VNRARA** [comment]
Longer explaination: 

I added a product under parent product cheese (kaas) and it wouldn't add a convertion qu for [pak] to [stuk] (showing red)
Then I deleted the qu [stuk] which broke the database and had to re-add and fix the reference in sqlite. 

[grocy.zip](https://github.com/patzly/grocy-android/files/11548251/grocy.zip)

**Comment by SapuSeven** [comment]
Similar problem here.
Im not sure what happened before, but I captured a screen recording:

https://github.com/patzly/grocy-android/assets/9549504/12256a9f-9b63-46c3-86c4-1215791701d5

The item has a QU of "Bottle".
When trying to add a QU conversion from "Bottle" to something else, every other unit works fine except "Liter".
When choosing a different from-unit, "to Liter" works as expected.

**Comment by VNRARA** [comment]
It's absolutely terrible. At one moment I CAN select a specific unit and not even a closing the app or screen for qu and it stopped accepting that same from/to qu conversion.

**Comment by VNRARA** [comment]
They changed code that made the unit conversion check go globally instead of per product: 

Test product one convert zak - > bak
Test product two convert zak -> bak2 (error)

Which isn't how grocy should work at all. Four days in and no response.

**Comment by patzly** [comment]
@VNRARA We are both studying and working and this is a free-time-only project. All work we do here is fully based on our free time and motivation, and if people point on us saying that we should answer more quickly and that our work is shitty, their issues will very likely be downgraded in our priority queue as our motivation is then simply missing. I hope you understand that so you can take the pressure out of your future messages and be more kindly, or skip our project entirely if you don't appreciate our time and work.

**Comment by VNRARA** [comment]
I try but some changes and your (non-)reactions make me really mad. I really want to help and clearly my passion for this got mistaken for ungratefulness @ #703 . I've contemplated reworking the code in the app and presenting PR's (after learning how). Looking at adding JUnit to prevent regression bugs, but I feel that discussion or other ideas are not wanted here.

**Comment by SapuSeven** [comment]
I think you need to keep in mind that even though this project is open source, it still belongs to someone. If you feel that their decisions are wrong, it's important that you don't demand anything but rather suggest changes and be open to discuss it.
After all, you get all this work _for free_, so if there is any bugs like this, there's no obligation to the developers to respond instantly. It will be addressed when there's time.

**Comment by VNRARA** [comment]
Okay, I code myself and see how much PRs these guys will accept. 👍🏽

**Comment by dominiczedler** [comment]
> But most likely it will be responded with "Creating such a PR is ridiculous"

We will see. ;) 

Feature contributions or bug fixes are highly welcome. I know that the code of this app is not the best in the world, so I hope it is possible to understand for other people.

I will investigate the bug in the next days, all I can say for now is that there was no intention in breaking things. It could be a mistake in one commit, which was meant as improvement for the "error issue" where always a network error was displayed if the conversion exists (catch wrong form content in the UI before the server answers with error).

**Comment by VNRARA** [comment]
Thanks man :) Also for putting up with my sh*t.

**Comment by dominiczedler** [comment]
I've hopefully fixed the bug now.

It was in a method that should find conversions for a given From-QU and To-QU together with a productId. As there are also global QU conversions it should return a global one (if it exists) if the product conversion doesn't exists. The mistake was that it didn't filter for *global* conversions (which don't have a productId in database) but instead looked for any other conversion with these From-QU and To-QU. In your cases you likely have the conversion which failed already in your database in another product. This should work again in the next release or the upcoming nightly build (which you could test to give feedback).

@VNRARA The bug has nothing to do with your original title of the issue. I don't understand what you have made exactly but I can say that our app is not the source of the broken database. It is the API of grocy server which should prevent that and give a HTTP error response then. If it was not the case in your setup and actions, then maybe the API needs some (more) checks for a specific endpoint. If you want to report this in grocy server repository, you should make the actions more reproducible (with english demo server).

**Comment by VNRARA** [comment]
Bro im done bro... Absolutely. It fcking worked perfectly pre 3.2.1 and 3.2.. Im absolutely done bros. Constantly trying to prove my points with u guys
