### ISSUE TITLE
ML kit doesn't scan specific barcode that ZX does

### ISSUE THREAD

**Issue by VNRARA** [patzly/grocy-android#709]
Where do I report that MLkit doesn't scan a specific barcode (minced meat from Albert Heijn). Zxing does scan it just fine and complete. I found to many github pages.

![Screenshot_20230524_172357_Grocy](https://github.com/patzly/grocy-android/assets/3942672/41874071-33c1-4c18-8495-cabb1a38c31a)

![16849419363946058188020773795521](https://github.com/patzly/grocy-android/assets/3942672/5481e8ad-ba50-4000-93b0-46f2ed91f465)

**Comment by dominiczedler** [comment]
I'm sorry, I cannot help you with that. I also don't know where to report such things. Personally I would skip this barcode if it doesn't work and do the work manually.
