### ISSUE TITLE
iOS version please!

### ISSUE THREAD

**Issue by kieric82** [patzly/grocy-android#71]
Hi,

First thank you for this awesome app. I'm currently loving it on my Android device but to be able to replace commercial competitor, I need an iOS app for my wife.

Is it something you're planning and is there a way I can contribute? (I'm kinda nerdy, but not a programmer) I would love to help you either, documentation, translation, beta testing, how-tos or even donation. FYI, my mother-tong is French in case this could help. :) 

Thank you.

**Comment by kieric82** [comment]
Hi,

I understand, thank you very much for your response, much appreciated.

Continue the good work! 👍

**Comment by MrJohnZoidberg** [comment]
@kieric82 
The app Pantry Party has an [iOS version](https://apps.apple.com/app/pantry-party/id1510485755), I didn't try it yet but maybe this is an alternative for your wife. :)

**Comment by kieric82** [comment]
> @kieric82 
> You're welcome! The app Pantry Party has an [iOS version](https://apps.apple.com/app/pantry-party/id1510485755), I haven't tried it yet but maybe this is an alternative for your wife. :)
> 

Thanks for sharing the idea. Already tried it but doesn't work the way your app does. Which isn't suitable for our need. I'll keep following your work and maybe I will be able to convert the wife... ;). Again, thank you for your work. :)

**Comment by Festeazy** [comment]
@kieric82 
https://routinehub.co/shortcut/7061/

**Comment by kieric82** [comment]
> 
> 
> @kieric82
> https://routinehub.co/shortcut/7061/

Thanks, I'll give it a look for sure!

**Comment by MrJohnZoidberg** [comment]
https://github.com/supergeorg/Grocy-SwiftUI
This is a very nice app for iOS and macOS.:+1:
