### ISSUE TITLE
Update broke whole page

### ISSUE THREAD

**Issue by ivannunyadambiz** [patzly/grocy-android#711]
so after running and using grocy for long enough i decided to update using update.sh

the page is now broken. i get the login page, after that i see the stock overview page, but unformatted text only.
if i click "location content sheet" i get a formatted page as usual, but then from there a click on just about anything just gives me more unformatted text.

how do i proceed to diagnose and clean this up? i need this running for kind of obvious reasons...

**Comment by ivannunyadambiz** [comment]
it might be something to do with the fact i have grocy installed in /var/www/html/grocy?

**Comment by ivannunyadambiz** [comment]
in the apache error log i have this when i open the stock overview page:

[Sun May 28 21:33:04.417408 2023] [php7:error] [pid 18182] [client 192.168.2.181:52567] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/grocy/vendor/ramsey/uuid/src/Uuid.php on line 312, referer: http://192.168.2.16/grocy/

**Comment by dominiczedler** [comment]
Please open issues regarding Grocy  server in the appropriate repository (grocy/grocy). This is the repository for the third party android app.

**Comment by ivannunyadambiz** [comment]
wrong tab, my bad
