### ISSUE TITLE
Turn off features like recipes with Home Assistant

### ISSUE THREAD

**Issue by WHagenauw** [patzly/grocy-android#713]
In the server settings I turned off the recipes but in the app I still see it. Is there a way that it will not show on my screen? I can't find any setting for this.

Greetings

Wim

**Comment by dominiczedler** [comment]
Go to the settings page -> server -> reload configuration
or restart your app. I just tested it and recipes are hidden wich FEATURE_RECIPES = false. :)

If this doesn't work, please send me logs if possible.

Greetings

**Comment by WHagenauw** [comment]
Hello

Almost from the beginning of Grocy as add on in Home Assistant I have
turned of recipes (even before I started using the Android app)  in the Add
on Grocy configuration screen with recipes: false (same with batteries). It
is not showing in the home assistant grocy version. So it works there.

I tried what you wrote but is not working. I don't know how to sent you
logs....

Greetings

Wim




Op wo 7 jun. 2023 20:43 schreef Dominic Zedler ***@***.***>:

**Comment by dominiczedler** [comment]
Okay, thanks. Maybe it has sth. to do with Home Assistant then, I have to test it.

**Comment by dominiczedler** [comment]
![image](https://github.com/patzly/grocy-android/assets/27244574/3052a15d-ed5d-49fe-9b09-140e6795922e)

Oh yes, it has something to do with the configurator of Home Assistant grocy add-on...

**Comment by dominiczedler** [comment]
@Auroria-code Seems like this is also your issue, right? ;) So it is not your mistake, it was my mistake but I didn't know that it could be something again with HASS.

**Comment by WHagenauw** [comment]
That means? Have to fill it in like your screenshot in home assistant? Or
something has to change in the app?

Greetings

Wim


Op wo 7 jun. 2023 21:32 schreef Dominic Zedler ***@***.***>:

**Comment by dominiczedler** [comment]
@WHagenauw 

> Thanks for the hint, I will look how I can fix it!

How can you misunderstand that... It's me who has to change something, not you.

**Comment by dominiczedler** [comment]
@WHagenauw Okay maybe it was because I added the sentence to the comment a few seconds later and you only read the mails.

**Comment by WHagenauw** [comment]
I am indeed reading it by mail :)

Op wo 7 jun. 2023 22:05 schreef Dominic Zedler ***@***.***>:
