### ISSUE TITLE
Request: auto grouping

### ISSUE THREAD

**Issue by chuq00** [patzly/grocy-android#715]
Having the option to have all products in the same product group to go into the same location (selectable with all the same options) with say a checkbox on the inventory screen, this will drastically speed up inputting inventory.
Example canned goods all are purchased by the can, go to the same location and same location on use. This way you only are having to add the item quantity and date when adding new canned goods item.

**Comment by dominiczedler** [comment]
I think this is not necessary as there are per product options like "default location". You can set this and the location will be prefilled. And for new products you can create a clonable template product with this location set and tap on the copy button near this template product when a new product barcode was scanned.
