### ISSUE TITLE
Shopping list with pictures

### ISSUE THREAD

**Issue by zunami** [patzly/grocy-android#716]
it's great that you've added pictures to the stick.

pictures would also be great in both shopping list variants. It makes it easier to get around with the shopping trolley.

![IMG_20230609_081429](https://github.com/patzly/grocy-android/assets/4697822/b6c642a7-5ff5-43a4-bdda-cedeccb0a324)

**Comment by dominiczedler** [comment]
Thanks! It is already done, will come in the next release or you can try the latest nightly builds.
You have to activate the field in the selection on the page first (not default enabled).

![image](https://github.com/patzly/grocy-android/assets/27244574/396f08cd-0a0e-4389-a6d2-372a3d0e2cf9)

![image](https://github.com/patzly/grocy-android/assets/27244574/cbfc47e1-7bf6-4163-9fd6-f97fd1c61bb5)

**Comment by zunami** [comment]
nice to hear
