### ISSUE TITLE
External barcode scanner

### ISSUE THREAD

**Issue by FBZH35** [patzly/grocy-android#72]
Hi
Thanks a lot for your great application.
Do you consider to implement a solution base on a bluetooth barcode scanner in stead of the camera ?

Regards
Frédéric

**Comment by patzly** [comment]
Currently we have no good idea how we should implementiert this functionality.
I think the consume and purchase forms are not the problem, there are already text fields. But how should this work in batch mode (which is more important for a Bluetooth scanner I think)?
Maybe there is a way to catch the input without a text field programatically.
Please be patient, maybe we'll buy a cheap scanner to test it on our own.

**Comment by nprill** [comment]
Similar interest here. I have an Android Device with a built in Barcode Scanner. I think the easiest way to implement this would be for the Consume and Purchase forms to be able to search based on a barcode placed into the text box, just like it does on the native Grocy web UI. My integrated scanner just pastes text, just as a bluetooth scanner would. I am happy to assist with testing if needed.

**Comment by MrJohnZoidberg** [comment]
Thanks a lot! Do you mean with "built in Barcode Scanner" the scanner in the Google Camera app or have I misunderstood you?
Your suggestion with the search field sounds good, we will look into it when we have enough time.

**Comment by nprill** [comment]
No, it’s a hardware scanner. See links below. Android just treats it as if it was a USB or Bluetooth Keyboard.

MUNBYN PDA Scanner with Android 7.0, 2D QR PDF417 Honeywell Barcode Scanner with 3G 4G WiFi Mobile Computer, 4'' Touch Screen& Numeric Keypad Rugged Handheld with Docking Station for Inventory System https://www.amazon.com/dp/B0756C3ZN3/ref=cm_sw_r_cp_api_i_-2QyFb5SD93QZ

**Comment by MrJohnZoidberg** [comment]
Do hardware scanners "press" a special key (TAB, ENTER, ...) after entering the barcode in the selected textfield?
Or do they only input the scanned result but nothing else?

**Comment by nprill** [comment]
They can, it is configurable. Mine can do tab, enter, space or nothing. Tab and enter tend to be the most common I believe.

**Comment by basxto** [comment]
The UI could have a text field “manually enter barcode” below the scanner, which gets all pressed keys and opens numbers-only touch keyboard when klicked on?

**Comment by MrJohnZoidberg** [comment]
`v1.9.0` will have initial barcode scanner device support, so in batch mode you can use your scanner device like the camera. But currently the included camera scanner is still active while using a scanner device (I will make a new page for physical scanner devices in `v2.0.0`) and you have to set up TAB as suffix in the scanner device. No other prefixes & suffixes should be active! Else the app could save a wrong barcode with some suffix or prefix included...


PS: I write "scanner device", because I mean USB scanners and bluetooth scanners, they both work like a simple physical keyboard which is connected with Android (I hope that I'm right).

PPS: `v1.9.0` will be released tomorrow or in a few days (depends on @patzly ).

**Comment by nprill** [comment]
Awesome! Thanks for your efforts here. I look forward to testing

**Comment by MrJohnZoidberg** [comment]
It's released now, so can you all please write here, if the initial implementation is working for your devices?
(I know that F-Droid is not released yet, so I'm patient)

**Comment by MrJohnZoidberg** [comment]
I will close this issue for now, because the alpha preview already has great external device support on the consume & purchase pages and I will implement it in other pages (I think shopping list item edit page is still missing), too.
