### ISSUE TITLE
Offline app when opend

### ISSUE THREAD

**Issue by Auroria-code** [patzly/grocy-android#722]
When I open the app it shows offline and I need to refresh once. https://github.com/patzly/grocy-android/assets/82872919/2e8e04a8-af08-487d-a141-a26f6cb9138a

I could test if i can use the app normally even tho it shows this, if needed, i just forget every time. 

My guess is, that it's bc the app is 7
"Sleeping" bc this is only when I open the app after a little while longer

**Comment by dominiczedler** [comment]
Thanks, I'm aware of that but wasn't sure how to solve it. I will look what I can do.

**Comment by Auroria-code** [comment]
Maybe that's stupid.. but you could just not show the message at startup because (i just tested) it fetches the data immediately when you click on any Overview
