### ISSUE TITLE
Adding new item to shopping list reverts to previous shopping list

### ISSUE THREAD

**Issue by jeffse** [patzly/grocy-android#731]
grocy-android v3.2.1
Setup: you must have at least two shopping lists defined.

To duplicate:
1. From the home screen, click "New Entry" for the shopping list.
2. Switch the shopping list to a different one than the default one.
3. Enter the name of a product that doesn't yet exist in the database, and click the "cloud" continue button.
4. At the prompt, select "Create new product and use input as name" and proceed.
5. Set any required properties for the new item and click the "cloud" continue button.

What happens: The shopping list has reverted back to the original list.
What should happen: The shopping list should be the same one that was selected in step 2.

I'm open to trying to fix this one myself. I'm not familiar with the codebase or with Android development in general but would love to give it a try.

**Comment by dominiczedler** [comment]
Thanks for the report! Sorry for the late response, we don't have much time currently.
