### ISSUE TITLE
Bug in confirmation box

### ISSUE THREAD

**Issue by Folders** [patzly/grocy-android#732]
Hello!

First, thank you for your application, it is really great!

I've just seen a small display problem when adding an element (I don't know if it's just a language problem, but I don't think so).

If i add a product with different unity (for exemple, 1 "box" = 250 "gramm"), i have this issue : 
![image](https://github.com/patzly/grocy-android/assets/346299/23921cf1-f0ee-494e-ae20-9e45ab785782)

It need to be 1 "box" or 250 "gramm", not both!

By the way, the final popup and the calculation is fine !
![image](https://github.com/patzly/grocy-android/assets/346299/f8f65616-3793-42d4-9e37-ce3272c5ed74)

Best regards,
Pierre

**Comment by dominiczedler** [comment]
Thanks for reporting! :)

**Comment by Folders** [comment]
Thanks for your job on the app ;)
