### ISSUE TITLE
App crashing on opening after sudden suspension

### ISSUE THREAD

**Issue by alfonso133** [patzly/grocy-android#734]
I noticed that the app crashes on opening from launcher icon if it has been suddenly suspended (or closed too, not sure) after being launched/resumed.
It happened to me in 2 situations:
1 - while I was using the app and periodically locking and unlocking the screen the app crashed when I accidentally pressed the power button instants after unlocking the phone
2 - while I was browsing the apps on my phone I accidentally opened the app, after quickly closing it it crashes if I reopen it

In both cases terminating the app and/or cleaning the cache does nothing and I can still use the app if I don't start it the normal way but go directly to a different activity (like the shopping list). A workaround to fix the situation is to open the app this way, go to settings -> restore settings from server and then restart the app

**Comment by patzly** [comment]
Could you please provide us the log which you can find in the settings after this situation? Without it we don't have any clue :)

**Comment by alfonso133** [comment]
/

**Comment by dominiczedler** [comment]
And Android version and app version too, as well as app source please.

**Comment by alfonso133** [comment]
Android 10
App version 3.2.1 from play store

**Comment by dominiczedler** [comment]
Thank you! We will look into it as soon as we find time for it. Hopefully we can reproduce it.

**Comment by alfonso133** [comment]
No problem, I am a Java developer and can help directly, but unfortunately I don't have much free time now

**Comment by dominiczedler** [comment]
Thanks! The release will be published in the next days.
