### ISSUE TITLE
Add support to Grocy 4.0.0

### ISSUE THREAD

**Issue by tmm360** [patzly/grocy-android#736]
I still didn't try to update server, but because it is a major release with api breaking changes, I suspect that client needs to be updated too. I'm opining this issue only to trace this update.

**Comment by dominiczedler** [comment]
We've finished the work for the new Grocy server version already. It will be released in a few days. Thanks for your attention!

**Comment by TheCDC** [comment]
You can see progress to Grocy 4.0.0 in issue #644

**Comment by patzly** [comment]
@tmm360 Grocy Android v3.3.0 with server v4.0.0 compatibility was released a while ago and I just published v3.3.1 with server v4.0.1 support, so I will close this this now. Have fun with all the new features!
