### ISSUE TITLE
Incorrect Prices in Shopping List if other QU than Stock is used.

### ISSUE THREAD

**Issue by alkuzman** [patzly/grocy-android#742]
If I enter the shopping list item with for example PurchaseQU the prices are incorrect. See for example **Mayo** is 0 Eur for 1l and 4.02 for 1000ml (the factor is correctly set to 1000).
![image](https://github.com/patzly/grocy-android/assets/7229627/17996d1b-9e11-4e57-91e9-f0061cad758c)

I believe the following code in [ShoppingListItemAdapter.java](https://github.com/patzly/grocy-android/blob/85514fffbbf32e14a9549b901526258457be5eef/app/src/main/java/xyz/zedler/patrick/grocy/adapter/ShoppingListItemAdapter.java#L556) takes the `amountInQuUnit` and multiplies it with the `price in stock Qu unit`.
![image](https://github.com/patzly/grocy-android/assets/7229627/5d9d9526-8419-4d7b-afa0-6dad4e3c2c63)

I guess an easy solution would be to use `item.getAmountDouble()` instead of amountInQuUnit.

**Comment by alkuzman** [comment]
Just noticed the same issue is present in the Total price of the Shopping List.

**Comment by dominiczedler** [comment]
Fixed with your contribution (e3673dfdad474b46ee58313bc747cb93afc349e8). :)
