### ISSUE TITLE
New Feature: Shopping List - show unit price with PriceQU

### ISSUE THREAD

**Issue by alkuzman** [patzly/grocy-android#743]
If you use Grocy for managing recipes, then probably you too store most of the products in grams and milliliters. This results in the unit price in the shopping list = 0 for almost all products. Since Grocy 4.0.0 we can use the newly provided PriceQU for showing this price which will make it more relevant in most markets that provide prices in kilogram and liter.

**Comment by dominiczedler** [comment]
Thanks for the suggestion, can you please describe again what is the current state in our app for this and what you expect with an improvement (I didn't understand it enough, sorry).

**Comment by alkuzman** [comment]
I made the same request in the Grocy server repo. It was just released. https://github.com/grocy/grocy/issues/2294
