### ISSUE TITLE
Shopping list amount wrong if product specific QU conversions are present

### ISSUE THREAD

**Issue by alkuzman** [patzly/grocy-android#744]
The product StockQU is in grams. It somehow mixes the Cup QU in the calculation.
![Screenshot_20230802_181151_Grocy.jpg](https://github.com/patzly/grocy-android/assets/7229627/b1a57955-7063-447a-9698-b787456cec9b)

![Screenshot_20230802_181115_Grocy.jpg](https://github.com/patzly/grocy-android/assets/7229627/87562e61-1854-4ea4-8082-492dbada1ba0)

![Screenshot_20230802_181102_Grocy.jpg](https://github.com/patzly/grocy-android/assets/7229627/0f9916ce-42f5-4b87-9475-711887a448ef)

**Comment by dominiczedler** [comment]
Hopefully fixed with #747, please report if there are still bugs.
