### ISSUE TITLE
Wrong amount consumed with some products and their QUs

### ISSUE THREAD

**Issue by 95erFan** [patzly/grocy-android#745]
When trying to consume a certain amount of some products, it seems the amount get mixed up by the QU conversion. As to be seen in the screenshots, trying to consume 10 gram, it consumes 0,0133 gram, which matches the QU conversion 1 gram = 0,0013 bags. Using newest nightly build with server 4.0.0. Works fine when trying in browser.

![Screenshot_20230803_091100](https://github.com/patzly/grocy-android/assets/73084235/bc6996ed-4497-47ae-8e79-4936751c6aef)
![Screenshot_20230803_091108](https://github.com/patzly/grocy-android/assets/73084235/f11fa11d-7d8a-4502-81e9-02e24a9ec05f)
![Screenshot_20230803_091119](https://github.com/patzly/grocy-android/assets/73084235/8f4dde51-5e7d-4dc8-803c-37e5f35ad2ec)

**Comment by alkuzman** [comment]
I guess this is simmilar to https://github.com/patzly/grocy-android/issues/744

**Comment by dominiczedler** [comment]
Hopefully fixed with #747, please report if there are still bugs.
