### ISSUE TITLE
Chores completing/rescheduling broken

### ISSUE THREAD

**Issue by Terrassa5** [patzly/grocy-android#748]
Since the last update on 3rd August It's not possible to complete or reschedule chores in the app, when clicking on a chore no options appear. The only way to complete or reschedule chores is on the web.

This is a big issue because one of the main functionalities used daily is not working.

**Comment by Lapotor** [comment]
In the Error logs no error is throwen, so i think it is missing Link.

**Comment by Zulgrib** [comment]
This specific action works if your server is version 4

**Comment by patzly** [comment]
Please choose a more informative issue title for future issues, dates or update references are not helpful for finding a specific issue. I will discuss the issue with my brother, as @Zulgrib mentions an update is likely required but I'm not sure yet, should be also working with server v3.x.

**Comment by dominiczedler** [comment]
Fixed with https://github.com/patzly/grocy-android/commit/03329d03ba470077a14a089828400af5e74961c2, this was a bug, sorry guys.
