### ISSUE TITLE
Regression : cannot see chores details

### ISSUE THREAD

**Issue by Zulgrib** [patzly/grocy-android#749]
Previously, tapping on a shore would make a panel appear from the bottom of the screen with buttons to report or complete a chore and display details. 

Now tapping on a shore does nothing. 

The new mechanic of sliding a shore reveal the two button but no chore details in sight. 

Chores details can contain important information on how to do a task safely, this regression is dangerous.

**Comment by dominiczedler** [comment]
Was a bug, sorry
