### ISSUE TITLE
Bug: Stock overview last and avg. prices not calculated properly.

### ISSUE THREAD

**Issue by alkuzman** [patzly/grocy-android#757]
Android App: v3.3.1
Server: v4.0.1

![Screenshot_20230816_193111_Grocy.jpg](https://github.com/patzly/grocy-android/assets/7229627/95cf3504-6262-4c93-8d8e-51776d0bee9c)

![Screenshot_20230816_193147_Chrome.jpg](https://github.com/patzly/grocy-android/assets/7229627/09f6977d-ef82-4848-a362-62a774ae0e9e)

**Comment by dominiczedler** [comment]
Thanks for reporting, there has to be something wrong with the new conversion system I've implemented  in v3.3.

**Comment by dominiczedler** [comment]
Fixed with your contribution (e3673dfdad474b46ee58313bc747cb93afc349e8). :)
