### ISSUE TITLE
No delete confirmation when in recipe edit mode

### ISSUE THREAD

**Issue by konwin** [patzly/grocy-android#764]
When you open a recipe in edit mode and press the paperbin icon the recipe will be deleted without confirmation (lost a very detailed recipe because of that :( ). So either there should also be a confirmation dialogue when pressing the paperbin icon or the icon should be removed in edit mode!

Grocy 3.3.1 from f-droid.

**Comment by patzly** [comment]
Right that's a bug, sorry for the inconveniences! :/
