### ISSUE TITLE
Product information is not saved when going back

### ISSUE THREAD

**Issue by Auroria-code** [patzly/grocy-android#765]
I think this worked before.
https://github.com/patzly/grocy-android/assets/82872919/f01ca30a-3b5d-4ed6-a9ce-1129cbd82585

It does work when hitting the back button, but going back with the phones back button (or swipe) doesn't save the Infos.

**Comment by szszoke** [comment]
I can confirm the same thing on version 3.3.1

**Comment by patzly** [comment]
Fixed with ef7504888c5d7abce03f69d0383b59e3dae1f696.
