### ISSUE TITLE
[3.3.1] [minor, UI] More uniform UI language in "consumption-view"

### ISSUE THREAD

**Issue by stheid** [patzly/grocy-android#768]
In many ui elements there are two buttons, one for _consumption_, one for _opening_. However in the main consumption view there is just one button paired with a tickbox. That was quite confusing for me

|currently|highlighted|requested change|
| --|--|--|
|![signal-2023-08-30-092143](https://github.com/patzly/grocy-android/assets/2736207/71cf12f2-d7c8-40d1-a044-e7d62345ae01) |![signal-2023-08-30-092235](https://github.com/patzly/grocy-android/assets/2736207/32b9677f-6ac6-4eed-b3af-0f990b3d0e1c)|![signal-2023-08-30-092143_3](https://github.com/patzly/grocy-android/assets/2736207/5863f79e-e6de-4f4a-8d81-73f2c864ea26)|

**Comment by patzly** [comment]
Thanks! Sadly it's not possible to have multible Floating Action Buttons in Material 3, the design language we use. Instead we would add an icon action to the left menu.

**Comment by stheid** [comment]
having it on the left menu and removed from the list would definetly be an improvement in the visual language. If this is the compromise with the current framework so be it.

Can you link the respective source file that needs to be changed here? i am curious. if i find time i might do a PR
