### ISSUE TITLE
[minor,UI] allow sorting "inventory" and "grocy products" by "added date"

### ISSUE THREAD

**Issue by stheid** [patzly/grocy-android#769]
## Description 
Often times (i guess expecially for new users) i make a small mistake wenn adding data, or i forget to add the expiry date or the price. Than i want to by the products i added or modified today to correct my mistakes in the database. sometimes i also add the products when being in the shop, but after shopping i want to correct or extend some data when i am heading home.

## feature request
It would be good to be able to sort for "added date" or "modified date" for the entries, such to find them faster when i need to do more than one change on the products. I am not sure if this data is stored in the database or if this would only be possible with a change on the grocy backend.

**Comment by patzly** [comment]
Sadly I have to disappoint you, you can see in the example data at _[your grocy url]/api#/Stock/get_stock_ and all other getters that the modification date of items is never stored anywhere.

**Comment by stheid** [comment]
the created timestamp would already help a bit....
