### ISSUE TITLE
Currency in app is different from the server

### ISSUE THREAD

**Issue by RonnyRusten** [patzly/grocy-android#773]
I can't find a way to set the currency in the app.
If it's supposed to use the currency on the server, I have found a bug, otherwise I would like a way to set it in the app.
Server running on Home Assistant is set to NOK, but app is using USD.
Edit
For some reason, the currency changed to NOK in the app.
So this is probably not an issue, but why did it take so long to update the language?
I have been using the app for days and it always showed prices and values in USD.

**Comment by patzly** [comment]
The app fetches the server config only during login. When you change your config after that, you need to perform Settings > Server > Reload configuration, to refetch and apply the new server config to the app. Hope that helps!
