### ISSUE TITLE
Base servings not working properly

### ISSUE THREAD

**Issue by sandervv** [patzly/grocy-android#784]
As title says

When I go into recipes and change the amount of servings on a dish it does not actually increase the amount of ingredients needed and thus clicking 'add to shopping list' means they don't add the right amount.

Grocy server version 4.0.2
App version  3.3.2

**Comment by dominiczedler** [comment]
Did you apply the amount with the "apply" symbol after changing it? Maybe we can change this little symbol to something other like a button to make it more clear.

**Comment by sandervv** [comment]
Oh, I definitely didn't. I don't think I saw the button, but I also don't recall having to do so on previous versions. It does work when doing that.

However, different issue - I see now that when making the recipes, it also failed to correctly save the ingredient count. I always make recipes with a base servings size of 2, and it saved the amount for 1 serving at 2, meaning i have to go up to 4 servings to get the correct amount. This is only on the 4 recipes made on the new version of the app.

Going into the recipe, ingredients list, then going back clicking the serving number and saving it again fixes it.

**Comment by dominiczedler** [comment]
Thanks, you're right with the base servings - I can reproduce it. I've changed the title of this issue because your initial issue will be solved anyway in the next version (redesigned "desired servings" field).
