### ISSUE TITLE
Quickscan for shopping does not respect standard purchase unit

### ISSUE THREAD

**Issue by jacotec** [patzly/grocy-android#791]
Example: Beer
Standard unit and consume unit: Bottle
Purchase Unit: Box

<img width="834" alt="image" src="https://github.com/patzly/grocy-android/assets/3321655/59e7af98-0b8e-46bf-8cc9-79c7c45c73b0">

A box is 20 bottles:

<img width="834" alt="image" src="https://github.com/patzly/grocy-android/assets/3321655/e924942d-2c07-4dfb-b4ed-0d78ad2178e4">

When I scan a bottle with the quick scan button for consume, one bottle is substracted from stock as expected.

When I purchase a box and scan a bottle in quick purchase mode (long press on the scan button), only one bottle is stocked up - not 20 bottles. If the standard purchase unit is a box, quick scan should add 20 bottles in this case.

**Comment by dominiczedler** [comment]
Maybe your stored barcode has the amount of 1 in the server for this product?
