### ISSUE TITLE
Add more Stores to an item

### ISSUE THREAD

**Issue by Eloxan** [patzly/grocy-android#794]
Grocy is a great tool! We buy things in two stores. Some things are only in one store but the most things are in both. When we make a list, it would be useful to sort the list for one store. All items with the store will be displayed. Therfore more then one store have to be in the item.

**Comment by LinuxLover9** [comment]
(I asked this first in [reddit/r/grocy](https://www.reddit.com/r/grocy/comments/17sxr7z/modify_products_while_shopping/) )
I use the Android app while shopping and miss the option to select the store I'm in. I.e. I need to buy meat and cereal. When at the butcher I don't need to see the cereal. While at the supermarket, I would want to see both. 

I've also looked at having grouping by store+section, but then what is the use of the store field? 

Also while shopping, I cannot mod the purchase volume. I.e. there are less items in stock than needed. How can you switch section while shopping for the remaining items? Maybe it's possible to enable a long press, to edit the amount purchased? And Edit the Product group?

Curious how others are using the shopping app?

**Comment by LinuxLover9** [comment]
Ok, it looks like there is a difference in Shopping list and "Shopping mode".
I see you can edit the value in Non-"Shopping mode", and then there is the Purchase option.
When I enter an item in the purchase screen, it's not taken off the shopping list.
I'm confused about how this app is supposed to be used?

**Comment by Eloxan** [comment]
Sorry, i don't want to close the issue.
I need in the Stammdaten the Option to select more then one store.

**Comment by patzly** [comment]
> Ok, it looks like there is a difference in Shopping list and "Shopping mode".
> I see you can edit the value in Non-"Shopping mode", and then there is the Purchase option.
> When I enter an item in the purchase screen, it's not taken off the shopping list.
> I'm confused about how this app is supposed to be used?
> 

Please first try out all your behavior questions in the grocy web app before asking them here. Our Android client uses the grocy API to make the same requests as the server web app, so there shouldn't be any differences in data behavior.
The purchase option for shopping list items is not equal to the purchase page. The first takes the item off the shopping list when the full amount was bought, the second is independent from the shopping list.
If that's the behavior you can also see in the web app, then this is not the correct repo for reporting.

For the butcher problem, you can either create multiple shopping lists for different stores, or you can filter one shopping list for product groups or stores.

**Comment by patzly** [comment]
@Eloxan In Grocy only a default store can be set for a product, please look for an existing issue or open a new one in the main Grocy repo. We cannot implement data-based features in our companion app when the API doesn't support them (aka when the web app also doesn't have the feature implemented). Thanks!

**Comment by Eloxan** [comment]
Ok. Right, thats an issue from the Server app.
I close this issue and post ist in the server app repo.
