### ISSUE TITLE
How to change the display language?

### ISSUE THREAD

**Issue by ErikUden** [patzly/grocy-android#795]
Hello there! 
I saw you write that you maintain a German version of the app! How do I switch to that? My phone's default language is English, but I'd love for some applications to be in German, especially those which I use with other people. 

I did not find the option to switch languages in the user settings! Is it somewhere else?

Sorry for such a basic question - love the app!

**Comment by dominiczedler** [comment]
Hello, just navigate to the Appearance Settings, the language switcher is there. :)
