### ISSUE TITLE
Do not consume multiple items.

### ISSUE THREAD

**Issue by ybbus** [patzly/grocy-android#797]
When I buy several identical items, I only scan one item and increase the number of items before saving them.

The problem with this is that, when I now scan such an item for consumption, multiple items are automatically removed, not just the one I scanned. Sometimes I don't even notice this, and then there is already a discrepancy between the database and the actual inventory.

Is this maybe only a configuration that I have to change?

**Comment by patzly** [comment]
Hi, you should try this with the web interface first. I think this is a server/database bug which would not be related to our app. Please update this issue if you know whether the web interface leads to the same result or not :)

**Comment by ybbus** [comment]
Hi.

It seems that when add add the item to the stock and set the amount of items to let's say 2. Then when scanning to consume this item it also is set to 2.

This is indeed the same behavior on the web interface. 

But it does not make sense for me... Just so that I buy several of the same item, I still do not want to consume all of them at once.
On the other hand I hopefully do not need to scan each item individually...

![image](https://github.com/patzly/grocy-android/assets/1547663/3c1699ff-a790-4217-aab3-92817317a17f)

But yes, then it does not seem to be related to the android app.

**Comment by dominiczedler** [comment]
Yeah you need to get used to the stock concept of Grocy. Either scan every barcode of every stock entry you consume or purchase or enter/check the amount which is prefilled after scan. Or you can use grocy codes for stock entries like Bernd mentioned. (grocy/grocy#2388 for clarification to other people)
