### ISSUE TITLE
OpenFoodFacts Request Issue

### ISSUE THREAD

**Issue by stephanfriedrich** [patzly/grocy-android#800]
hello everyone,
first of all, thank you for your user-friendly android app and all the work.

---

### issue:

unfortunately the data from openfoodfacts, with the product "Vemondo" is not queried correctly and not returned.
the product itself can be found on openfoodfacts with the same barcode.
other queries to foodfacts work, but "Vemondo" does not.

---

### additional data:

working openfoodfacts.json request:
https://world.openfoodfacts.org/api/v0/product/4056489703990.json

**Comment by stephanfriedrich** [comment]
![Screenshot_20231124-111424](https://github.com/patzly/grocy-android/assets/2052955/c39f980f-064d-4459-a511-4e38e8dfe197)
![rn_image_picker_lib_temp_15f4cb70-8a2b-4ec8-b5b1-0f54959f089f](https://github.com/patzly/grocy-android/assets/2052955/56d44abb-93a9-45d3-9696-c67be886d709)
![rn_image_picker_lib_temp_e71ac161-044a-41e7-b7b3-dd573a6e395a](https://github.com/patzly/grocy-android/assets/2052955/c8a44aca-9e41-479e-a52e-4846a600c261)

**Comment by stephanfriedrich** [comment]
![Screenshot_20231124-111424](https://github.com/patzly/grocy-android/assets/2052955/bd7027bf-66e2-438b-bc5a-5b854df16035)
![rn_image_picker_lib_temp_15f4cb70-8a2b-4ec8-b5b1-0f54959f089f](https://github.com/patzly/grocy-android/assets/2052955/4dae0879-ef0b-408c-a01f-6145bad39f42)
![rn_image_picker_lib_temp_e71ac161-044a-41e7-b7b3-dd573a6e395a](https://github.com/patzly/grocy-android/assets/2052955/24c0f19b-d73b-4bb4-8a1a-18f00bdaf4a0)

**Comment by dominiczedler** [comment]
Thanks. But you can see by yourself in the JSON data that the product is not named properly. The name is missing in all languages and the brand is the only thing which could be filled in our app. But the brand won't be taken from the app (currently). So we can't do anything, instead you can improve the product by yourself in OFF.
