### ISSUE TITLE
issue in the creation of similar products 

### ISSUE THREAD

**Issue by stephanfriedrich** [patzly/grocy-android#802]
hi,
thanks for your app, great work.

as a user, i would like to be able to enter similar products (black beans) with different packaging, e.g. pickled in a can or dried in a bag.

on the one hand, the suggestion from openFoodFacs disappears when scanning, and on the other hand, it is not possible to create a new product, but only to select an existing product. 

## what did i expect

i can create similar products at the same time, but with different properties. dried green beans and canned green beans.

**Comment by dominiczedler** [comment]
If you want to create a new product but the option is not available, you are on the wrong page. Consume page doesn't display this option, you have to go to purchase page. For you question there are two ways:

- Use the quantity units for a product and set the barcodes to the respective unit
- Tap the "Duplicate product" button on the page where you choose the product after scanning a new barcode on purchase page. Then you can create a new product but this has the properties of the other product and there you could set another quantity unit.
