### ISSUE TITLE
Crash when trying to setup / Invalid Product / Crash when opening settings

### ISSUE THREAD

**Issue by mhilcher** [patzly/grocy-android#806]
Since Version 3.4. all these bugs appear:

Every product is shown invalid when trying to add it to the stock.
Doesn't matter if it is a new product or an already configured one.
The name of the product is in the list and selectable, the amount can be entered and that's all.
Every action then is stopped and "Invalid product" (Ungültiges Produkt in german) is shown.
Doing it directly in the UI of the server works.

When trying to open the settings, the App crashes.
Every time.

I reinstalled the app after deleting the cache and there's no chance for setting up the server again.
When trying to scan the QR code the app crashes.
When entering the data manually the app crashes.

Tried it with the official version from the Play Store and with the latest nightly build.

Had to go back to 3.3.2 then everything is working again.

Poco X3 Pro
Android 13

**Comment by patzly** [comment]
Thanks, I'm already working on the fix!

**Comment by mhilcher** [comment]
> Thanks, I'm already working on the fix!

Hi,

I am still running server version 3.3.2, maybe that's the problem.
But the app updated in the background to 3.4 automatically and that could be a problem for all running server version 3.3.2

**Comment by patzly** [comment]
A fix is already on the way.

**Comment by mhilcher** [comment]
Thx very much, seems to work like a charm now
Great work
