### ISSUE TITLE
Recipe list shows only dates instead of names

### ISSUE THREAD

**Issue by mikedolx** [patzly/grocy-android#808]
Hi,

since the last upgrade from the playstore i have a weird behavior in the recipe list. The list shows only dates instead of names. I have tried to find any settings to change that, but i couldn't find anything.

Here is a screenshot of my grocy android app:

![Screenshot_20231202-112011_Trebuchet](https://github.com/patzly/grocy-android/assets/15738117/e915b5bc-3e3b-4a6b-acf6-8bb132dc881b)

This is how my grocy frontend looks like on my android browser.

![Screenshot_20231202-112057_Trebuchet](https://github.com/patzly/grocy-android/assets/15738117/301d2425-0a77-47ac-9ed8-21e53208e026)

### Grocy server
- version: 4.0.3
- self-hosted within a proxmox lxc container
### Grocy App
- 3.4.1 on Android 13 (Lineage OS with gapps)

Any idea whalt could be wrong?

**Comment by AlesZurek** [comment]
I have also this issue.
I suppose it is now showing the recipes but all meals from the meal planner (as I have a lot more records there than recipes and there was record for almost every day).

**Comment by mikedolx** [comment]
> I have that too, but the Recipes are not on the server at all... Like I have my normal ones who are on the server, and then there are these date ones who are just on the app, they are additional.
> 
> I have a Home assistant version

Can confirm that. After scrolling a bit in the app, could find my "original" recipes.
Could those recipes be some sort of versioned variants? Maybe the app lacks some filtering?

**Comment by AlesZurek** [comment]
> > I have that too, but the Recipes are not on the server at all... Like I have my normal ones who are on the server, and then there are these date ones who are just on the app, they are additional.
> > I have a Home assistant version
> 
> Can confirm that. After scrolling a bit in the app, could find my "original" recipes. Could those recipes be some sort of versioned variants? Maybe the app lacks some filtering?

Yes I can also confirm that recipes are there but at the end of the list.

**Comment by dominiczedler** [comment]
A new version will be released in the next days. I fixed the bug right after the last release but my brother is just a bit lazy with a new release or has other important things in his study life.
