### ISSUE TITLE
How to swap between long and short press behavior

### ISSUE THREAD

**Issue by alexandru0-dev** [patzly/grocy-android#810]
Long press by default is purchase, short press is consume.
Is it possible to swap those?
Found no options about this, not even in the behavior settings.

**Comment by dominiczedler** [comment]
Is consume page not the page you would use more than the purchase page?

**Comment by dominiczedler** [comment]
If we would add an option for everything, the app would be too cluttered and hard to develop. So please take the time to press the button ~0.5 seconds longer if you need purchase quick mode with scanning...
