### ISSUE TITLE
Feature Request: Manual Offline mode for shopping list

### ISSUE THREAD

**Issue by mikedolx** [patzly/grocy-android#816]
Hi,

i've already saw some bugs and feature requests regarding the offline mode for the shopping list (speaking only of marking an item as done and resyncing after going back online). 
So apparently, here in germany most of the grocery stores have really bad mobile coverage indoors and the open wifi is not always that reliable. So often i have the following issue:
My mobile data (EDGE indoors) is doing some ping-pong with the wifi of the grocery store, which leads the app to permanently attempting to sync the shopping list - i guess the app thinks the internet is back an tries to sync. But the result is, that the app is constantly trying to sync the shopping list, showing the spinning circle (of death). 

**Feature Request**: I'd like to have  a small button in the shopping list, that let's me toggle the offline mode for the shopping list. So before i enter a grocery store i switch to the offline mode, and when i leave the store i switch back to online mode and let grocy sync the list.

I know, that i theoretically could switch my phone into flight mode, but i like to be in contact with my spouse (for inquiries :-)). Apperently, messenger like whatsapp and threema seem to work with a bad internet connection (no offense towards grocy android :-)).

What do you think?

**Comment by patzly** [comment]
For me it's the same experience in my go-to grocery store, so I think this is a good suggestion! (But this has to be done by my brother, so please Dominic :D)
