### ISSUE TITLE
Feature Request: Deep linking

### ISSUE THREAD

**Issue by mikedolx** [patzly/grocy-android#817]
Hi,

I'd like to enable or simplify the integration of the grocy-android app into other apps (and workflows), by allowing deep linking. The idea is to have a parent todo-list in another app, where shopping with grocy is one action point. By clicking a link from the todo-app i can directly switch to the shopping list of grocy-android. This would allow me to create daily todo lists, that allow me to easily jump to grocy.

### Example Markdown
```markdown
- [ ] Laundry
- [ ] Post Office
- [ ] [ALDI](app://grocy.info/shopping-list)
- [ ] Disney Land
```

See also:
- https://developer.android.com/training/app-links/deep-linking
- https://www.geeksforgeeks.org/deep-linking-in-android-with-example/

What do you think?

**Comment by patzly** [comment]
Deeplinks are already used in the app, so maybe this should not be that hard.

**Comment by dominiczedler** [comment]
Hey, this should already be possible:

grocy://shoppingListFragment

Doesn't this work for you?

**Comment by mikedolx** [comment]
> grocy://shoppingListFragment

This one worked out of the box! Amazing!

Thanks a lot!!

**Comment by mikedolx** [comment]
Issue can be closed
