### ISSUE TITLE
Crash on all scanning attempts

### ISSUE THREAD

**Issue by Akron** [patzly/grocy-android#820]
Thank you for this software!
I guess this is specific to my phone, or is there anything I do obviously wrong or is missing (permission, service ...), that no scanning works for me? It crashes with the following error:

```
01-07 11:15:41.959   792   792 E AndroidRuntime: FATAL EXCEPTION: main
01-07 11:15:41.959   792   792 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 792
01-07 11:15:41.959   792   792 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.view.View xyz.zedler.patrick.grocy.databinding.FragmentPurchaseBinding.dummyFocusView' on a null object reference in method 'void androidx.activity.ComponentDialog$$ExternalSyntheticLambda1.run()'
01-07 11:15:41.959   792   792 E AndroidRuntime: at androidx.activity.ComponentDialog$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:23)
01-07 11:15:41.959   792   792 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
01-07 11:15:41.959   792   792 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
01-07 11:15:41.959   792   792 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:201)
01-07 11:15:41.959   792   792 E AndroidRuntime: at android.os.Looper.loop(Looper.java:288)
01-07 11:15:41.959   792   792 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7937)
01-07 11:15:41.959   792   792 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
01-07 11:15:41.959   792   792 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
01-07 11:15:41.959   792   792 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
```
Running Grocy Android v3.5.0 on Android 13

Tested both with
- Grocy-Server v4.0.3 (HomeAssistant AddOn - no https)
- Demo-Server

Crashes with any bar code.

**Comment by sn0west** [comment]
Same problem here,
Yesterday I made a big grocery trip with a lot of products. I started scaning all products that I bought in the shop. Some suddenly it did not scan anymore. Everytime I scaned a new product the app crashed complitly.
My version are
Android OS: 12
App Version: 3.5.0
Server version: 4.0.3

I tried to clear the cache, tried to reinstall the app, also tried to downgrade the app, but it crashes all the time. If I can provide you with a log, let me know how to do it.

Thanks

**Comment by patzly** [comment]
@sn0west Log would he helpful, you can find it in settings.

**Comment by sn0west** [comment]
`
--------- beginning of crash
01-12 06:34:49.035 19534 19534 E AndroidRuntime: FATAL EXCEPTION: main
01-12 06:34:49.035 19534 19534 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 19534
01-12 06:34:49.035 19534 19534 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.view.View xyz.zedler.patrick.grocy.databinding.FragmentPurchaseBinding.dummyFocusView' on a null object reference
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at androidx.activity.ComponentDialog$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:23)
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-12 06:34:49.035 19534 19534 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: FATAL EXCEPTION: main
01-12 06:35:03.819 19624 19624 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 19624
01-12 06:35:03.819 19624 19624 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.view.View xyz.zedler.patrick.grocy.databinding.FragmentPurchaseBinding.dummyFocusView' on a null object reference
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at androidx.activity.ComponentDialog$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:23)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-12 06:35:03.819 19624 19624 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: FATAL EXCEPTION: main
01-12 11:58:27.470  6599  6599 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 6599
01-12 11:58:27.470  6599  6599 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.view.View xyz.zedler.patrick.grocy.databinding.FragmentPurchaseBinding.dummyFocusView' on a null object reference
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at androidx.activity.ComponentDialog$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:23)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-12 11:58:27.470  6599  6599 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: FATAL EXCEPTION: main
01-12 11:59:09.868  6815  6815 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 6815
01-12 11:59:09.868  6815  6815 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.view.View xyz.zedler.patrick.grocy.databinding.FragmentPurchaseBinding.dummyFocusView' on a null object reference
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at androidx.activity.ComponentDialog$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:23)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-12 11:59:09.868  6815  6815 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: FATAL EXCEPTION: main
01-12 17:35:27.386  3884  3884 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 3884
01-12 17:35:27.386  3884  3884 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.view.View xyz.zedler.patrick.grocy.databinding.FragmentPurchaseBinding.dummyFocusView' on a null object reference
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at androidx.activity.ComponentDialog$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:23)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-12 17:35:27.386  3884  3884 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`

**Comment by dominiczedler** [comment]
Hey guys, I've found the bug - thanks for reporting. It seems that it only occur on some devices, because it has something to do with the performance (how fast the code of the app is executed). We will release a new version for that, let me just work a bit further on the other issues this weekend. The next nightly build APKs here on Github will already contain the fix, so you may try these for testing or to scan your products.

Sorry for any inconvenience, we hope you like our app anyway.

**Comment by sn0west** [comment]
Your app us excelent! Thanks for your work.
