### ISSUE TITLE
App Crashes When Adding a New Product Without Scanning Barcode - IllegalArgumentException in ScannerMLKit

### ISSUE THREAD

**Issue by Payne530** [patzly/grocy-android#821]
I'm adding a product that's been setup. I have not scanned a barcode in this case. Once I press the purchase button, the app crashes.

This is the first time I have purchased any of this product.

The item still seems to get purchased though...

I turned on the debugger and ran through the process again.

`--------- beginning of crash
01-07 09:31:09.361  9477  9477 E AndroidRuntime: FATAL EXCEPTION: main
01-07 09:31:09.361  9477  9477 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 9477
01-07 09:31:09.361  9477  9477 E AndroidRuntime: java.lang.IllegalArgumentException: The detector does not exist
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.1.0:6)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.scanner.EmbeddedFragmentScannerMLKit$$ExternalSyntheticLambda0.accept(R8$$SyntheticClass:31)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at androidx.camera.mlkit.vision.MlKitAnalyzer$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:26)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-07 09:31:09.361  9477  9477 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
--------- beginning of main
01-07 09:31:11.657  9801  9801 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.`

**Comment by Payne530** [comment]
And of course it's intermittent??? 😩

**Comment by Payne530** [comment]
I can't seem to reproduce this.

**Comment by dominiczedler** [comment]
We are aware of this type of crash with the ML Kit scanner. Which version do you use? The Google Play package is not up-to-date yet, the latest published Github version (with ML Kit) should fix these crashes. You can create a new issue, if you still experience such a crash with the latest version.

My brother will update the app in the Playstore soon, there were legal issues due to new Google policies.

**Comment by Payne530** [comment]
I'm using version 3.4.1

OK, that sounds good. :)
