### ISSUE TITLE
[Bug] Keyboard hides Notes in Purchase mode.

### ISSUE THREAD

**Issue by voronind-com** [patzly/grocy-android#822]
https://github.com/patzly/grocy-android/assets/22127600/fe59335c-a6d5-4508-b11e-6d9e98de488b

When you Purchase stuff, you have to type Notes blind, because you can't scroll down to make Notes visible.

**Comment by patzly** [comment]
Thanks a lot! I just saw that all pages are affected... Will hopefully be fixed in the next verison.
