### ISSUE TITLE
Recipe total count is incorrect

### ISSUE THREAD

**Issue by trevermah** [patzly/grocy-android#827]
The total recipe count does not match the actual recipe count.

This was accurate until the meal plan update so I think the count is adding the related entries as mentioned in another issue that was fixed. See 
https://github.com/patzly/grocy-android/issues/808

![Screenshot_20240116-055950](https://github.com/patzly/grocy-android/assets/106401307/15bebeae-2b09-4bf3-a99e-bce64c16b746)
![Screenshot_20240116-055930](https://github.com/patzly/grocy-android/assets/106401307/34f07ffa-1b4a-4173-8a57-e71efebc0110)

Server version 4.0.3
App version 3.5.0

**Comment by dominiczedler** [comment]
Thanks!
