### ISSUE TITLE
Add support for server 4.1.0

### ISSUE THREAD

**Issue by winnieXY** [patzly/grocy-android#837]
After updating the server from 4.0.X to 4.1 I'll get some warnings regarding incompatibilities of grocy-android.

Would it be possible to make grocy-android compatible again?

With best regards
Patrick

**Comment by dominiczedler** [comment]
Thank you, the next version will be released in a few days. :)

**Comment by rhl2401** [comment]
@dominiczedler Looking forward to the update. Do you need any help in regard to this issue?

**Comment by dominiczedler** [comment]
@rhl2401 Sorry, it's been a busy week, my brother will release the version as soon as possible. Have already made the commit, so everything is good - thanks for your offer though!
