### ISSUE TITLE
Donation button

### ISSUE THREAD

**Issue by alex01at** [patzly/grocy-android#838]
1) I miss a donation button for the developer of the app!
2) When would "aufgaben" implement in the app?
3) What is the app in playstore for 7.99€?

**Comment by patzly** [comment]
Hi, you can read a message about that in the app when you try to change the scanner in settings :)
A donation button sadly is not officially allowed by Google as a payment always has to unlock some features in an app.

**Comment by patzly** [comment]
Tasks are already implemented, you can find them on the start page. Else you have disabled them in your server configuration and have to enable them there first.

**Comment by alex01at** [comment]
Sorry my mistake. It works from frontpage!
But if you try to navigate from "Stammdaten" (last link) it come a toast with "coming soon". 

back to topic:
Why you don't create a button on your website with "donation" ;-)

**Comment by patzly** [comment]
Ah you mean chores (Hausarbeiten)? That's different from tasks (Aufgaben), tasks is implemented and chores is indeed not finished in master data I think. Maybe Dominic can work on it when he has tine again :)
If I would place a paypal donation button on my homepage, Google would take the app down with the explanation that there is a link to an external payment service when a user visits the homepage from the app...

**Comment by vanMacG** [comment]
In #460 and #571 there are mentioned two paypal adresses ([1](https://www.paypal.me/dozedler), [2](https://www.paypal.me/pzedler)). If this is still valid ppl could use this 😄

**Comment by carsonbird** [comment]
Hmm. Is the same true for a donation link on the GitHub README for the unlock kit? Happy to support you.

**Comment by patzly** [comment]
Where exactly is the donation link you mean? The problem with donation links is that Google takes an app down when the developer mentions a payment method anywhere which isn't Google Play...

**Comment by carsonbird** [comment]
Yeah, I'm just wondering if including a donation link on the github
README, and not soliciting about it violates the terms as well. Not a big
deal, the Play Store is easy and Google can have their cut.

--Carson

**Comment by patzly** [comment]
The README is directly callable from the app's about section which was sadly enough in similar cases in the past, so a link in the README would lead Google to a temporary block with the statement "you can navigate to About, then scroll down, then tap on the link and voila, on the homepage on the bottom there is a donation link to an external payment service which is illegal".
