### ISSUE TITLE
Full offline mode support

### ISSUE THREAD

**Issue by Nasreddine** [patzly/grocy-android#84]
Hi,

Thanks for this awesome work. 
I want to know if you intend to fully support offline mode ? 
Til now, I think you're supporting only offline mode for shopping list.

Kind regards.

**Comment by patzly** [comment]
Hello! Sadly we have no plans to make the app available for offline usage because all data is stored and processed on the server instance.
It would be an entire new big (and very hard) project to develop an app that works without the server application.
