### ISSUE TITLE
Add new product

### ISSUE THREAD

**Issue by alex01at** [patzly/grocy-android#841]
I'm not sure, maybe that's how it's supposed to work...
When I create a new product, I can enter all the required properties. After saving for the first time, you will be asked for the best before date. When I enter this, the product is ready and the start screen appears.
If I press "cancel" I can enter the price and quantity purchased as desired.
Is it wanted like that?
Tested with Samsung Galaxy S23 Ultra and Samsung Fold 3

**Comment by patzly** [comment]
Yes, that is intended. You can read the info for the so called quick mode when you tap on the help icon in the top app bar on the purchase page. In your situation quick mode leaves the price empty and uses "default amount for purchase" from user settings for the amount.

**Comment by dominiczedler** [comment]
The price field will be filled with the last price, if it was entered before in another purchase. :)
