### ISSUE TITLE
Add best before with camera

### ISSUE THREAD

**Issue by alex01at** [patzly/grocy-android#842]
I don't know if it's possible or not.
Add or change best before date with smartphone camera.

greet

**Comment by dominiczedler** [comment]
Hey, this is not easy to implement because it would require a text recognition package in our app (which increases size to another level) and reading of many available formats.

**Comment by patzly** [comment]
Also many best before dates are printed with small dots instead of solid characters on bottles, tins and similar products and OCR libs probably wouldn't recognize the text correctly.

**Comment by patzly** [comment]
I've decided to close this issue because often it's even hard for humans to read a best before date on products so I think manual input is faster than always correcting an incorrectly auto detected date.

**Comment by spiritwiz** [comment]
I am considering the following approach

1. Use OCR to parse raw text
  => with ML Kit Text Recognition v2 API, which is an on-device android feature
2. Generate possible answers using GenAI
  => with user's own API key
3. User select the right answer

Is anyone interested in collaborating on this?
