### ISSUE TITLE
Please include the latest Swedish translations in the next release 

### ISSUE THREAD

**Issue by schteff** [patzly/grocy-android#864]
Hi!

It looks like it was a while ago the Swedish translation was updated in the app. Many strings that were translated years ago in the translation app are still in English in the Android app. I provided some new translations but many strings I wanted to translate were already translated. 

Just a quick reminder if you already had it on the agenda.

I'm trying to use grocy mainly for chore tracking for my kids which is why I need the Swedish strings.

**Comment by dominiczedler** [comment]
Hey, thanks for the reminder! The translation progress needs to be higher than (or equal to) 80% so this should be the reason why no translations were updated for such a long time.

Thanks for using our app with your family! The Swedish translation should be up to date in the next release.
