### ISSUE TITLE
Battery drains very quickly 

### ISSUE THREAD

**Issue by amarradi** [patzly/grocy-android#867]
Since I installed the app for the first time 5 days ago, my battery has been draining very quickly. Can you please take a look at the topic of resources and possibly improve the battery utilization. I don't know if this is a bug or if I'm using grocy incorrectly

**Comment by patzly** [comment]
Hi, I think this sadly isn't a bug we can address. Android sometimes seems to run a random app incorrectly and drains the battery with it, for me it was Firefox Focus on Android 15 beta until I uninstalled it.
You can try disabling the notification feature in the app settings, but if this isn't the cause then our app hasn't any remaining background feature and should not use any battery in background. You also should try to update your system if an update is available or uninstall and reinstall Grocy, I hope you can solve it somehow :/

**Comment by amarradi** [comment]
After the Android 14 update, it runs much more economically. I think it's fine like this

**Comment by patzly** [comment]
That's perfect, glad it works now!
