### ISSUE TITLE
Save data locally and then synchronize it?

### ISSUE THREAD

**Issue by amarradi** [patzly/grocy-android#868]
I have installed grocy locally on the raspi and set up the service locally without going outside. Is there a possibility that I can also "shop" in the supermarket with the app, i.e. the products are saved locally on the smartphone and then synchronized?

**Comment by dominiczedler** [comment]
Hey, this would be hard to implement as the app only uses the server API - we designed the shopping mode for that which also works offline because item states are preserved and then synced when online again. 

Related older issues are for example #5, #19 and #84.
