### ISSUE TITLE
[BUG] Incorrect Stock notification

### ISSUE THREAD

**Issue by oxigen-dev** [patzly/grocy-android#898]
The quantity of not fresh items is incorrect.

It shows that 5 products are not fresh:

![image](https://github.com/user-attachments/assets/e0b13cf4-dca9-4bb4-a821-5b00f0f2e41f)

In reality only 3 are not fresh:

![image](https://github.com/user-attachments/assets/9a974e04-ef17-40df-9d5a-19a8c1e3d001)

**Comment by patzly** [comment]
Thanks! I just tried to reproduce this with the API and it seems the web interface also displays the wrong number (screenshot taken after click on "3 products are overdue"):

![Screenshot 2024-12-25 at 17 39 47](https://github.com/user-attachments/assets/83e3ced0-17e8-434b-9114-c444f44272dc)

After studying the API response I saw the mistake: the expired item is also included in the overdue items, maybe a bug or a feature. But this doesn't fully explain your screenshot, 2+1 and 1 only accumulates to 4 and not 5... I think you maybe took the screenshot after an item was consumed or something was cached wrongly. Hopefully my fix fixes the bug for you.
