### ISSUE TITLE
Consume fails often

### ISSUE THREAD

**Issue by teitrand** [patzly/grocy-android#96]
When I am trying to consume certain products or open products by using the barcode-button on the front, the app gives me an error even though the product is in stock, the barcode is linked and everything should be fine.

If I manually find the product and consume it, it is no problem.

It is not an consistent error, so it is hard to tell why this happens. I have no connection issues while using the app, so I think it should be good.

**Comment by patzly** [comment]
Hi! Does the error message only say "An error occured"?

**Comment by teitrand** [comment]
Yes

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MrJohnZoidberg** [comment]
After enabling logging and "Show info logs" in the app settings, you might see the exact error message in the logs after the error occurs again. If not, please let us know.
We will improve the error output in the next major version.

**Comment by teitrand** [comment]
--------- beginning of crash
09-06 09:42:04.320 10171 10171 E AndroidRuntime: FATAL EXCEPTION: main
09-06 09:42:04.320 10171 10171 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 10171
09-06 09:42:04.320 10171 10171 E AndroidRuntime: java.util.ConcurrentModificationException
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at c.a.a.a.b.y$a.publishResults(SourceFile:4)
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:284)
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
09-06 09:42:04.320 10171 10171 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
--------- beginning of system
--------- beginning of main
09-09 23:29:05.506 21581 21581 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-09 23:29:05.820 21581 27763 I Camera  : close camera: 0, package name: xyz.zedler.patrick.grocy
09-09 23:29:05.821 21581 27763 I HwCameraUtil: notifySurfaceFlingerCameraStatus : isFront = false , isOpend = false
09-09 23:29:06.011 21581 21581 I HwViewRootImpl: removeInvalidNode jank list is null
09-09 23:29:06.116 21581 21581 I stock   : download QuantityUnits: [QuantityUnit(Stykk), QuantityUnit(Pakke), QuantityUnit(Flaske), QuantityUnit(Pose), QuantityUnit(Gram), QuantityUnit(Kilo), QuantityUnit(Liter), QuantityUnit(Desiliter), QuantityUnit(Glass), QuantityUnit(Boks), QuantityUnit(Teskje), QuantityUnit(Spiseskje), QuantityUnit(Hektogram)]
09-09 23:29:06.149 21581 21581 I stock   : download ProductGroups: [ProductGroup(Drikke), ProductGroup(Bakervare), ProductGroup(Hermetikk), ProductGroup(Meierivarer), ProductGroup(Tørrvare), ProductGroup(Frossenmat), ProductGroup(Kjøtt), ProductGroup(Frukt/grønt), ProductGroup(Vaskemidler), ProductGroup(Husholdning), ProductGroup(Hygiene), ProductGroup(Annet), ProductGroup(Snacks), ProductGroup(Pålegg), ProductGroup(Posemat), ProductGroup(Krydder), ProductGroup(Frokostblanding)]
09-09 23:29:06.166 21581 21581 I stock   : download Locations: [Location(Kjøleskap), Location(Fryser), Location(Matskap), Location(Kjeller), Location(Kjøkkenskap), Location(Bad), Location(Vaskerom)]
09-09 23:29:06.167 21581 21581 I stock   : download ShoppingListItems: [ShoppingListItem(226, null)]
09-09 23:29:06.406 21581 21608 W libEGL  : EGLNativeWindowType 0x788b722a50 disconnect failed
09-09 23:29:06.693 21581 21581 I stock   : download StockItems: [StockItem(Karbonadekaker First Price), StockItem(Potetmos med gressløk og melk), StockItem(Vann), StockItem(Maiskorn 3-pack), StockItem(Sukker), StockItem(Aluminiumsfolie), StockItem(Pizza- og bakeark), StockItem(Brødposer), StockItem(Friele Filterkaffe original), StockItem(Bomullspinner (Q-Tips) ), StockItem(Grovbrød), StockItem(Brokkoliblanding), StockItem(Lapskausblanding), StockItem(Strandamør), StockItem(Meksikansk gryte), StockItem(Bali kyllinggryte), StockItem(Blomkål og brokkolisuppe), StockItem(Barilla Pesto alla genovese (grønn) ), StockItem(Agurk), StockItem(Tannkrem), StockItem(Kjøttpølse uten skinn), StockItem(Kyllingfilet First Price), StockItem(Avfallsposer med håndtak (First Price) ), StockItem(Norvegia ost 1.3 kg), StockItem(Sun 3i1 Glansmiddel), StockItem(Cornflakes 500g), StockItem(Strandamør snacks 250g), StockItem(Soft flora), StockItem(Flytende håndsåpe), StockItem(Biff), StockItem(Hjortekjøtt), StockItem(Fun light Cloudy Apple), StockItem(Folkets Pepperoni Pizza), StockItem(Oppvaskmaskintabletter), StockItem(Toro Jegergryte), StockItem(Dr Greve Sensitive Intimvask), StockItem(Trønderfår), StockItem(Polpa finissima), StockItem(Nypoteter), StockItem(Idun tomatketchup), StockItem(Kjøttdeig 600gram), StockItem(Comfort tøymykner mandarin), StockItem(Melange), StockItem(Kyllingkjøtt), StockItem(Dampamår av hjort), StockItem(Poteter), StockItem(Eldorado Utsteinede Oliven svart), StockItem(Siktet hvetemel 2kg), StockItem(Gudbrandsdalost), StockItem(Crème fraîche), StockItem(Viltsaus), StockItem(Jegergryte), StockItem(Nugatti), StockItem(Mors hjemmebakte Pizzagjær), StockItem(Coop kjøttkakesaus), StockItem(Xtra bearnaisesaus), StockItem(Xtra makaroni), StockItem(Pizzasaus coop), StockItem(Pizzapepperoni), StockItem(Crème Fraîche), StockItem(Avfallsposer 46L Coop), StockItem(Coop rømmedressing), StockItem(Tine lettmelk 1.75L), StockItem(Toro Lasagne Italiensk), StockItem(Saft), StockItem(Sriracha Chili Saus), StockItem(Søppelsekker), StockItem(Engangshansker), StockItem(Gudbrandsdalsost 1kg), StockItem(Folie), StockItem(Lapskausblanding Norrek 2kg), StockItem(Farfalle), StockItem(Fusilli), StockItem(Pasta penne), StockItem(Regal siktet hvetemel 2 kg), StockItem(Pommes frites 1.2kg), StockItem(Wokblanding coop), StockItem(Påleggsskinke), StockItem(Hel pepper sort), StockItem(Ming Grøtris), StockItem(Grønnsaksbuljong), StockItem(Kjøttbuljong), StockItem(Rapsolje), StockItem(Kanel), StockItem(Leverpostei), StockItem(Kardemomme), StockItem(Vaniljekrem), StockItem(Melis Dansukker), StockItem(Coop Kokosmasse), StockItem(Kokosolje), StockItem(Laksefilet naturell 4pk), StockItem(Hjortesteik), StockItem(Xtra baconost), StockItem(Idun tomatketchup Hot chili), StockItem(Loreal thermic resist), StockItem(Gilde ovnsbakt leverpostei), StockItem(Gilde ovnsbakt leverpostei original), StockItem(Norvegia ost 1 kg), StockItem(Kornbrød skåret 750g), StockItem(Go strawberry & kiwi), StockItem(Go orange & mango), StockItem(Idun Tørrgjær 5pk), StockItem(Idun tørrgjær søt), StockItem(Idun tørrgjær pizza), StockItem(Dr.Oetker Sprinkles Mix), StockItem(Coop kokt skinke), StockItem(Coop hamburgerrygg), StockItem(WC duck fresh disc lavender), StockItem(Gunry liquid soap carambola), StockItem(Gunry liquid soap pineapple), StockItem(Whiskas maxi pack 40 stk), StockItem(Ariel A+ Giga pack 174 vasker), StockItem(Finish powerball mega pack), StockItem(Kanel Santa Maria glass), StockItem(Rema 1000 Potetsalat), StockItem(Rema 1000 tyttebærsylte), StockItem(Havrebrød), StockItem(Rema hverdagsbrød kneipp), StockItem(Rema Grovbrød), StockItem(Sunniva original tropisk), StockItem(Gilde Bøkerøkt svinerull), StockItem(Gilde favorittskinke), StockItem(Rema 1000 XXL mørpølse), StockItem(Coop puffet ris), StockItem(Coop fusilli pasta), StockItem(Xtra kneippbrød), StockItem(Coop müsli), StockItem(Nature moments shampoo), StockItem(Grilstad Trønderfår), StockItem(Xtra tagliatelle pasta), StockItem(Coop kidneybønner), StockItem(Coop Bringebærsy
09-09 23:29:07.927 21581 21581 I stock   : downloadVolatile: success
09-09 23:29:07.930 21581 21581 I stock   : downloadVolatile: expiring = [StockItem(Viltsaus), StockItem(Tine lettmelk 1.75L)]
09-09 23:29:07.934 21581 21581 I stock   : downloadVolatile: expired = [StockItem(Grovbrød), StockItem(Kyllingfilet First Price), StockItem(Cornflakes 500g), StockItem(Kyllingkjøtt), StockItem(Pizzasaus coop), StockItem(Pizzapepperoni), StockItem(Crème Fraîche), StockItem(Coop rømmedressing), StockItem(Sriracha Chili Saus), StockItem(Påleggsskinke), StockItem(Hjortesteik), StockItem(Kornbrød skåret 750g), StockItem(Coop kokt skinke), StockItem(Coop hamburgerrygg)]
09-09 23:29:07.935 21581 21581 I stock   : downloadVolatile: missing = [MissingItem(Potetmos med gressløk og melk), MissingItem(Grovbrød), MissingItem(Egg), MissingItem(Clean Drop Rens kaffimaskin)]
09-09 23:29:08.499 21581 21581 I stock   : download ProductDetails: ProductDetails(Clean Drop Rens kaffimaskin)
09-09 23:29:08.515 21581 21581 I stock   : download ProductDetails: ProductDetails(Egg)
09-09 23:29:08.516 21581 21581 I stock   : filterItems: filter = all, display = all
09-09 23:29:08.517 21581 21581 I stock   : filterItems: filteredItems = [StockItem(Karbonadekaker First Price), StockItem(Potetmos med gressløk og melk), StockItem(Vann), StockItem(Maiskorn 3-pack), StockItem(Sukker), StockItem(Aluminiumsfolie), StockItem(Pizza- og bakeark), StockItem(Brødposer), StockItem(Friele Filterkaffe original), StockItem(Bomullspinner (Q-Tips) ), StockItem(Grovbrød), StockItem(Brokkoliblanding), StockItem(Lapskausblanding), StockItem(Strandamør), StockItem(Meksikansk gryte), StockItem(Bali kyllinggryte), StockItem(Blomkål og brokkolisuppe), StockItem(Barilla Pesto alla genovese (grønn) ), StockItem(Agurk), StockItem(Tannkrem), StockItem(Kjøttpølse uten skinn), StockItem(Kyllingfilet First Price), StockItem(Avfallsposer med håndtak (First Price) ), StockItem(Norvegia ost 1.3 kg), StockItem(Sun 3i1 Glansmiddel), StockItem(Cornflakes 500g), StockItem(Strandamør snacks 250g), StockItem(Soft flora), StockItem(Flytende håndsåpe), StockItem(Biff), StockItem(Hjortekjøtt), StockItem(Fun light Cloudy Apple), StockItem(Folkets Pepperoni Pizza), StockItem(Oppvaskmaskintabletter), StockItem(Toro Jegergryte), StockItem(Dr Greve Sensitive Intimvask), StockItem(Trønderfår), StockItem(Polpa finissima), StockItem(Nypoteter), StockItem(Idun tomatketchup), StockItem(Kjøttdeig 600gram), StockItem(Comfort tøymykner mandarin), StockItem(Melange), StockItem(Kyllingkjøtt), StockItem(Dampamår av hjort), StockItem(Poteter), StockItem(Eldorado Utsteinede Oliven svart), StockItem(Siktet hvetemel 2kg), StockItem(Gudbrandsdalost), StockItem(Crème fraîche), StockItem(Viltsaus), StockItem(Jegergryte), StockItem(Nugatti), StockItem(Mors hjemmebakte Pizzagjær), StockItem(Coop kjøttkakesaus), StockItem(Xtra bearnaisesaus), StockItem(Xtra makaroni), StockItem(Pizzasaus coop), StockItem(Pizzapepperoni), StockItem(Crème Fraîche), StockItem(Avfallsposer 46L Coop), StockItem(Coop rømmedressing), StockItem(Tine lettmelk 1.75L), StockItem(Toro Lasagne Italiensk), StockItem(Saft), StockItem(Sriracha Chili Saus), StockItem(Søppelsekker), StockItem(Engangshansker), StockItem(Gudbrandsdalsost 1kg), StockItem(Folie), StockItem(Lapskausblanding Norrek 2kg), StockItem(Farfalle), StockItem(Fusilli), StockItem(Pasta penne), StockItem(Regal siktet hvetemel 2 kg), StockItem(Pommes frites 1.2kg), StockItem(Wokblanding coop), StockItem(Påleggsskinke), StockItem(Hel pepper sort), StockItem(Ming Grøtris), StockItem(Grønnsaksbuljong), StockItem(Kjøttbuljong), StockItem(Rapsolje), StockItem(Kanel), StockItem(Leverpostei), StockItem(Kardemomme), StockItem(Vaniljekrem), StockItem(Melis Dansukker), StockItem(Coop Kokosmasse), StockItem(Kokosolje), StockItem(Laksefilet naturell 4pk), StockItem(Hjortesteik), StockItem(Xtra baconost), StockItem(Idun tomatketchup Hot chili), StockItem(Loreal thermic resist), StockItem(Gilde ovnsbakt leverpostei), StockItem(Gilde ovnsbakt leverpostei original), StockItem(Norvegia ost 1 kg), StockItem(Kornbrød skåret 750g), StockItem(Go strawberry & kiwi), StockItem(Go orange & mango), StockItem(Idun Tørrgjær 5pk), StockItem(Idun tørrgjær søt), StockItem(Idun tørrgjær pizza), StockItem(Dr.Oetker Sprinkles Mix), StockItem(Coop kokt skinke), StockItem(Coop hamburgerrygg), StockItem(WC duck fresh disc lavender), StockItem(Gunry liquid soap carambola), StockItem(Gunry liquid soap pineapple), StockItem(Whiskas maxi pack 40 stk), StockItem(Ariel A+ Giga pack 174 vasker), StockItem(Finish powerball mega pack), StockItem(Kanel Santa Maria glass), StockItem(Rema 1000 Potetsalat), StockItem(Rema 1000 tyttebærsylte), StockItem(Havrebrød), StockItem(Rema hverdagsbrød kneipp), StockItem(Rema Grovbrød), StockItem(Sunniva original tropisk), StockItem(Gilde Bøkerøkt svinerull), StockItem(Gilde favorittskinke), StockItem(Rema 1000 XXL mørpølse), StockItem(Coop puffet ris), StockItem(Coop fusilli pasta), StockItem(Xtra kneippbrød), StockItem(Coop müsli), StockItem(Nature moments shampoo), StockItem(Grilstad Trønderfår), StockItem(Xtra tagliatelle pasta), StockItem(Coop kidneybønner), StockItem(Coop Brin
09-09 23:29:08.517 21581 21581 I stock   : sortItems: sort by best_before, ascending = true
09-09 23:29:09.946 21581 21581 I HwViewRootImpl: removeInvalidNode jank list is null
09-09 23:29:10.235 21581 21608 W libEGL  : EGLNativeWindowType 0x787e475710 disconnect failed
09-09 23:29:10.645 21581 21581 I MainActivity: showBottomSheet: DrawerBottomSheet
09-09 23:29:10.727 21581 21581 I DrawerBottomSheet: onCreateView: uiMode = stock_default
09-09 23:29:11.836 21581 21581 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-09 23:29:12.258 21581 21608 W libEGL  : EGLNativeWindowType 0x787e475710 disconnect failed
09-09 23:29:12.771 21581 21608 W libEGL  : EGLNativeWindowType 0x787c5565d0 disconnect failed
09-09 23:29:12.778 21581 21581 I n       : saved state: isPrimary = true
09-09 23:29:13.301 21581 21581 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-09 23:29:13.344 21581 21581 W HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:32.505188, limit is:51The moving distance of Y is:83.5155, limit is:51
09-09 23:29:15.624 21581 21608 W libEGL  : EGLNativeWindowType 0x787e475710 disconnect failed
09-09 23:29:16.694 21581 21581 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-09 23:29:17.259 21581 21608 W libEGL  : EGLNativeWindowType 0x7906cf0a50 disconnect failed

**Comment by patzly** [comment]
Thank you! We'll take a look into it.

**Comment by MrJohnZoidberg** [comment]
We're sorry for the long waiting period, but we currently don't have enough time to concentrate on our app.

**Comment by donk7413** [comment]
Can you provide a bigger log file ? 
I think it's list iteraion error but i can't see where in the code.

Did this happens when you consume a item and the amount become 0 ?

**Comment by MrJohnZoidberg** [comment]
@donk7413 Thanks for helping us with that. :-)

**Comment by donk7413** [comment]
No thanks, I really enjoy the app and the works. And I use it for my house management combined with a local AI and cook helpers, so I have a lot of needs. so if I can help, I do it. 🙂

**Comment by MrJohnZoidberg** [comment]
In the new version 2.0.0 of our app there won't be separate pages for batch mode anymore. The code was really ugly and I found a new way to implement a "Scan mode" just like on the web interface. So there will only be forms for purchase and consume which have the ability to scan barcodes and ask for missing information.
So this issue can be closed because the code which contains the mistake/error will be removed.
